-- =============================================================================
-- Migration: 20260613041303_criar_modelos_descricao_cirurgica
-- Aggregate: ModeloDescricaoCirurgica (bounded context Prontuários)
-- Aplicado:  pela pipeline CI/CD via deploy/scripts/migrate.sh (psql)
-- Transação: gerenciada externamente — NÃO adicionar BEGIN/COMMIT aqui
-- =============================================================================
--
-- Padrão live-link (mesmo de ProntuarioVariavelPool):
--   eh_padrao_sistema = true  → estabelecimento_id = NULL  (global, todos os tenants)
--   eh_padrao_sistema = false → estabelecimento_id NOT NULL (só do estabelecimento)
-- Query de leitura: WHERE (eh_padrao_sistema = true OR estabelecimento_id = @EstabelecimentoId)
--
-- FK para estabelecimentos: ON DELETE RESTRICT (padrão do projeto).
-- Omitida no EF Configuration (sem HasOne) pois é nullable — adicionada manualmente aqui.
-- =============================================================================

-- ── Tabela ───────────────────────────────────────────────────────────────────

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260613041303_CriarModeloDescricaoCirurgica') THEN

    CREATE TABLE IF NOT EXISTS public.modelos_descricao_cirurgica (
        id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        estabelecimento_id bigint       NULL,
        titulo             varchar(200) NOT NULL,
        corpo              text         NOT NULL,
        ativo              boolean      NOT NULL DEFAULT true,
        eh_padrao_sistema  boolean      NOT NULL DEFAULT false,
        criado_em          timestamptz  NOT NULL,
        atualizado_em      timestamptz  NULL
    );

    END IF;
END $EF$;

-- ── FK para estabelecimentos (nullable — padrão-sistema tem NULL) ─────────────

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260613041303_CriarModeloDescricaoCirurgica') THEN

    DO $$
    BEGIN
        IF NOT EXISTS (
            SELECT 1 FROM pg_constraint
            WHERE conname = 'fk_modelo_desc_cirurgica_estabelecimento'
              AND conrelid = 'public.modelos_descricao_cirurgica'::regclass
        ) THEN
            ALTER TABLE public.modelos_descricao_cirurgica
                ADD CONSTRAINT fk_modelo_desc_cirurgica_estabelecimento
                FOREIGN KEY (estabelecimento_id)
                REFERENCES public.estabelecimentos (id)
                ON DELETE RESTRICT;
        END IF;
    END $$;

    END IF;
END $EF$;

-- ── Índices ───────────────────────────────────────────────────────────────────
-- ix_modelo_desc_cirurgica_estabelecimento: suporte à query de leitura tenant
-- ix_modelo_desc_cirurgica_padrao: filtro rápido de padrão-sistema

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260613041303_CriarModeloDescricaoCirurgica') THEN

    CREATE INDEX IF NOT EXISTS ix_modelo_desc_cirurgica_estabelecimento
        ON public.modelos_descricao_cirurgica (estabelecimento_id);

    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260613041303_CriarModeloDescricaoCirurgica') THEN

    CREATE INDEX IF NOT EXISTS ix_modelo_desc_cirurgica_padrao
        ON public.modelos_descricao_cirurgica (eh_padrao_sistema);

    END IF;
END $EF$;

-- ── Registro em __ef_migrations_history ──────────────────────────────────────

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260613041303_CriarModeloDescricaoCirurgica') THEN
    INSERT INTO public.__ef_migrations_history ("MigrationId", "ProductVersion")
    VALUES ('20260613041303_CriarModeloDescricaoCirurgica', '10.0.0');
    END IF;
END $EF$;
