
DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260516135216_ConfigOrcamentoAbas2') THEN
    ALTER TABLE public.orcamento_catalogo_produto ADD codigo_sku character varying(40);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260516135216_ConfigOrcamentoAbas2') THEN
    ALTER TABLE public.orcamento_catalogo_produto ADD fornecedor_nome character varying(200);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260516135216_ConfigOrcamentoAbas2') THEN
    ALTER TABLE public.orcamento_catalogo_produto ADD marca character varying(120);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260516135216_ConfigOrcamentoAbas2') THEN
    ALTER TABLE public.orcamento_catalogo_produto ADD tipo character varying(20) NOT NULL DEFAULT 'Outros';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260516135216_ConfigOrcamentoAbas2') THEN
    ALTER TABLE public.orcamento_catalogo_produto ADD unidade character varying(20) NOT NULL DEFAULT 'un';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260516135216_ConfigOrcamentoAbas2') THEN
    ALTER TABLE public.orcamento_catalogo_cirurgia_produto ADD incluido boolean NOT NULL DEFAULT TRUE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260516135216_ConfigOrcamentoAbas2') THEN
    ALTER TABLE public.orcamento_catalogo_cirurgia ADD categoria character varying(80);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260516135216_ConfigOrcamentoAbas2') THEN
    ALTER TABLE public.orcamento_catalogo_cirurgia ADD codigo_interno character varying(40);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260516135216_ConfigOrcamentoAbas2') THEN
    ALTER TABLE public.orcamento_catalogo_cirurgia ADD codigo_tuss character varying(20);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260516135216_ConfigOrcamentoAbas2') THEN
    CREATE TABLE public.orcamento_anestesista (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        estabelecimento_id bigint NOT NULL,
        profissional_usuario_id uuid,
        nome character varying(200) NOT NULL,
        crm character varying(40),
        especialidade character varying(120),
        telefone character varying(40),
        tabela_honorarios character varying(80),
        ativo boolean NOT NULL DEFAULT TRUE,
        criada_em timestamp with time zone NOT NULL,
        atualizada_em timestamp with time zone,
        CONSTRAINT "PK_orcamento_anestesista" PRIMARY KEY (id),
        CONSTRAINT fk_orcamento_anestesista_estabelecimento FOREIGN KEY (estabelecimento_id) REFERENCES public.estabelecimentos (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260516135216_ConfigOrcamentoAbas2') THEN
    CREATE TABLE public.orcamento_team_role (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        estabelecimento_id bigint NOT NULL,
        papel character varying(80) NOT NULL,
        profissional_usuario_id uuid,
        nome_padrao character varying(200),
        tipo_honorario character varying(20) NOT NULL,
        valor numeric(12,2) NOT NULL,
        base_calculo character varying(40) NOT NULL,
        ativo boolean NOT NULL DEFAULT TRUE,
        criada_em timestamp with time zone NOT NULL,
        atualizada_em timestamp with time zone,
        CONSTRAINT "PK_orcamento_team_role" PRIMARY KEY (id),
        CONSTRAINT fk_orcamento_team_role_estabelecimento FOREIGN KEY (estabelecimento_id) REFERENCES public.estabelecimentos (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260516135216_ConfigOrcamentoAbas2') THEN
    CREATE TABLE public.orcamento_anestesista_faixa (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        anestesista_id bigint NOT NULL,
        descricao character varying(120) NOT NULL,
        valor numeric(12,2) NOT NULL,
        ordem integer NOT NULL,
        CONSTRAINT "PK_orcamento_anestesista_faixa" PRIMARY KEY (id),
        CONSTRAINT fk_anestesista_faixa_anestesista FOREIGN KEY (anestesista_id) REFERENCES public.orcamento_anestesista (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260516135216_ConfigOrcamentoAbas2') THEN
    CREATE TABLE public.orcamento_pacote (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        estabelecimento_id bigint NOT NULL,
        nome character varying(200) NOT NULL,
        descricao character varying(500),
        anestesista_id bigint,
        valor_total_sugerido numeric(12,2),
        ativo boolean NOT NULL DEFAULT TRUE,
        criada_em timestamp with time zone NOT NULL,
        atualizada_em timestamp with time zone,
        CONSTRAINT "PK_orcamento_pacote" PRIMARY KEY (id),
        CONSTRAINT fk_orcamento_pacote_anestesista FOREIGN KEY (anestesista_id) REFERENCES public.orcamento_anestesista (id) ON DELETE RESTRICT,
        CONSTRAINT fk_orcamento_pacote_estabelecimento FOREIGN KEY (estabelecimento_id) REFERENCES public.estabelecimentos (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260516135216_ConfigOrcamentoAbas2') THEN
    CREATE TABLE public.orcamento_pacote_procedimento (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        pacote_id bigint NOT NULL,
        catalogo_cirurgia_id bigint NOT NULL,
        ordem integer NOT NULL,
        CONSTRAINT "PK_orcamento_pacote_procedimento" PRIMARY KEY (id),
        CONSTRAINT fk_pacote_procedimento_cirurgia FOREIGN KEY (catalogo_cirurgia_id) REFERENCES public.orcamento_catalogo_cirurgia (id) ON DELETE RESTRICT,
        CONSTRAINT fk_pacote_procedimento_pacote FOREIGN KEY (pacote_id) REFERENCES public.orcamento_pacote (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260516135216_ConfigOrcamentoAbas2') THEN
    CREATE TABLE public.orcamento_pacote_produto (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        pacote_id bigint NOT NULL,
        catalogo_produto_id bigint NOT NULL,
        quantidade numeric(10,3) NOT NULL,
        CONSTRAINT "PK_orcamento_pacote_produto" PRIMARY KEY (id),
        CONSTRAINT fk_pacote_produto_pacote FOREIGN KEY (pacote_id) REFERENCES public.orcamento_pacote (id) ON DELETE CASCADE,
        CONSTRAINT fk_pacote_produto_produto FOREIGN KEY (catalogo_produto_id) REFERENCES public.orcamento_catalogo_produto (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260516135216_ConfigOrcamentoAbas2') THEN
    CREATE TABLE public.orcamento_pacote_team_role (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        pacote_id bigint NOT NULL,
        team_role_id bigint NOT NULL,
        CONSTRAINT "PK_orcamento_pacote_team_role" PRIMARY KEY (id),
        CONSTRAINT fk_pacote_team_role_pacote FOREIGN KEY (pacote_id) REFERENCES public.orcamento_pacote (id) ON DELETE CASCADE,
        CONSTRAINT fk_pacote_team_role_team_role FOREIGN KEY (team_role_id) REFERENCES public.orcamento_team_role (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260516135216_ConfigOrcamentoAbas2') THEN
    CREATE INDEX ix_orcamento_anestesista_estab_ativo ON public.orcamento_anestesista (estabelecimento_id, ativo);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260516135216_ConfigOrcamentoAbas2') THEN
    CREATE UNIQUE INDEX uq_anestesista_faixa_descricao ON public.orcamento_anestesista_faixa (anestesista_id, descricao);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260516135216_ConfigOrcamentoAbas2') THEN
    CREATE INDEX "IX_orcamento_pacote_anestesista_id" ON public.orcamento_pacote (anestesista_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260516135216_ConfigOrcamentoAbas2') THEN
    CREATE INDEX ix_orcamento_pacote_estab_ativo ON public.orcamento_pacote (estabelecimento_id, ativo);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260516135216_ConfigOrcamentoAbas2') THEN
    CREATE INDEX "IX_orcamento_pacote_procedimento_catalogo_cirurgia_id" ON public.orcamento_pacote_procedimento (catalogo_cirurgia_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260516135216_ConfigOrcamentoAbas2') THEN
    CREATE UNIQUE INDEX uq_pacote_procedimento ON public.orcamento_pacote_procedimento (pacote_id, catalogo_cirurgia_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260516135216_ConfigOrcamentoAbas2') THEN
    CREATE INDEX "IX_orcamento_pacote_produto_catalogo_produto_id" ON public.orcamento_pacote_produto (catalogo_produto_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260516135216_ConfigOrcamentoAbas2') THEN
    CREATE UNIQUE INDEX uq_pacote_produto ON public.orcamento_pacote_produto (pacote_id, catalogo_produto_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260516135216_ConfigOrcamentoAbas2') THEN
    CREATE INDEX "IX_orcamento_pacote_team_role_team_role_id" ON public.orcamento_pacote_team_role (team_role_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260516135216_ConfigOrcamentoAbas2') THEN
    CREATE UNIQUE INDEX uq_pacote_team_role ON public.orcamento_pacote_team_role (pacote_id, team_role_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260516135216_ConfigOrcamentoAbas2') THEN
    CREATE INDEX ix_orcamento_team_role_estab_ativo ON public.orcamento_team_role (estabelecimento_id, ativo);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260516135216_ConfigOrcamentoAbas2') THEN
    INSERT INTO public.__ef_migrations_history ("MigrationId", "ProductVersion")
    VALUES ('20260516135216_ConfigOrcamentoAbas2', '10.0.0');
    END IF;
END $EF$;

