-- Migration: CriarCategoriaFinanceiraPadraoSistema
-- Tabela global de categorias financeiras padrão da plataforma (briefing 2026-06-22_003 M1).
-- Sem estabelecimento_id — escopo plataforma. Acesso exclusivo pelo admin global.
-- Gerado via: dotnet ef migrations script ... --idempotent
-- START TRANSACTION/COMMIT removidos — a pipeline (migrate.sh) gerencia a transação.

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260623003204_CriarCategoriaFinanceiraPadraoSistema') THEN
    CREATE TABLE IF NOT EXISTS public.categorias_financeiras_padrao_sistema (
        id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        nome          character varying(80)           NOT NULL,
        tipo          character varying(10)           NOT NULL,
        ativo         boolean                         NOT NULL DEFAULT true,
        criada_em     timestamp with time zone        NOT NULL,
        atualizada_em timestamp with time zone        NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260623003204_CriarCategoriaFinanceiraPadraoSistema') THEN
    CREATE UNIQUE INDEX IF NOT EXISTS uq_categorias_financeiras_padrao_sistema_nome_tipo
        ON public.categorias_financeiras_padrao_sistema (nome, tipo);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260623003204_CriarCategoriaFinanceiraPadraoSistema') THEN
    INSERT INTO public.__ef_migrations_history ("MigrationId", "ProductVersion")
    VALUES ('20260623003204_CriarCategoriaFinanceiraPadraoSistema', '10.0.0');
    END IF;
END $EF$;
