-- Migration: 20260610200104_CriarModuloCobrancasF1
-- Módulo Financeiro/Cobranças — F1: Fundação + Consulta (briefing 2026-06-10_009)
-- Tabelas novas: cobrancas, pagamentos, tabela_preco_consulta, config_taxa_forma_pagamento
-- ALTER: lancamentos ganha cobranca_id e pagamento_id
-- Idempotente via guards __EFMigrationsHistory (BEGIN/COMMIT removidos — pipeline gerencia a transação)

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260610200104_CriarModuloCobrancasF1') THEN
    ALTER TABLE public.lancamentos ADD cobranca_id bigint;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260610200104_CriarModuloCobrancasF1') THEN
    ALTER TABLE public.lancamentos ADD pagamento_id bigint;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260610200104_CriarModuloCobrancasF1') THEN
    CREATE TABLE public.cobrancas (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        estabelecimento_id bigint NOT NULL,
        paciente_id bigint NOT NULL,
        origem character varying(50) NOT NULL,
        agendamento_id bigint,
        orcamento_id bigint,
        tipo_atendimento character varying(20) NOT NULL,
        convenio_id bigint,
        valor_cobrado numeric(12,2) NOT NULL,
        desconto numeric(12,2) NOT NULL DEFAULT 0.0,
        status character varying(20) NOT NULL,
        descricao character varying(300),
        criado_por_usuario_id uuid NOT NULL,
        criado_em timestamp with time zone NOT NULL,
        atualizado_em timestamp with time zone,
        CONSTRAINT "PK_cobrancas" PRIMARY KEY (id),
        CONSTRAINT fk_cobrancas_estabelecimento FOREIGN KEY (estabelecimento_id) REFERENCES public.estabelecimentos (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260610200104_CriarModuloCobrancasF1') THEN
    CREATE TABLE public.config_taxa_forma_pagamento (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        estabelecimento_id bigint NOT NULL,
        forma_pagamento_id bigint NOT NULL,
        taxa_percentual numeric(6,3) NOT NULL DEFAULT 0.0,
        ativo boolean NOT NULL DEFAULT TRUE,
        criado_em timestamp with time zone NOT NULL,
        atualizado_em timestamp with time zone,
        CONSTRAINT "PK_config_taxa_forma_pagamento" PRIMARY KEY (id),
        CONSTRAINT fk_config_taxa_forma_pagamento_estabelecimento FOREIGN KEY (estabelecimento_id) REFERENCES public.estabelecimentos (id) ON DELETE RESTRICT,
        CONSTRAINT fk_config_taxa_forma_pagamento_forma FOREIGN KEY (forma_pagamento_id) REFERENCES public.formas_pagamento (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260610200104_CriarModuloCobrancasF1') THEN
    CREATE TABLE public.tabela_preco_consulta (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        estabelecimento_id bigint NOT NULL,
        profissional_id uuid,
        valor_sugerido numeric(12,2) NOT NULL,
        ativo boolean NOT NULL DEFAULT TRUE,
        criado_em timestamp with time zone NOT NULL,
        atualizado_em timestamp with time zone,
        CONSTRAINT "PK_tabela_preco_consulta" PRIMARY KEY (id),
        CONSTRAINT fk_tabela_preco_consulta_estabelecimento FOREIGN KEY (estabelecimento_id) REFERENCES public.estabelecimentos (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260610200104_CriarModuloCobrancasF1') THEN
    CREATE TABLE public.pagamentos (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        cobranca_id bigint NOT NULL,
        valor numeric(12,2) NOT NULL,
        forma_pagamento_id bigint NOT NULL,
        parcelas integer NOT NULL DEFAULT 1,
        juros numeric(12,2) NOT NULL DEFAULT 0.0,
        taxa numeric(12,2) NOT NULL DEFAULT 0.0,
        data_pagamento date NOT NULL,
        registrado_por_usuario_id uuid NOT NULL,
        lancamento_id bigint,
        criado_em timestamp with time zone NOT NULL,
        CONSTRAINT "PK_pagamentos" PRIMARY KEY (id),
        CONSTRAINT fk_pagamentos_cobranca FOREIGN KEY (cobranca_id) REFERENCES public.cobrancas (id) ON DELETE RESTRICT,
        CONSTRAINT fk_pagamentos_forma_pagamento FOREIGN KEY (forma_pagamento_id) REFERENCES public.formas_pagamento (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

-- Índices --

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260610200104_CriarModuloCobrancasF1') THEN
    CREATE INDEX ix_lancamentos_cobranca_id ON public.lancamentos (cobranca_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260610200104_CriarModuloCobrancasF1') THEN
    CREATE INDEX ix_cobrancas_agendamento_id ON public.cobrancas (agendamento_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260610200104_CriarModuloCobrancasF1') THEN
    CREATE INDEX ix_cobrancas_estab_paciente ON public.cobrancas (estabelecimento_id, paciente_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260610200104_CriarModuloCobrancasF1') THEN
    CREATE INDEX ix_cobrancas_estab_status ON public.cobrancas (estabelecimento_id, status);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260610200104_CriarModuloCobrancasF1') THEN
    CREATE INDEX ix_config_taxa_forma_pagamento_forma_id ON public.config_taxa_forma_pagamento (forma_pagamento_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260610200104_CriarModuloCobrancasF1') THEN
    CREATE UNIQUE INDEX uq_config_taxa_forma_pagamento_estab_forma ON public.config_taxa_forma_pagamento (estabelecimento_id, forma_pagamento_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260610200104_CriarModuloCobrancasF1') THEN
    CREATE INDEX ix_pagamentos_cobranca_id ON public.pagamentos (cobranca_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260610200104_CriarModuloCobrancasF1') THEN
    CREATE INDEX ix_pagamentos_forma_pagamento_id ON public.pagamentos (forma_pagamento_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260610200104_CriarModuloCobrancasF1') THEN
    CREATE INDEX ix_tabela_preco_consulta_estab_profissional ON public.tabela_preco_consulta (estabelecimento_id, profissional_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260610200104_CriarModuloCobrancasF1') THEN
    INSERT INTO public.__ef_migrations_history ("MigrationId", "ProductVersion")
    VALUES ('20260610200104_CriarModuloCobrancasF1', '10.0.0');
    END IF;
END $EF$;
