-- Migration: 20260615220000_criar_tabela_migracao_job_eventos
-- Addendum 003 — briefing 2026-06-15_004 (Central de Migração)
--
-- 1. Cria migracao_job_eventos: trilha forward-only de transições de status do job.
-- 2. Cria índice ix_migracao_jobs_estab_criado_em em migracao_jobs.
-- 3. Confirma que ix_migracao_registros_job_status já existe (não recria).
--
-- Sem PII — só metadados de transição (status_anterior, status_novo, usuario_id).
-- Multi-tenant: estabelecimento_id herdado do job.
--
-- IMPORTANTE: BEGIN/COMMIT removidos — a pipeline (migrate.sh) gerencia a transação.

-- ── 1. Tabela migracao_job_eventos ──────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.migracao_job_eventos (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    migracao_job_id    BIGINT       NOT NULL,
    estabelecimento_id BIGINT       NOT NULL,
    status_anterior    TEXT         NULL,      -- null = evento de criação do job
    status_novo        TEXT         NOT NULL,
    usuario_id         UUID         NULL,      -- null = sistema/job recorrente
    criado_em          TIMESTAMPTZ  NOT NULL,
    CONSTRAINT fk_migracao_job_eventos_job
        FOREIGN KEY (migracao_job_id)
        REFERENCES public.migracao_jobs (id)
        ON DELETE CASCADE
);

COMMENT ON TABLE public.migracao_job_eventos IS
    'Trilha forward-only de transições de status de migracao_jobs. Sem PII. Addendum 003 briefing 2026-06-15_004.';

COMMENT ON COLUMN public.migracao_job_eventos.status_anterior IS
    'Null apenas no evento de criação do job (status anterior inexistente).';

COMMENT ON COLUMN public.migracao_job_eventos.usuario_id IS
    'Null = sistema/job recorrente; preenchido = admin que executou a ação.';

-- ── 2. Índice: timeline cronológica de um job ────────────────────────────────────

CREATE INDEX IF NOT EXISTS ix_migracao_job_eventos_job_criado_em
    ON public.migracao_job_eventos (migracao_job_id, criado_em);

-- ── 3. Índice: listagem admin de jobs por período ────────────────────────────────
-- Cobre: WHERE estabelecimento_id = $1 AND criado_em BETWEEN $2 AND $3
--        ORDER BY criado_em DESC
-- Índices existentes ix_migracao_jobs_estab_status e ix_migracao_jobs_estab_onda_status
-- não cobrem criado_em — este índice é necessário.

CREATE INDEX IF NOT EXISTS ix_migracao_jobs_estab_criado_em
    ON public.migracao_jobs (estabelecimento_id, criado_em DESC);

-- ── 4. Confirmação: ix_migracao_registros_job_status ────────────────────────────
-- O índice (migracao_job_id, status) em migracao_registros JÁ EXISTE desde
-- 20260615152934_criar_tabelas_migracao.sql. Não recriar.
-- Confirmado via inspeção da migration original (linhas 173-176).

-- Registro da migration aplicada (idempotente via ON CONFLICT).
INSERT INTO public."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260615220000_CriarTabelaMigracaoJobEventos', '10.0.0')
ON CONFLICT DO NOTHING;
