-- =============================================================================
-- F7 — Caixa diário, config de comissão, cobranca_id em movimentacoes_estoque
-- Briefing: 2026-06-11_001_financeiro-f7-consolidacao.md
-- Migration EF: 20260611050119_CriarCaixaDiarioComissaoCobrancaEstoqueF7
-- Aplicado por: deploy/scripts/migrate.sh (psql) — sem BEGIN/COMMIT aqui.
-- =============================================================================

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260611050119_CriarCaixaDiarioComissaoCobrancaEstoqueF7') THEN
    ALTER TABLE public.movimentacoes_estoque ADD cobranca_id bigint;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260611050119_CriarCaixaDiarioComissaoCobrancaEstoqueF7') THEN
    CREATE TABLE public.caixa_diario (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        estabelecimento_id bigint NOT NULL,
        data date NOT NULL,
        status character varying(20) NOT NULL,
        aberto_por_usuario_id uuid NOT NULL,
        aberto_em timestamp with time zone NOT NULL,
        fechado_por_usuario_id uuid,
        fechado_em timestamp with time zone,
        observacao character varying(500),
        reaberto_por_usuario_id uuid,
        reaberto_em timestamp with time zone,
        criado_em timestamp with time zone NOT NULL,
        atualizado_em timestamp with time zone,
        CONSTRAINT "PK_caixa_diario" PRIMARY KEY (id),
        CONSTRAINT fk_caixa_diario_estabelecimento FOREIGN KEY (estabelecimento_id) REFERENCES public.estabelecimentos (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260611050119_CriarCaixaDiarioComissaoCobrancaEstoqueF7') THEN
    CREATE TABLE public.config_comissao_profissional (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        estabelecimento_id bigint NOT NULL,
        profissional_usuario_id uuid NOT NULL,
        tipo character varying(20) NOT NULL,
        percentual numeric(5,2) NOT NULL,
        criado_em timestamp with time zone NOT NULL,
        atualizado_em timestamp with time zone,
        CONSTRAINT "PK_config_comissao_profissional" PRIMARY KEY (id),
        CONSTRAINT fk_config_comissao_estabelecimento FOREIGN KEY (estabelecimento_id) REFERENCES public.estabelecimentos (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260611050119_CriarCaixaDiarioComissaoCobrancaEstoqueF7') THEN
    CREATE INDEX ix_movimentacao_cobranca_id ON public.movimentacoes_estoque (cobranca_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260611050119_CriarCaixaDiarioComissaoCobrancaEstoqueF7') THEN
    CREATE INDEX IF NOT EXISTS ix_lancamentos_estab_data_pagamento ON public.lancamentos (estabelecimento_id, data_pagamento);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260611050119_CriarCaixaDiarioComissaoCobrancaEstoqueF7') THEN
    CREATE INDEX ix_lancamentos_estab_data_pagamento_pago ON public.lancamentos (estabelecimento_id, data_pagamento) WHERE status = 'Pago';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260611050119_CriarCaixaDiarioComissaoCobrancaEstoqueF7') THEN
    CREATE INDEX IF NOT EXISTS ix_pagamentos_data_pagamento ON public.pagamentos (data_pagamento);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260611050119_CriarCaixaDiarioComissaoCobrancaEstoqueF7') THEN
    CREATE UNIQUE INDEX uq_caixa_diario_estab_data ON public.caixa_diario (estabelecimento_id, data);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260611050119_CriarCaixaDiarioComissaoCobrancaEstoqueF7') THEN
    CREATE UNIQUE INDEX uq_config_comissao_estab_prof_tipo ON public.config_comissao_profissional (estabelecimento_id, profissional_usuario_id, tipo);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260611050119_CriarCaixaDiarioComissaoCobrancaEstoqueF7') THEN
    INSERT INTO public.__ef_migrations_history ("MigrationId", "ProductVersion")
    VALUES ('20260611050119_CriarCaixaDiarioComissaoCobrancaEstoqueF7', '10.0.0');
    END IF;
END $EF$;
