
DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260520014048_CriarTermosDeConsentimento') THEN
    ALTER TABLE public.estabelecimentos ADD cidade character varying(100);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260520014048_CriarTermosDeConsentimento') THEN
    ALTER TABLE public.estabelecimentos ADD estado character(2);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260520014048_CriarTermosDeConsentimento') THEN
    CREATE TABLE public.termo_audit_log (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        estabelecimento_id bigint,
        usuario_id uuid,
        acao character varying(60) NOT NULL,
        entidade character varying(40) NOT NULL,
        entidade_id bigint NOT NULL,
        metadata_json jsonb,
        ip_origem character varying(45),
        criado_em timestamp with time zone NOT NULL,
        CONSTRAINT "PK_termo_audit_log" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260520014048_CriarTermosDeConsentimento') THEN
    CREATE TABLE public.termo_emitido (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        paciente_id bigint NOT NULL,
        estabelecimento_id bigint NOT NULL,
        termo_modelo_id bigint NOT NULL,
        versao_modelo integer NOT NULL,
        conteudo_snapshot_html text NOT NULL,
        conteudo_snapshot_texto text NOT NULL,
        status character varying(20) NOT NULL,
        assinatura_tipo character varying(20) NOT NULL,
        assinado_em timestamp with time zone,
        ip_assinatura character varying(45),
        user_agent_assinatura character varying(500),
        hash_integridade character(64) NOT NULL,
        pdf_url character varying(500),
        pdf_hash character(64),
        token_aceite character varying(64),
        token_expira_em timestamp with time zone,
        revogado_em timestamp with time zone,
        revogado_por_usuario_id uuid,
        revogado_motivo character varying(500),
        emitido_por_usuario_id uuid NOT NULL,
        criado_em timestamp with time zone NOT NULL,
        atualizado_em timestamp with time zone,
        CONSTRAINT "PK_termo_emitido" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260520014048_CriarTermosDeConsentimento') THEN
    CREATE TABLE public.termo_emitido_acesso_log (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        termo_emitido_id bigint NOT NULL,
        ip_origem character varying(45),
        user_agent character varying(500),
        acao character varying(30) NOT NULL,
        criado_em timestamp with time zone NOT NULL,
        CONSTRAINT "PK_termo_emitido_acesso_log" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260520014048_CriarTermosDeConsentimento') THEN
    CREATE TABLE public.termo_modelo (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        estabelecimento_id bigint,
        categoria character varying(30) NOT NULL,
        titulo character varying(120) NOT NULL,
        conteudo_html text NOT NULL,
        ativo boolean NOT NULL,
        versao_atual integer NOT NULL,
        padrao_clonado_de bigint,
        deletado_em timestamp with time zone,
        criado_em timestamp with time zone NOT NULL,
        criado_por_usuario_id uuid,
        atualizado_em timestamp with time zone,
        CONSTRAINT "PK_termo_modelo" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260520014048_CriarTermosDeConsentimento') THEN
    CREATE TABLE public.termo_modelo_versao (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        termo_modelo_id bigint NOT NULL,
        versao integer NOT NULL,
        conteudo_html text NOT NULL,
        criado_em timestamp with time zone NOT NULL,
        criado_por_usuario_id uuid,
        CONSTRAINT "PK_termo_modelo_versao" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260520014048_CriarTermosDeConsentimento') THEN
    CREATE INDEX ix_termo_audit_log_entidade_criado ON public.termo_audit_log (entidade, entidade_id, criado_em DESC);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260520014048_CriarTermosDeConsentimento') THEN
    CREATE INDEX ix_termo_audit_log_estab_criado ON public.termo_audit_log (estabelecimento_id, criado_em DESC);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260520014048_CriarTermosDeConsentimento') THEN
    CREATE INDEX ix_termo_emitido_estab_status ON public.termo_emitido (estabelecimento_id, status);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260520014048_CriarTermosDeConsentimento') THEN
    CREATE INDEX ix_termo_emitido_paciente_estab_criado ON public.termo_emitido (paciente_id, estabelecimento_id, criado_em DESC);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260520014048_CriarTermosDeConsentimento') THEN
    CREATE UNIQUE INDEX uq_termo_emitido_token ON public.termo_emitido (token_aceite) WHERE token_aceite IS NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260520014048_CriarTermosDeConsentimento') THEN
    CREATE INDEX ix_termo_emitido_acesso_log_termo_criado ON public.termo_emitido_acesso_log (termo_emitido_id, criado_em DESC);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260520014048_CriarTermosDeConsentimento') THEN
    CREATE INDEX ix_termo_modelo_estab_cat_ativo ON public.termo_modelo (estabelecimento_id, categoria, ativo);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260520014048_CriarTermosDeConsentimento') THEN
    CREATE INDEX ix_termo_modelo_estab_deletado ON public.termo_modelo (estabelecimento_id, deletado_em);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260520014048_CriarTermosDeConsentimento') THEN
    CREATE INDEX ix_termo_modelo_padrao_categoria ON public.termo_modelo (categoria) WHERE estabelecimento_id IS NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260520014048_CriarTermosDeConsentimento') THEN
    CREATE UNIQUE INDEX uq_termo_modelo_versao ON public.termo_modelo_versao (termo_modelo_id, versao);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260520014048_CriarTermosDeConsentimento') THEN
    INSERT INTO public.__ef_migrations_history ("MigrationId", "ProductVersion")
    VALUES ('20260520014048_CriarTermosDeConsentimento', '10.0.0');
    END IF;
END $EF$;

