
DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260516125710_CriarCadastrosEstoque') THEN
    CREATE TABLE public.categorias_estoque (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        estabelecimento_id bigint NOT NULL,
        nome character varying(80) NOT NULL,
        cor character varying(40) NOT NULL,
        icone character varying(40) NOT NULL,
        ativo boolean NOT NULL,
        criado_em timestamp with time zone NOT NULL,
        atualizado_em timestamp with time zone,
        CONSTRAINT "PK_categorias_estoque" PRIMARY KEY (id),
        CONSTRAINT fk_categorias_estoque_estabelecimento FOREIGN KEY (estabelecimento_id) REFERENCES public.estabelecimentos (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260516125710_CriarCadastrosEstoque') THEN
    CREATE TABLE public.fabricantes_estoque (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        estabelecimento_id bigint NOT NULL,
        nome character varying(150) NOT NULL,
        pais character varying(60),
        ativo boolean NOT NULL,
        criado_em timestamp with time zone NOT NULL,
        atualizado_em timestamp with time zone,
        CONSTRAINT "PK_fabricantes_estoque" PRIMARY KEY (id),
        CONSTRAINT fk_fabricantes_estoque_estabelecimento FOREIGN KEY (estabelecimento_id) REFERENCES public.estabelecimentos (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260516125710_CriarCadastrosEstoque') THEN
    CREATE TABLE public.fornecedores_estoque (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        estabelecimento_id bigint NOT NULL,
        razao_social character varying(200) NOT NULL,
        nome_fantasia character varying(150),
        cnpj character varying(14),
        contato_nome character varying(150),
        contato_telefone character varying(40),
        contato_email character varying(200),
        prazo_entrega_dias integer NOT NULL,
        ativo boolean NOT NULL,
        criado_em timestamp with time zone NOT NULL,
        atualizado_em timestamp with time zone,
        CONSTRAINT "PK_fornecedores_estoque" PRIMARY KEY (id),
        CONSTRAINT fk_fornecedores_estoque_estabelecimento FOREIGN KEY (estabelecimento_id) REFERENCES public.estabelecimentos (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260516125710_CriarCadastrosEstoque') THEN
    CREATE TABLE public.locais_estoque (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        estabelecimento_id bigint NOT NULL,
        nome character varying(120) NOT NULL,
        tipo character varying(20) NOT NULL,
        andar_setor character varying(80),
        responsavel character varying(150),
        ativo boolean NOT NULL,
        criado_em timestamp with time zone NOT NULL,
        atualizado_em timestamp with time zone,
        CONSTRAINT "PK_locais_estoque" PRIMARY KEY (id),
        CONSTRAINT fk_locais_estoque_estabelecimento FOREIGN KEY (estabelecimento_id) REFERENCES public.estabelecimentos (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260516125710_CriarCadastrosEstoque') THEN
    ALTER TABLE public.itens_inventario ADD categoria_id bigint;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260516125710_CriarCadastrosEstoque') THEN
    ALTER TABLE public.itens_inventario ADD fabricante_id bigint;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260516125710_CriarCadastrosEstoque') THEN
    ALTER TABLE public.itens_inventario ADD fornecedor_padrao_id bigint;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260516125710_CriarCadastrosEstoque') THEN
    ALTER TABLE public.itens_inventario ADD local_padrao_id bigint;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260516125710_CriarCadastrosEstoque') THEN
    ALTER TABLE public.itens_inventario ADD custo_unitario numeric(12,2);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260516125710_CriarCadastrosEstoque') THEN

                    UPDATE public.itens_inventario
                       SET categoria = 'Sem categoria'
                     WHERE COALESCE(NULLIF(trim(categoria), ''), '') = '';

                    INSERT INTO public.categorias_estoque (estabelecimento_id, nome, cor, icone, ativo, criado_em)
                    SELECT DISTINCT i.estabelecimento_id, i.categoria, 'hsl(218 70% 50%)', 'fa-tag', true, now()
                      FROM public.itens_inventario i
                     WHERE NOT EXISTS (
                            SELECT 1 FROM public.categorias_estoque c
                             WHERE c.estabelecimento_id = i.estabelecimento_id
                               AND lower(c.nome) = lower(i.categoria)
                           );

                    UPDATE public.itens_inventario i
                       SET categoria_id = c.id
                      FROM public.categorias_estoque c
                     WHERE c.estabelecimento_id = i.estabelecimento_id
                       AND lower(c.nome) = lower(i.categoria)
                       AND i.categoria_id IS NULL;
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260516125710_CriarCadastrosEstoque') THEN

                    DO $$
                    BEGIN
                        IF EXISTS (SELECT 1 FROM public.itens_inventario WHERE categoria_id IS NULL) THEN
                            RAISE EXCEPTION 'Migration falhou: existem itens_inventario com categoria_id NULL após data migration.';
                        END IF;
                    END $$;
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260516125710_CriarCadastrosEstoque') THEN
    ALTER TABLE public.itens_inventario ALTER COLUMN categoria_id SET NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260516125710_CriarCadastrosEstoque') THEN
    CREATE INDEX ix_inventario_estab_categoria ON public.itens_inventario (estabelecimento_id, categoria_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260516125710_CriarCadastrosEstoque') THEN
    CREATE INDEX "IX_itens_inventario_categoria_id" ON public.itens_inventario (categoria_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260516125710_CriarCadastrosEstoque') THEN
    CREATE INDEX "IX_itens_inventario_fabricante_id" ON public.itens_inventario (fabricante_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260516125710_CriarCadastrosEstoque') THEN
    CREATE INDEX "IX_itens_inventario_fornecedor_padrao_id" ON public.itens_inventario (fornecedor_padrao_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260516125710_CriarCadastrosEstoque') THEN
    CREATE INDEX "IX_itens_inventario_local_padrao_id" ON public.itens_inventario (local_padrao_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260516125710_CriarCadastrosEstoque') THEN
    CREATE INDEX ix_categorias_estoque_estab_ativo ON public.categorias_estoque (estabelecimento_id, ativo);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260516125710_CriarCadastrosEstoque') THEN
    CREATE INDEX ix_fabricantes_estoque_estab_ativo ON public.fabricantes_estoque (estabelecimento_id, ativo);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260516125710_CriarCadastrosEstoque') THEN
    CREATE INDEX ix_fornecedores_estoque_estab_ativo ON public.fornecedores_estoque (estabelecimento_id, ativo);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260516125710_CriarCadastrosEstoque') THEN
    CREATE INDEX ix_locais_estoque_estab_ativo ON public.locais_estoque (estabelecimento_id, ativo);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260516125710_CriarCadastrosEstoque') THEN

                    CREATE UNIQUE INDEX IF NOT EXISTS uq_categorias_estoque_estab_nome    ON public.categorias_estoque   (estabelecimento_id, lower(nome));
                    CREATE UNIQUE INDEX IF NOT EXISTS uq_fabricantes_estoque_estab_nome   ON public.fabricantes_estoque  (estabelecimento_id, lower(nome));
                    CREATE UNIQUE INDEX IF NOT EXISTS uq_fornecedores_estoque_estab_razao ON public.fornecedores_estoque (estabelecimento_id, lower(razao_social));
                    CREATE UNIQUE INDEX IF NOT EXISTS uq_locais_estoque_estab_nome        ON public.locais_estoque       (estabelecimento_id, lower(nome));
                    CREATE UNIQUE INDEX IF NOT EXISTS uq_fornecedores_estoque_estab_cnpj  ON public.fornecedores_estoque (estabelecimento_id, cnpj) WHERE cnpj IS NOT NULL;
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260516125710_CriarCadastrosEstoque') THEN
    ALTER TABLE public.itens_inventario ADD CONSTRAINT fk_inventario_categoria FOREIGN KEY (categoria_id) REFERENCES public.categorias_estoque (id) ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260516125710_CriarCadastrosEstoque') THEN
    ALTER TABLE public.itens_inventario ADD CONSTRAINT fk_inventario_fabricante FOREIGN KEY (fabricante_id) REFERENCES public.fabricantes_estoque (id) ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260516125710_CriarCadastrosEstoque') THEN
    ALTER TABLE public.itens_inventario ADD CONSTRAINT fk_inventario_fornecedor_padrao FOREIGN KEY (fornecedor_padrao_id) REFERENCES public.fornecedores_estoque (id) ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260516125710_CriarCadastrosEstoque') THEN
    ALTER TABLE public.itens_inventario ADD CONSTRAINT fk_inventario_local_padrao FOREIGN KEY (local_padrao_id) REFERENCES public.locais_estoque (id) ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260516125710_CriarCadastrosEstoque') THEN
    INSERT INTO public.__ef_migrations_history ("MigrationId", "ProductVersion")
    VALUES ('20260516125710_CriarCadastrosEstoque', '10.0.0');
    END IF;
END $EF$;

