DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260518182322_CriarAtestadosEPedidosExame') THEN
    CREATE TABLE public.atestados (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        estabelecimento_id bigint NOT NULL,
        paciente_id bigint NOT NULL,
        profissional_usuario_id uuid NOT NULL,
        tipo character varying(20) NOT NULL,
        dias_afastamento integer,
        cid10 character varying(8),
        conteudo text NOT NULL,
        criado_em timestamp with time zone NOT NULL,
        deletado_em timestamp with time zone,
        deletado_por_usuario_id uuid,
        CONSTRAINT "PK_atestados" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260518182322_CriarAtestadosEPedidosExame') THEN
    CREATE TABLE public.modelos_atestado (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        estabelecimento_id bigint NOT NULL,
        profissional_usuario_id uuid NOT NULL,
        nome character varying(120) NOT NULL,
        tipo character varying(20) NOT NULL,
        conteudo text NOT NULL,
        criado_em timestamp with time zone NOT NULL,
        atualizado_em timestamp with time zone,
        CONSTRAINT "PK_modelos_atestado" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260518182322_CriarAtestadosEPedidosExame') THEN
    CREATE TABLE public.pedidos_exame (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        estabelecimento_id bigint NOT NULL,
        paciente_id bigint NOT NULL,
        profissional_usuario_id uuid NOT NULL,
        tipo character varying(20) NOT NULL,
        exames jsonb,
        indicacao_clinica text NOT NULL,
        cid10 character varying(8),
        observacoes text,
        criado_em timestamp with time zone NOT NULL,
        deletado_em timestamp with time zone,
        deletado_por_usuario_id uuid,
        CONSTRAINT "PK_pedidos_exame" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260518182322_CriarAtestadosEPedidosExame') THEN
    CREATE INDEX ix_atestados_estab_criado ON public.atestados (estabelecimento_id, criado_em DESC);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260518182322_CriarAtestadosEPedidosExame') THEN
    CREATE INDEX ix_atestados_paciente_criado ON public.atestados (paciente_id, criado_em DESC);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260518182322_CriarAtestadosEPedidosExame') THEN
    CREATE INDEX ix_modelos_atestado_estab_nome ON public.modelos_atestado (estabelecimento_id, nome);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260518182322_CriarAtestadosEPedidosExame') THEN
    CREATE INDEX ix_pedidos_exame_estab_criado ON public.pedidos_exame (estabelecimento_id, criado_em DESC);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260518182322_CriarAtestadosEPedidosExame') THEN
    CREATE INDEX ix_pedidos_exame_paciente_criado ON public.pedidos_exame (paciente_id, criado_em DESC);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260518182322_CriarAtestadosEPedidosExame') THEN
    INSERT INTO public.__ef_migrations_history ("MigrationId", "ProductVersion")
    VALUES ('20260518182322_CriarAtestadosEPedidosExame', '10.0.0');
    END IF;
END $EF$;
