DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260610235639_CriarPendenciasAtendimentoF3B') THEN
    CREATE TABLE public.pendencias_atendimento (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        estabelecimento_id bigint NOT NULL,
        paciente_id bigint NOT NULL,
        evolucao_id bigint NOT NULL,
        agendamento_id bigint,
        acao character varying(40) NOT NULL,
        status character varying(20) NOT NULL,
        referencia_id bigint,
        concluida_em timestamp with time zone,
        criado_por_usuario_id uuid NOT NULL,
        criado_em timestamp with time zone NOT NULL,
        atualizado_em timestamp with time zone,
        CONSTRAINT "PK_pendencias_atendimento" PRIMARY KEY (id),
        CONSTRAINT fk_pendencias_estabelecimento FOREIGN KEY (estabelecimento_id) REFERENCES public.estabelecimentos (id) ON DELETE RESTRICT,
        CONSTRAINT fk_pendencias_evolucao FOREIGN KEY (evolucao_id) REFERENCES public.prontuario_evolucoes (id) ON DELETE RESTRICT,
        CONSTRAINT fk_pendencias_paciente FOREIGN KEY (paciente_id) REFERENCES public.pacientes (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260610235639_CriarPendenciasAtendimentoF3B') THEN
    CREATE INDEX "IX_pendencias_atendimento_paciente_id" ON public.pendencias_atendimento (paciente_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260610235639_CriarPendenciasAtendimentoF3B') THEN
    CREATE INDEX ix_pendencias_estab_paciente_status ON public.pendencias_atendimento (estabelecimento_id, paciente_id, status);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260610235639_CriarPendenciasAtendimentoF3B') THEN
    CREATE UNIQUE INDEX uq_pendencias_evolucao_acao ON public.pendencias_atendimento (evolucao_id, acao);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260610235639_CriarPendenciasAtendimentoF3B') THEN
    INSERT INTO public.__ef_migrations_history ("MigrationId", "ProductVersion")
    VALUES ('20260610235639_CriarPendenciasAtendimentoF3B', '10.0.0');
    END IF;
END $EF$;
