
DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260518103100_AdicionarSalaEmAgendamento') THEN
    ALTER TABLE public.agendamentos ADD sala_id bigint;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260518103100_AdicionarSalaEmAgendamento') THEN
    CREATE TABLE public.agendamento_sala_audit (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        agendamento_id bigint NOT NULL,
        estabelecimento_id bigint NOT NULL,
        sala_id_anterior bigint,
        sala_id_nova bigint,
        usuario_id uuid NOT NULL,
        em timestamp with time zone NOT NULL,
        CONSTRAINT "PK_agendamento_sala_audit" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260518103100_AdicionarSalaEmAgendamento') THEN
    CREATE INDEX ix_agendamentos_sala ON public.agendamentos (sala_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260518103100_AdicionarSalaEmAgendamento') THEN
    CREATE INDEX ix_agendamento_sala_audit_agendamento ON public.agendamento_sala_audit (agendamento_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260518103100_AdicionarSalaEmAgendamento') THEN
    CREATE INDEX ix_agendamento_sala_audit_estab ON public.agendamento_sala_audit (estabelecimento_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260518103100_AdicionarSalaEmAgendamento') THEN
    ALTER TABLE public.agendamentos ADD CONSTRAINT fk_agendamento_sala FOREIGN KEY (sala_id) REFERENCES public.sala_atendimento (id) ON DELETE SET NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260518103100_AdicionarSalaEmAgendamento') THEN
    INSERT INTO public.__ef_migrations_history ("MigrationId", "ProductVersion")
    VALUES ('20260518103100_AdicionarSalaEmAgendamento', '10.0.0');
    END IF;
END $EF$;

