DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260603124913_CriarLinkPublicoConfirmacaoAgendamento') THEN
    ALTER TABLE public.agendamentos ADD confirmado_por_link_em timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260603124913_CriarLinkPublicoConfirmacaoAgendamento') THEN
    ALTER TABLE public.agendamentos ADD token_confirmacao text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260603124913_CriarLinkPublicoConfirmacaoAgendamento') THEN
    ALTER TABLE public.agendamentos ADD token_confirmacao_expira_em timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260603124913_CriarLinkPublicoConfirmacaoAgendamento') THEN
    CREATE TABLE public.agendamento_confirmacao_acesso_log (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        agendamento_id bigint NOT NULL,
        estabelecimento_id bigint NOT NULL,
        ip_origem character varying(45),
        user_agent character varying(500),
        acao character varying(30) NOT NULL,
        acessado_em timestamp with time zone NOT NULL,
        CONSTRAINT "PK_agendamento_confirmacao_acesso_log" PRIMARY KEY (id),
        CONSTRAINT fk_agendamento_confirmacao_acesso_log_agendamento FOREIGN KEY (agendamento_id) REFERENCES public.agendamentos (id) ON DELETE CASCADE,
        CONSTRAINT fk_agendamento_confirmacao_acesso_log_estabelecimento FOREIGN KEY (estabelecimento_id) REFERENCES public.estabelecimentos (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260603124913_CriarLinkPublicoConfirmacaoAgendamento') THEN
    CREATE UNIQUE INDEX uq_agendamentos_token_confirmacao ON public.agendamentos (token_confirmacao) WHERE token_confirmacao IS NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260603124913_CriarLinkPublicoConfirmacaoAgendamento') THEN
    CREATE INDEX ix_agendamento_confirmacao_acesso_log_agendamento_acessado ON public.agendamento_confirmacao_acesso_log (agendamento_id, acessado_em DESC);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260603124913_CriarLinkPublicoConfirmacaoAgendamento') THEN
    CREATE INDEX ix_agendamento_confirmacao_acesso_log_estabelecimento ON public.agendamento_confirmacao_acesso_log (estabelecimento_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260603124913_CriarLinkPublicoConfirmacaoAgendamento') THEN
    INSERT INTO public.__ef_migrations_history ("MigrationId", "ProductVersion")
    VALUES ('20260603124913_CriarLinkPublicoConfirmacaoAgendamento', '10.0.0');
    END IF;
END $EF$;
