-- Migration: 20260611034119_criar_convenios_paciente_convenio_guia_f6
-- Briefing: 2026-06-10_016 — Financeiro F6: Convênio estrutura base
-- Escopo: tabelas convenios, convenio_planos, paciente_convenios +
--         ALTER cobrancas (guia_numero, guia_senha, guia_autorizada_em) +
--         FK fk_cobrancas_convenio (ON DELETE SET NULL) +
--         7 índices (todos snake_case).
-- LGPD: numero_carteirinha em paciente_convenios é dado pessoal — DTO minimizado, sem PII em log.
-- NÃO contém BEGIN/COMMIT — a pipeline (migrate.sh) gerencia a transação.

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260611034119_CriarConveniosPacienteConvenioGuiaF6') THEN
    ALTER TABLE public.cobrancas ADD guia_autorizada_em date;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260611034119_CriarConveniosPacienteConvenioGuiaF6') THEN
    ALTER TABLE public.cobrancas ADD guia_numero character varying(100);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260611034119_CriarConveniosPacienteConvenioGuiaF6') THEN
    ALTER TABLE public.cobrancas ADD guia_senha character varying(100);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260611034119_CriarConveniosPacienteConvenioGuiaF6') THEN
    CREATE TABLE public.convenios (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        estabelecimento_id bigint NOT NULL,
        nome text NOT NULL,
        registro_ans text,
        ativo boolean NOT NULL DEFAULT TRUE,
        criado_em timestamp with time zone NOT NULL,
        atualizado_em timestamp with time zone,
        CONSTRAINT "PK_convenios" PRIMARY KEY (id),
        CONSTRAINT fk_convenios_estabelecimento FOREIGN KEY (estabelecimento_id) REFERENCES public.estabelecimentos (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260611034119_CriarConveniosPacienteConvenioGuiaF6') THEN
    CREATE TABLE public.convenio_planos (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        convenio_id bigint NOT NULL,
        estabelecimento_id bigint NOT NULL,
        nome text NOT NULL,
        ativo boolean NOT NULL DEFAULT TRUE,
        criado_em timestamp with time zone NOT NULL,
        CONSTRAINT "PK_convenio_planos" PRIMARY KEY (id),
        CONSTRAINT fk_convenio_planos_convenio FOREIGN KEY (convenio_id) REFERENCES public.convenios (id) ON DELETE CASCADE,
        CONSTRAINT fk_convenio_planos_estabelecimento FOREIGN KEY (estabelecimento_id) REFERENCES public.estabelecimentos (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260611034119_CriarConveniosPacienteConvenioGuiaF6') THEN
    CREATE TABLE public.paciente_convenios (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        paciente_id bigint NOT NULL,
        estabelecimento_id bigint NOT NULL,
        convenio_id bigint NOT NULL,
        plano_id bigint,
        numero_carteirinha text NOT NULL,
        validade date,
        ativo boolean NOT NULL DEFAULT TRUE,
        criado_em timestamp with time zone NOT NULL,
        atualizado_em timestamp with time zone,
        CONSTRAINT "PK_paciente_convenios" PRIMARY KEY (id),
        CONSTRAINT fk_paciente_convenios_convenio FOREIGN KEY (convenio_id) REFERENCES public.convenios (id) ON DELETE RESTRICT,
        CONSTRAINT fk_paciente_convenios_estabelecimento FOREIGN KEY (estabelecimento_id) REFERENCES public.estabelecimentos (id) ON DELETE RESTRICT,
        CONSTRAINT fk_paciente_convenios_paciente FOREIGN KEY (paciente_id) REFERENCES public.pacientes (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260611034119_CriarConveniosPacienteConvenioGuiaF6') THEN
    CREATE INDEX ix_cobrancas_convenio_id ON public.cobrancas (convenio_id) WHERE convenio_id IS NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260611034119_CriarConveniosPacienteConvenioGuiaF6') THEN
    CREATE INDEX ix_convenio_planos_convenio_ativo ON public.convenio_planos (convenio_id, ativo);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260611034119_CriarConveniosPacienteConvenioGuiaF6') THEN
    CREATE INDEX ix_convenio_planos_estabelecimento_id ON public.convenio_planos (estabelecimento_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260611034119_CriarConveniosPacienteConvenioGuiaF6') THEN
    CREATE INDEX ix_convenios_estab_ativo ON public.convenios (estabelecimento_id, ativo);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260611034119_CriarConveniosPacienteConvenioGuiaF6') THEN
    CREATE INDEX ix_paciente_convenios_convenio_id ON public.paciente_convenios (convenio_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260611034119_CriarConveniosPacienteConvenioGuiaF6') THEN
    CREATE INDEX ix_paciente_convenios_estabelecimento_id ON public.paciente_convenios (estabelecimento_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260611034119_CriarConveniosPacienteConvenioGuiaF6') THEN
    CREATE INDEX ix_paciente_convenios_paciente_estab_ativo ON public.paciente_convenios (paciente_id, estabelecimento_id, ativo);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260611034119_CriarConveniosPacienteConvenioGuiaF6') THEN
    ALTER TABLE public.cobrancas ADD CONSTRAINT fk_cobrancas_convenio FOREIGN KEY (convenio_id) REFERENCES public.convenios (id) ON DELETE SET NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260611034119_CriarConveniosPacienteConvenioGuiaF6') THEN
    INSERT INTO public.__ef_migrations_history ("MigrationId", "ProductVersion")
    VALUES ('20260611034119_CriarConveniosPacienteConvenioGuiaF6', '10.0.0');
    END IF;
END $EF$;
