-- Migration: 20260610211901_CriarEstornoPagamentosF2
-- Módulo Financeiro/Cobranças — F2: Estorno de pagamento (briefing 2026-06-10_010)
-- Tabela nova: estorno_pagamentos
-- Sem ALTER em lancamentos (DC2: valor negativo + categoria — sem coluna/flag nova)
-- Sem CHECK constraint em lancamentos.valor (confirmado por análise estática — não há)
-- Idempotente via guards __EFMigrationsHistory (BEGIN/COMMIT removidos — pipeline gerencia a transação)

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260610211901_CriarEstornoPagamentosF2') THEN
    CREATE TABLE public.estorno_pagamentos (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        pagamento_id bigint NOT NULL,
        cobranca_id bigint NOT NULL,
        estabelecimento_id bigint NOT NULL,
        valor numeric(12,2) NOT NULL,
        motivo text NOT NULL,
        lancamento_estorno_id bigint,
        estornado_por_usuario_id uuid NOT NULL,
        data_estorno date NOT NULL,
        criado_em timestamp with time zone NOT NULL,
        CONSTRAINT "PK_estorno_pagamentos" PRIMARY KEY (id),
        CONSTRAINT fk_estorno_pagamentos_cobranca FOREIGN KEY (cobranca_id) REFERENCES public.cobrancas (id) ON DELETE RESTRICT,
        CONSTRAINT fk_estorno_pagamentos_pagamento FOREIGN KEY (pagamento_id) REFERENCES public.pagamentos (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260610211901_CriarEstornoPagamentosF2') THEN
    CREATE INDEX ix_estorno_pagamentos_cobranca_id ON public.estorno_pagamentos (cobranca_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260610211901_CriarEstornoPagamentosF2') THEN
    CREATE INDEX ix_estorno_pagamentos_estab_cobranca ON public.estorno_pagamentos (estabelecimento_id, cobranca_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260610211901_CriarEstornoPagamentosF2') THEN
    CREATE UNIQUE INDEX uq_estorno_pagamentos_pagamento_id ON public.estorno_pagamentos (pagamento_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260610211901_CriarEstornoPagamentosF2') THEN
    INSERT INTO public.__ef_migrations_history ("MigrationId", "ProductVersion")
    VALUES ('20260610211901_CriarEstornoPagamentosF2', '10.0.0');
    END IF;
END $EF$;
