-- Migration: criar_tabelas_migracao
-- Briefing: 2026-06-15_001 — Central de Migração (Marco 1)
-- Tabelas: migracao_templates (cross-tenant), migracao_jobs, migracao_mapas, migracao_registros
-- Multi-tenant: migracao_jobs, migracao_mapas, migracao_registros têm estabelecimento_id NOT NULL + FK + índice.
-- migracao_templates é global (justificativa: metadado de schema compartilhado entre todos os tenants).
-- Pipeline: psql aplica via deploy/scripts/migrate.sh — sem BEGIN/COMMIT aqui.

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260615152934_CriarTabelasMigracao') THEN
    CREATE TABLE public.migracao_templates (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        nome varchar(200) NOT NULL,
        entidade varchar(100) NOT NULL,
        mapa_json jsonb NOT NULL,
        criado_por_usuario_id uuid NOT NULL,
        criado_em timestamp with time zone NOT NULL,
        atualizado_em timestamp with time zone NOT NULL,
        CONSTRAINT "PK_migracao_templates" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260615152934_CriarTabelasMigracao') THEN
    CREATE TABLE public.migracao_jobs (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        estabelecimento_id bigint NOT NULL,
        status varchar(50) NOT NULL,
        origem varchar(200),
        arquivo_s3_key varchar(500),
        arquivo_expira_em timestamp with time zone,
        arquivo_expirado boolean NOT NULL DEFAULT FALSE,
        termo_aceito_em timestamp with time zone,
        template_origem_id bigint,
        criado_por_usuario_id uuid NOT NULL,
        disparado_por_usuario_id uuid,
        criado_em timestamp with time zone NOT NULL,
        atualizado_em timestamp with time zone NOT NULL,
        CONSTRAINT "PK_migracao_jobs" PRIMARY KEY (id),
        CONSTRAINT fk_migracao_jobs_estabelecimento FOREIGN KEY (estabelecimento_id) REFERENCES public.estabelecimentos (id) ON DELETE RESTRICT,
        CONSTRAINT fk_migracao_jobs_template_origem FOREIGN KEY (template_origem_id) REFERENCES public.migracao_templates (id) ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260615152934_CriarTabelasMigracao') THEN
    CREATE TABLE public.migracao_mapas (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        migracao_job_id bigint NOT NULL,
        estabelecimento_id bigint NOT NULL,
        entidade varchar(100) NOT NULL,
        mapa_json jsonb NOT NULL,
        revisado_por_usuario_id uuid,
        revisado_em timestamp with time zone,
        criado_em timestamp with time zone NOT NULL,
        atualizado_em timestamp with time zone NOT NULL,
        CONSTRAINT "PK_migracao_mapas" PRIMARY KEY (id),
        CONSTRAINT fk_migracao_mapas_job FOREIGN KEY (migracao_job_id) REFERENCES public.migracao_jobs (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260615152934_CriarTabelasMigracao') THEN
    CREATE TABLE public.migracao_registros (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        migracao_job_id bigint NOT NULL,
        estabelecimento_id bigint NOT NULL,
        entidade varchar(100) NOT NULL,
        payload_bruto jsonb NOT NULL,
        status varchar(50) NOT NULL DEFAULT 'pendente',
        motivo_rejeicao text,
        entidade_alvo_id bigint,
        criado_em timestamp with time zone NOT NULL,
        CONSTRAINT "PK_migracao_registros" PRIMARY KEY (id),
        CONSTRAINT fk_migracao_registros_job FOREIGN KEY (migracao_job_id) REFERENCES public.migracao_jobs (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260615152934_CriarTabelasMigracao') THEN
    CREATE INDEX ix_migracao_jobs_arquivo_expira_em ON public.migracao_jobs (arquivo_expira_em);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260615152934_CriarTabelasMigracao') THEN
    CREATE INDEX ix_migracao_jobs_criado_por_usuario_id ON public.migracao_jobs (criado_por_usuario_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260615152934_CriarTabelasMigracao') THEN
    CREATE INDEX ix_migracao_jobs_estab_status ON public.migracao_jobs (estabelecimento_id, status);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260615152934_CriarTabelasMigracao') THEN
    -- FK coverage para template_origem_id (gerado pelo EF automaticamente).
    CREATE INDEX ix_migracao_jobs_template_origem_id ON public.migracao_jobs (template_origem_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260615152934_CriarTabelasMigracao') THEN
    CREATE UNIQUE INDEX uq_migracao_mapas_job_entidade ON public.migracao_mapas (migracao_job_id, entidade);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260615152934_CriarTabelasMigracao') THEN
    CREATE INDEX ix_migracao_registros_estab_entidade ON public.migracao_registros (estabelecimento_id, entidade);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260615152934_CriarTabelasMigracao') THEN
    CREATE INDEX ix_migracao_registros_job_id ON public.migracao_registros (migracao_job_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260615152934_CriarTabelasMigracao') THEN
    CREATE INDEX ix_migracao_registros_job_status ON public.migracao_registros (migracao_job_id, status);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260615152934_CriarTabelasMigracao') THEN
    CREATE UNIQUE INDEX uq_migracao_templates_nome_entidade ON public.migracao_templates (nome, entidade);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260615152934_CriarTabelasMigracao') THEN
    INSERT INTO public.__ef_migrations_history ("MigrationId", "ProductVersion")
    VALUES ('20260615152934_CriarTabelasMigracao', '10.0.0');
    END IF;
END $EF$;
