-- Migration F5 — cobrança de cirurgia: tabela cobranca_historico_valor + índice UNIQUE parcial.
-- Gerado via: dotnet ef migrations script ... --idempotent
-- BEGIN/COMMIT removidos — pipeline (migrate.sh) gerencia a transação.

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260611015422_CobrancaHistoricoValorF5Cirurgia') THEN
    CREATE TABLE public.cobranca_historico_valor (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        cobranca_id bigint NOT NULL,
        estabelecimento_id bigint NOT NULL,
        valor_anterior numeric(14,2) NOT NULL,
        valor_novo numeric(14,2) NOT NULL,
        alterado_por_usuario_id uuid NOT NULL,
        alterado_em timestamp with time zone NOT NULL,
        CONSTRAINT "PK_cobranca_historico_valor" PRIMARY KEY (id),
        CONSTRAINT fk_cobranca_historico_valor_cobranca FOREIGN KEY (cobranca_id) REFERENCES public.cobrancas (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260611015422_CobrancaHistoricoValorF5Cirurgia') THEN
    CREATE UNIQUE INDEX ux_cobrancas_orcamento_cirurgia ON public.cobrancas (orcamento_id) WHERE origem = 'Cirurgia' AND orcamento_id IS NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260611015422_CobrancaHistoricoValorF5Cirurgia') THEN
    CREATE INDEX ix_cobranca_historico_valor_cobranca_id ON public.cobranca_historico_valor (cobranca_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260611015422_CobrancaHistoricoValorF5Cirurgia') THEN
    INSERT INTO public.__ef_migrations_history ("MigrationId", "ProductVersion")
    VALUES ('20260611015422_CobrancaHistoricoValorF5Cirurgia', '10.0.0');
    END IF;
END $EF$;
