namespace Imedto.Backend.Application.Catalogo;

/// <summary>
/// Dados de seed do catálogo de regiões anatômicas globais.
///
/// Portado do legado SQL (supabase/migrations/20260226100000_create_exame_fisico_tables.sql).
/// Esta estrutura é consumida pelo database-architect na Etapa B para gerar
/// os INSERTs SQL em supabase/migrations/.
///
/// Campos: Codigo (slug único), Nome, PaiCodigo (hierarquia), Nivel (0-3),
/// Vista ("anterior"|"posterior"), TemplateTexto, SvgCoordsJson (null — preenchido via
/// frontend BodyMapSvg), Ordem (dentro do grupo pai), Lateralidade (região tem versão E/D).
/// </summary>
public static class SeedsRegioesAnatomicas
{
    public record RegiaoCatalogoSeed(
        string Codigo,
        string Nome,
        string? PaiCodigo,
        short Nivel,
        string? Vista,
        string? TemplateTexto,
        short Ordem,
        bool Lateralidade);

    public static readonly IReadOnlyList<RegiaoCatalogoSeed> Regioes = new List<RegiaoCatalogoSeed>
    {
        // === NÍVEL 1 — Vista ANTERIOR ===
        new("cabeca-anterior", "Cabeça (anterior)", null, 1, "anterior",
            "Crânio normocefálico, sem deformidades. Couro cabeludo sem lesões visíveis.", 1, false),
        new("pescoco-anterior", "Pescoço (anterior)", null, 1, "anterior",
            "Pescoço cilíndrico, sem massas palpáveis. Tireoide sem alterações à palpação.", 2, false),
        new("torax-anterior", "Tórax (anterior)", null, 1, "anterior",
            "Tórax simétrico, expansibilidade preservada. Murmúrio vesicular fisiológico bilateral.", 3, false),
        new("abdome-anterior", "Abdome (anterior)", null, 1, "anterior",
            "Abdome plano, flácido, indolor à palpação superficial e profunda. Ruídos hidroaéreos presentes.", 4, false),
        new("pelve-anterior", "Pelve (anterior)", null, 1, "anterior",
            "Região pélvica sem alterações à inspeção. Sem sinais de irritação peritoneal.", 5, false),
        new("msd-anterior", "Membro superior direito (anterior)", null, 1, "anterior",
            "Sem edema, sem deformidades. Pulsos radial e ulnar palpáveis e simétricos. Força muscular preservada.", 6, false),
        new("mse-anterior", "Membro superior esquerdo (anterior)", null, 1, "anterior",
            "Sem edema, sem deformidades. Pulsos radial e ulnar palpáveis e simétricos. Força muscular preservada.", 7, false),
        new("mid-anterior", "Membro inferior direito (anterior)", null, 1, "anterior",
            "Sem edema, sem varizes. Pulsos pedioso e tibial posterior palpáveis. Força muscular preservada.", 8, false),
        new("mie-anterior", "Membro inferior esquerdo (anterior)", null, 1, "anterior",
            "Sem edema, sem varizes. Pulsos pedioso e tibial posterior palpáveis. Força muscular preservada.", 9, false),

        // === NÍVEL 1 — Vista POSTERIOR ===
        new("cabeca-posterior", "Cabeça (posterior)", null, 1, "posterior",
            "Região occipital sem massas ou deformidades. Couro cabeludo sem lesões.", 10, false),
        new("pescoco-posterior", "Pescoço (posterior)", null, 1, "posterior",
            "Nuca livre. Sem rigidez de nuca. Musculatura cervical posterior sem contraturas.", 11, false),
        new("torax-posterior", "Tórax (posterior)", null, 1, "posterior",
            "Dorso simétrico. Coluna torácica sem desvios. Murmúrio vesicular fisiológico bilateral.", 12, false),
        new("lombossacra-posterior", "Região lombossacra (posterior)", null, 1, "posterior",
            "Coluna lombar sem desvios. Sem dor à palpação de processos espinhosos. Lasègue negativo bilateral.", 13, false),
        new("pelve-posterior", "Pelve (posterior)", null, 1, "posterior",
            "Região glútea sem alterações. Sem sinais de fístulas ou lesões perianais.", 14, false),
        new("msd-posterior", "Membro superior direito (posterior)", null, 1, "posterior",
            "Face posterior sem lesões. Tríceps e musculatura posterior do antebraço com tônus preservado.", 15, false),
        new("mse-posterior", "Membro superior esquerdo (posterior)", null, 1, "posterior",
            "Face posterior sem lesões. Tríceps e musculatura posterior do antebraço com tônus preservado.", 16, false),
        new("mid-posterior", "Membro inferior direito (posterior)", null, 1, "posterior",
            "Face posterior sem lesões. Panturrilha sem empastamento. Sinal de Homans negativo.", 17, false),
        new("mie-posterior", "Membro inferior esquerdo (posterior)", null, 1, "posterior",
            "Face posterior sem lesões. Panturrilha sem empastamento. Sinal de Homans negativo.", 18, false),

        // === NÍVEL 2 — Filhos de Tórax Anterior ===
        new("pulmao", "Pulmão", "torax-anterior", 2, "anterior",
            "Murmúrio vesicular fisiológico, sem ruídos adventícios. Expansibilidade e frêmito preservados.", 1, true),
        new("coracao", "Coração", "torax-anterior", 2, "anterior",
            "Bulhas rítmicas, normofonéticas, em 2 tempos, sem sopros. Ictus cordis no 5° EIC esquerdo.", 2, false),
        new("mama", "Mama", "torax-anterior", 2, "anterior",
            "Mamas simétricas, sem retrações. Sem nódulos palpáveis. Sem descarga papilar.", 3, true),
        new("axila", "Axila", "torax-anterior", 2, "anterior",
            "Axilas sem linfonodomegalias palpáveis. Sem lesões cutâneas.", 5, true),
        new("parede-toracica", "Parede torácica", "torax-anterior", 2, "anterior",
            "Parede torácica sem lesões ou deformidades. Sem dor à palpação.", 4, false),

        // === NÍVEL 2 — Filhos de Abdome Anterior ===
        new("epigastrio", "Epigástrio", "abdome-anterior", 2, "anterior",
            "Epigástrio indolor à palpação. Sem massas palpáveis.", 1, false),
        new("mesogastrio", "Mesogástrio", "abdome-anterior", 2, "anterior",
            "Mesogástrio indolor. Sem visceromegalias.", 2, false),
        new("hipogastrio", "Hipogástrio", "abdome-anterior", 2, "anterior",
            "Hipogástrio indolor. Sem massas palpáveis. Bexiga não palpável.", 3, false),
        new("hipocondrio", "Hipocôndrio", "abdome-anterior", 2, "anterior",
            "Hipocôndrio indolor à palpação superficial e profunda.", 4, true),
        new("flanco", "Flanco", "abdome-anterior", 2, "anterior",
            "Flancos indolores. Sem sinais de irritação peritoneal.", 5, true),
        new("fossa-iliaca", "Fossa ilíaca", "abdome-anterior", 2, "anterior",
            "Fossa ilíaca indolor à palpação. Sem massas ou hérnias.", 6, true),
        new("figado", "Fígado", "abdome-anterior", 2, "anterior",
            "Fígado não palpável abaixo do rebordo costal. Espaço de Traube livre.", 7, false),
        new("baco", "Baço", "abdome-anterior", 2, "anterior",
            "Baço não palpável. Espaço de Traube livre.", 8, false),

        // === NÍVEL 2 — Filhos de Pelve Anterior ===
        new("regiao-inguinal", "Região inguinal", "pelve-anterior", 2, "anterior",
            "Região inguinal sem abaulamentos. Sem hérnias. Linfonodos inguinais não palpáveis.", 1, true),
        new("genitalia", "Genitália", "pelve-anterior", 2, "anterior",
            "Genitália externa sem alterações à inspeção.", 2, false),

        // === NÍVEL 2 — Filhos de Cabeça Anterior ===
        new("olho", "Olho", "cabeca-anterior", 2, "anterior",
            "Pupilas isocóricas e fotorreagentes. Conjuntivas normocoradas. Escleras anictéricas.", 1, true),
        new("orelha", "Orelha", "cabeca-anterior", 2, "anterior",
            "Pavilhão auricular sem alterações. Meato acústico externo pérvio.", 2, true),
        new("nariz", "Nariz", "cabeca-anterior", 2, "anterior",
            "Pirâmide nasal sem desvios. Mucosa nasal úmida e normocorada. Septo centrado.", 3, false),
        new("boca", "Boca", "cabeca-anterior", 2, "anterior",
            "Mucosa oral úmida e normocorada. Orofaringe sem hiperemia. Amígdalas sem hipertrofia.", 4, false),
        new("face", "Face", "cabeca-anterior", 2, "anterior",
            "Facies atípica. Sem assimetrias. Sem lesões cutâneas visíveis.", 5, false),
        new("fronte", "Fronte", "cabeca-anterior", 2, "anterior",
            "Fronte sem abaulamentos ou depressões. Pele íntegra.", 6, false),

        // === NÍVEL 2 — Filhos de Pescoço Anterior ===
        new("tireoide", "Tireoide", "pescoco-anterior", 2, "anterior",
            "Tireoide de tamanho normal à palpação, sem nódulos. Indolor.", 1, false),
        new("linfonodos-cervicais", "Linfonodos cervicais", "pescoco-anterior", 2, "anterior",
            "Linfonodos cervicais não palpáveis bilateralmente.", 2, true),
        new("carotidas", "Carótidas", "pescoco-anterior", 2, "anterior",
            "Pulsos carotídeos simétricos, sem sopros.", 3, true),
        new("jugulares", "Jugulares", "pescoco-anterior", 2, "anterior",
            "Veias jugulares sem ingurgitamento com paciente a 45°.", 4, true),

        // === NÍVEL 2 — Filhos de MSD/MSE Anterior ===
        new("ombro-direito", "Ombro direito", "msd-anterior", 2, "anterior",
            "Ombro sem deformidades. Amplitude de movimento preservada.", 1, false),
        new("braco-direito", "Braço direito", "msd-anterior", 2, "anterior",
            "Braço sem edema ou lesões. Musculatura com tônus preservado.", 2, false),
        new("cotovelo-direito", "Cotovelo direito", "msd-anterior", 2, "anterior",
            "Cotovelo sem derrame articular. Flexo-extensão completa.", 3, false),
        new("antebraco-direito", "Antebraço direito", "msd-anterior", 2, "anterior",
            "Antebraço sem edema. Prono-supinação preservada.", 4, false),
        new("punho-direito", "Punho direito", "msd-anterior", 2, "anterior",
            "Punho sem edema ou deformidades. Teste de Phalen e Tinel negativos.", 5, false),
        new("mao-direita", "Mão direita", "msd-anterior", 2, "anterior",
            "Mão sem edema ou deformidades. Preensão preservada. Perfusão capilar < 3s.", 6, false),

        new("ombro-esquerdo", "Ombro esquerdo", "mse-anterior", 2, "anterior",
            "Ombro sem deformidades. Amplitude de movimento preservada.", 1, false),
        new("braco-esquerdo", "Braço esquerdo", "mse-anterior", 2, "anterior",
            "Braço sem edema ou lesões. Musculatura com tônus preservado.", 2, false),
        new("cotovelo-esquerdo", "Cotovelo esquerdo", "mse-anterior", 2, "anterior",
            "Cotovelo sem derrame articular. Flexo-extensão completa.", 3, false),
        new("antebraco-esquerdo", "Antebraço esquerdo", "mse-anterior", 2, "anterior",
            "Antebraço sem edema. Prono-supinação preservada.", 4, false),
        new("punho-esquerdo", "Punho esquerdo", "mse-anterior", 2, "anterior",
            "Punho sem edema ou deformidades. Teste de Phalen e Tinel negativos.", 5, false),
        new("mao-esquerda", "Mão esquerda", "mse-anterior", 2, "anterior",
            "Mão sem edema ou deformidades. Preensão preservada. Perfusão capilar < 3s.", 6, false),

        // === NÍVEL 2 — Filhos de MID/MIE Anterior ===
        new("quadril-direito", "Quadril direito", "mid-anterior", 2, "anterior",
            "Quadril sem deformidades. Amplitude de movimento preservada.", 1, false),
        new("coxa-direita", "Coxa direita", "mid-anterior", 2, "anterior",
            "Coxa sem edema ou lesões. Musculatura com tônus e trofismo preservados.", 2, false),
        new("joelho-direito", "Joelho direito", "mid-anterior", 2, "anterior",
            "Joelho sem derrame articular. Ligamentos estáveis. Flexo-extensão completa.", 3, false),
        new("perna-direita", "Perna direita", "mid-anterior", 2, "anterior",
            "Perna sem edema. Sem varizes. Sem sinais de TVP.", 4, false),
        new("tornozelo-direito", "Tornozelo direito", "mid-anterior", 2, "anterior",
            "Tornozelo sem edema ou instabilidade.", 5, false),
        new("pe-direito", "Pé direito", "mid-anterior", 2, "anterior",
            "Pé sem deformidades. Arco plantar preservado. Pulso pedioso palpável.", 6, false),

        new("quadril-esquerdo", "Quadril esquerdo", "mie-anterior", 2, "anterior",
            "Quadril sem deformidades. Amplitude de movimento preservada.", 1, false),
        new("coxa-esquerda", "Coxa esquerda", "mie-anterior", 2, "anterior",
            "Coxa sem edema ou lesões. Musculatura com tônus e trofismo preservados.", 2, false),
        new("joelho-esquerdo", "Joelho esquerdo", "mie-anterior", 2, "anterior",
            "Joelho sem derrame articular. Ligamentos estáveis. Flexo-extensão completa.", 3, false),
        new("perna-esquerda", "Perna esquerda", "mie-anterior", 2, "anterior",
            "Perna sem edema. Sem varizes. Sem sinais de TVP.", 4, false),
        new("tornozelo-esquerdo", "Tornozelo esquerdo", "mie-anterior", 2, "anterior",
            "Tornozelo sem edema ou instabilidade.", 5, false),
        new("pe-esquerdo", "Pé esquerdo", "mie-anterior", 2, "anterior",
            "Pé sem deformidades. Arco plantar preservado. Pulso pedioso palpável.", 6, false),

        // === NÍVEL 2 — Vista POSTERIOR ===
        new("occipital", "Occipital", "cabeca-posterior", 2, "posterior",
            "Região occipital sem massas ou pontos dolorosos.", 1, false),
        new("mastoide", "Mastóide", "cabeca-posterior", 2, "posterior",
            "Região mastoidea sem dor à palpação. Sem sinais de Battle.", 2, true),
        new("musculatura-cervical", "Musculatura cervical", "pescoco-posterior", 2, "posterior",
            "Musculatura cervical posterior sem contraturas. Sem pontos gatilho.", 1, false),
        new("linfonodos-cervicais-post", "Linfonodos cervicais posteriores", "pescoco-posterior", 2, "posterior",
            "Linfonodos cervicais posteriores não palpáveis.", 2, true),
        new("coluna-toracica", "Coluna torácica", "torax-posterior", 2, "posterior",
            "Coluna torácica alinhada, sem desvios.", 1, false),
        new("escapula", "Escápula", "torax-posterior", 2, "posterior",
            "Escápula sem alamento. Musculatura periescapular com tônus preservado.", 2, true),
        new("pulmao-posterior", "Pulmão (posterior)", "torax-posterior", 2, "posterior",
            "Murmúrio vesicular fisiológico bilateralmente na ausculta posterior.", 3, true),
        new("coluna-lombar", "Coluna lombar", "lombossacra-posterior", 2, "posterior",
            "Coluna lombar alinhada. Sem dor à palpação. Mobilidade preservada.", 1, false),
        new("regiao-sacral", "Região sacral", "lombossacra-posterior", 2, "posterior",
            "Região sacral sem dor à palpação. Sem fístulas ou lesões.", 2, false),
        new("musculatura-paravertebral", "Musculatura paravertebral", "lombossacra-posterior", 2, "posterior",
            "Musculatura paravertebral sem contraturas ou pontos dolorosos.", 3, true),
        new("gluteo", "Glúteo", "pelve-posterior", 2, "posterior",
            "Região glútea sem alterações. Musculatura com tônus preservado.", 1, true),
        new("regiao-perianal", "Região perianal", "pelve-posterior", 2, "posterior",
            "Região perianal sem fissuras, fístulas ou hemorroidas externas.", 2, false),
        new("ombro-direito-post", "Ombro direito (posterior)", "msd-posterior", 2, "posterior",
            "Face posterior do ombro sem alterações.", 1, false),
        new("braco-direito-post", "Braço direito (posterior)", "msd-posterior", 2, "posterior",
            "Face posterior do braço sem lesões. Tríceps com tônus preservado.", 2, false),
        new("cotovelo-direito-post", "Cotovelo direito (posterior)", "msd-posterior", 2, "posterior",
            "Olécrano sem bursite.", 3, false),
        new("ombro-esquerdo-post", "Ombro esquerdo (posterior)", "mse-posterior", 2, "posterior",
            "Face posterior do ombro sem alterações.", 1, false),
        new("braco-esquerdo-post", "Braço esquerdo (posterior)", "mse-posterior", 2, "posterior",
            "Face posterior do braço sem lesões. Tríceps com tônus preservado.", 2, false),
        new("cotovelo-esquerdo-post", "Cotovelo esquerdo (posterior)", "mse-posterior", 2, "posterior",
            "Olécrano sem bursite.", 3, false),
        new("coxa-direita-post", "Coxa direita (posterior)", "mid-posterior", 2, "posterior",
            "Face posterior da coxa sem lesões. Isquiotibiais com tônus preservado.", 1, false),
        new("fossa-poplitea-direita", "Fossa poplítea direita", "mid-posterior", 2, "posterior",
            "Fossa poplítea sem massas palpáveis. Sem cisto de Baker.", 2, false),
        new("panturrilha-direita", "Panturrilha direita", "mid-posterior", 2, "posterior",
            "Panturrilha sem empastamento. Sinal de Homans negativo.", 3, false),
        new("tendao-aquiles-direito", "Tendão de Aquiles direito", "mid-posterior", 2, "posterior",
            "Tendão de Aquiles sem espessamento. Thompson negativo.", 4, false),
        new("coxa-esquerda-post", "Coxa esquerda (posterior)", "mie-posterior", 2, "posterior",
            "Face posterior da coxa sem lesões. Isquiotibiais com tônus preservado.", 1, false),
        new("fossa-poplitea-esquerda", "Fossa poplítea esquerda", "mie-posterior", 2, "posterior",
            "Fossa poplítea sem massas palpáveis. Sem cisto de Baker.", 2, false),
        new("panturrilha-esquerda", "Panturrilha esquerda", "mie-posterior", 2, "posterior",
            "Panturrilha sem empastamento. Sinal de Homans negativo.", 3, false),
        new("tendao-aquiles-esquerdo", "Tendão de Aquiles esquerdo", "mie-posterior", 2, "posterior",
            "Tendão de Aquiles sem espessamento. Thompson negativo.", 4, false),

        // === NÍVEL 3 — Filhos de Pulmão ===
        new("apice-pulmonar", "Ápice pulmonar", "pulmao", 3, "anterior",
            "MV fisiológico no ápice. Sem ruídos adventícios.", 1, true),
        new("base-pulmonar", "Base pulmonar", "pulmao", 3, "anterior",
            "MV fisiológico na base. Sem crepitações ou sibilos.", 2, true),
        new("lobo-medio-lingula", "Lobo médio/língula", "pulmao", 3, "anterior",
            "Ausculta sem alterações em lobo médio/língula.", 3, true),

        // === NÍVEL 3 — Filhos de Coração ===
        new("foco-aortico", "Foco aórtico", "coracao", 3, "anterior",
            "Bulha normofonética. Sem sopros.", 1, false),
        new("foco-pulmonar", "Foco pulmonar", "coracao", 3, "anterior",
            "Bulha normofonética. Sem sopros.", 2, false),
        new("foco-tricuspide", "Foco tricúspide", "coracao", 3, "anterior",
            "Bulha normofonética. Sem sopros.", 3, false),
        new("foco-mitral", "Foco mitral", "coracao", 3, "anterior",
            "Bulha normofonética. Sem sopros. Sem cliques.", 4, false),
        new("foco-aortico-acessorio", "Foco aórtico acessório", "coracao", 3, "anterior",
            "Sem sopros (ponto de Erb).", 5, false),

        // === NÍVEL 3 — Filhos de Mama ===
        new("qse-mama", "QSE mama", "mama", 3, "anterior",
            "Quadrante superior externo sem nódulos.", 1, true),
        new("qsi-mama", "QSI mama", "mama", 3, "anterior",
            "Quadrante superior interno sem nódulos.", 2, true),
        new("qie-mama", "QIE mama", "mama", 3, "anterior",
            "Quadrante inferior externo sem nódulos.", 3, true),
        new("qii-mama", "QII mama", "mama", 3, "anterior",
            "Quadrante inferior interno sem nódulos.", 4, true),
        new("regiao-areolar", "Região areolar", "mama", 3, "anterior",
            "Sem retração ou descarga papilar.", 5, true),

        // === NÍVEL 3 — Filhos de Olho ===
        new("palpebra", "Pálpebra", "olho", 3, "anterior",
            "Pálpebras sem ptose, edema ou lesões.", 1, true),
        new("conjuntiva", "Conjuntiva", "olho", 3, "anterior",
            "Conjuntiva normocorada e sem hiperemia.", 2, true),
        new("cornea", "Córnea", "olho", 3, "anterior",
            "Córnea transparente, sem opacidades.", 3, true),
        new("pupila", "Pupila", "olho", 3, "anterior",
            "Pupilas isocóricas, fotorreagentes.", 4, true),
        new("fundo-de-olho", "Fundo de olho", "olho", 3, "anterior",
            "Papila de bordos nítidos. Vasos sem alterações.", 5, true),

        // === NÍVEL 3 — Filhos de Orelha ===
        new("pavilhao-auricular", "Pavilhão auricular", "orelha", 3, "anterior",
            "Pavilhão auricular sem deformidades ou lesões.", 1, true),
        new("conduto-auditivo", "Conduto auditivo", "orelha", 3, "anterior",
            "Conduto auditivo externo pérvio.", 2, true),
        new("membrana-timpanica", "Membrana timpânica", "orelha", 3, "anterior",
            "Membrana timpânica íntegra, translúcida.", 3, true),

        // === NÍVEL 3 — Filhos de Boca ===
        new("labios", "Lábios", "boca", 3, "anterior",
            "Lábios normocorados, sem lesões.", 1, false),
        new("lingua", "Língua", "boca", 3, "anterior",
            "Língua normocorada, úmida, sem saburra.", 2, false),
        new("gengiva", "Gengiva", "boca", 3, "anterior",
            "Gengiva normocorada, sem hipertrofia.", 3, false),
        new("palato", "Palato", "boca", 3, "anterior",
            "Palato duro e mole sem lesões. Úvula centrada.", 4, false),
        new("orofaringe", "Orofaringe", "boca", 3, "anterior",
            "Orofaringe sem hiperemia. Amígdalas sem hipertrofia.", 5, false),
        new("dentes", "Dentes", "boca", 3, "anterior",
            "Arcada dentária sem cáries visíveis.", 6, false),

        // === NÍVEL 3 — Filhos de Joelho ===
        new("menisco-medial-d", "Menisco medial D", "joelho-direito", 3, "anterior",
            "McMurray negativo para menisco medial.", 1, false),
        new("menisco-lateral-d", "Menisco lateral D", "joelho-direito", 3, "anterior",
            "McMurray negativo para menisco lateral.", 2, false),
        new("lca-direito", "LCA direito", "joelho-direito", 3, "anterior",
            "Lachman negativo. Gaveta anterior negativa.", 3, false),
        new("lcp-direito", "LCP direito", "joelho-direito", 3, "anterior",
            "Gaveta posterior negativa.", 4, false),
        new("patela-d", "Patela D", "joelho-direito", 3, "anterior",
            "Patela centrada, sem derrame.", 5, false),

        new("menisco-medial-e", "Menisco medial E", "joelho-esquerdo", 3, "anterior",
            "McMurray negativo para menisco medial.", 1, false),
        new("menisco-lateral-e", "Menisco lateral E", "joelho-esquerdo", 3, "anterior",
            "McMurray negativo para menisco lateral.", 2, false),
        new("lca-esquerdo", "LCA esquerdo", "joelho-esquerdo", 3, "anterior",
            "Lachman negativo. Gaveta anterior negativa.", 3, false),
        new("lcp-esquerdo", "LCP esquerdo", "joelho-esquerdo", 3, "anterior",
            "Gaveta posterior negativa.", 4, false),
        new("patela-e", "Patela E", "joelho-esquerdo", 3, "anterior",
            "Patela centrada, sem derrame.", 5, false),

        // === NÍVEL 3 — Filhos de Mão ===
        new("dedos-mao-d", "Dedos mão D", "mao-direita", 3, "anterior",
            "Sem deformidades. Mobilidade preservada.", 1, false),
        new("mcf-direitas", "MCF direitas", "mao-direita", 3, "anterior",
            "Sem edema, dor ou desvio ulnar.", 2, false),
        new("eminencia-tenar-d", "Eminência tenar D", "mao-direita", 3, "anterior",
            "Sem atrofia. Oposição preservada.", 3, false),
        new("dedos-mao-e", "Dedos mão E", "mao-esquerda", 3, "anterior",
            "Sem deformidades. Mobilidade preservada.", 1, false),
        new("mcf-esquerdas", "MCF esquerdas", "mao-esquerda", 3, "anterior",
            "Sem edema, dor ou desvio ulnar.", 2, false),
        new("eminencia-tenar-e", "Eminência tenar E", "mao-esquerda", 3, "anterior",
            "Sem atrofia. Oposição preservada.", 3, false),

        // === NÍVEL 3 — Filhos de Pé ===
        new("dedos-pe-d", "Dedos pé D", "pe-direito", 3, "anterior",
            "Sem deformidades. Unhas sem alterações.", 1, false),
        new("arco-plantar-d", "Arco plantar D", "pe-direito", 3, "anterior",
            "Arco plantar preservado.", 2, false),
        new("calcanhar-d", "Calcanhar D", "pe-direito", 3, "anterior",
            "Sem esporão palpável.", 3, false),
        new("dedos-pe-e", "Dedos pé E", "pe-esquerdo", 3, "anterior",
            "Sem deformidades. Unhas sem alterações.", 1, false),
        new("arco-plantar-e", "Arco plantar E", "pe-esquerdo", 3, "anterior",
            "Arco plantar preservado.", 2, false),
        new("calcanhar-e", "Calcanhar E", "pe-esquerdo", 3, "anterior",
            "Sem esporão palpável.", 3, false),

        // === NÍVEL 3 — Filhos de Coluna Lombar (posterior) ===
        new("articulacao-sacroiliaca", "Articulação sacroilíaca", "coluna-lombar", 3, "posterior",
            "Sem dor. Patrick/FABER negativo.", 1, false),
        new("processos-espinhosos-lombares", "Processos espinhosos lombares", "coluna-lombar", 3, "posterior",
            "Sem dor à palpação. Sem degraus palpáveis.", 2, false),
    };
}
