// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Imedto.Backend.Infrastructure.Database;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Imedto.Backend.Infrastructure.Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260418232458_CriarInventario")]
    partial class CriarInventario
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Imedto.Backend.Domain.Agendamentos.Agendamento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<Guid>("CriadoPorUsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("criado_por_usuario_id");

                    b.Property<long>("EstabelecimentoId")
                        .HasColumnType("bigint")
                        .HasColumnName("estabelecimento_id");

                    b.Property<DateTime>("FimPrevisto")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fim_previsto");

                    b.Property<DateTime>("InicioPrevisto")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("inicio_previsto");

                    b.Property<string>("MotivoCancelamento")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("motivo_cancelamento");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("observacoes");

                    b.Property<long>("PacienteId")
                        .HasColumnType("bigint")
                        .HasColumnName("paciente_id");

                    b.Property<Guid>("ProfissionalUsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("profissional_usuario_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("TipoServico")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tipo_servico");

                    b.HasKey("Id");

                    b.HasIndex("EstabelecimentoId", "InicioPrevisto")
                        .HasDatabaseName("ix_agendamentos_estab_inicio");

                    b.HasIndex("PacienteId", "InicioPrevisto")
                        .HasDatabaseName("ix_agendamentos_paciente_inicio");

                    b.HasIndex("ProfissionalUsuarioId", "InicioPrevisto")
                        .HasDatabaseName("ix_agendamentos_prof_inicio");

                    b.ToTable("agendamentos", "public");
                });

            modelBuilder.Entity("Imedto.Backend.Domain.Estabelecimentos.Estabelecimento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("Cnpj")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("cnpj");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<Guid>("DonoUsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("dono_usuario_id");

                    b.Property<string>("Endereco")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("endereco");

                    b.Property<string>("NomeFantasia")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome_fantasia");

                    b.Property<string>("RazaoSocial")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("razao_social");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefone");

                    b.HasKey("Id");

                    b.HasIndex("Cnpj")
                        .IsUnique()
                        .HasDatabaseName("uq_estabelecimentos_cnpj")
                        .HasFilter("cnpj IS NOT NULL");

                    b.HasIndex("DonoUsuarioId")
                        .IsUnique()
                        .HasDatabaseName("uq_estabelecimentos_dono");

                    b.ToTable("estabelecimentos", "public");
                });

            modelBuilder.Entity("Imedto.Backend.Domain.Inventario.ItemInventario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("categoria");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<long>("EstabelecimentoId")
                        .HasColumnType("bigint")
                        .HasColumnName("estabelecimento_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<decimal>("QuantidadeAtual")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("quantidade_atual");

                    b.Property<decimal>("QuantidadeMinima")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("quantidade_minima");

                    b.Property<string>("UnidadeMedida")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("unidade_medida");

                    b.HasKey("Id");

                    b.HasIndex("EstabelecimentoId", "Ativo")
                        .HasDatabaseName("ix_inventario_estab_ativo");

                    b.HasIndex("EstabelecimentoId", "Codigo")
                        .IsUnique()
                        .HasDatabaseName("uq_inventario_codigo_por_estab");

                    b.ToTable("itens_inventario", "public");
                });

            modelBuilder.Entity("Imedto.Backend.Domain.Inventario.MovimentacaoEstoque", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<Guid>("CriadoPorUsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("criado_por_usuario_id");

                    b.Property<long>("EstabelecimentoId")
                        .HasColumnType("bigint")
                        .HasColumnName("estabelecimento_id");

                    b.Property<long>("ItemInventarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("item_inventario_id");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("observacao");

                    b.Property<decimal>("Quantidade")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("quantidade");

                    b.Property<decimal>("QuantidadeAnterior")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("quantidade_anterior");

                    b.Property<decimal>("QuantidadeApos")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("quantidade_apos");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.HasIndex("EstabelecimentoId", "CriadoEm")
                        .HasDatabaseName("ix_movimentacao_estab_data");

                    b.HasIndex("ItemInventarioId", "CriadoEm")
                        .HasDatabaseName("ix_movimentacao_item_data");

                    b.ToTable("movimentacoes_estoque", "public");
                });

            modelBuilder.Entity("Imedto.Backend.Domain.ModelosPermissao.ModeloPermissaoEstabelecimento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<bool>("EhPadrao")
                        .HasColumnType("boolean")
                        .HasColumnName("eh_padrao");

                    b.Property<long>("EstabelecimentoId")
                        .HasColumnType("bigint")
                        .HasColumnName("estabelecimento_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<string>("PermissoesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("permissoes");

                    b.Property<string>("TipoAcesso")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo_acesso");

                    b.HasKey("Id");

                    b.HasIndex("EstabelecimentoId")
                        .HasDatabaseName("ix_modelo_permissao_estabelecimento");

                    b.HasIndex("EstabelecimentoId", "Nome")
                        .IsUnique()
                        .HasDatabaseName("uq_modelo_permissao_nome_por_estabelecimento");

                    b.ToTable("modelo_permissao_estabelecimento", "public");
                });

            modelBuilder.Entity("Imedto.Backend.Domain.Pacientes.Paciente", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("Cpf")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("cpf");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("date")
                        .HasColumnName("data_nascimento");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<Guid?>("DeletadoPorUsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("deletado_por_usuario_id");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("Endereco")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("endereco");

                    b.Property<long>("EstabelecimentoId")
                        .HasColumnType("bigint")
                        .HasColumnName("estabelecimento_id");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("genero");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome_completo");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("observacoes");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefone");

                    b.HasKey("Id");

                    b.HasIndex("EstabelecimentoId", "Cpf")
                        .IsUnique()
                        .HasDatabaseName("uq_pacientes_estabelecimento_cpf")
                        .HasFilter("cpf IS NOT NULL AND deletado_em IS NULL");

                    b.HasIndex("EstabelecimentoId", "DeletadoEm")
                        .HasDatabaseName("ix_pacientes_estabelecimento");

                    b.ToTable("pacientes", "public");
                });

            modelBuilder.Entity("Imedto.Backend.Domain.Profissionais.Profissional", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("Bio")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("bio");

                    b.Property<string>("Conselho")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("conselho");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Especialidade")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("especialidade");

                    b.Property<string>("NumeroRegistro")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("numero_registro");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character(2)")
                        .HasColumnName("uf")
                        .IsFixedLength();

                    b.HasKey("Id");

                    b.HasIndex("Conselho", "Uf", "NumeroRegistro")
                        .IsUnique()
                        .HasDatabaseName("uq_profissionais_conselho_uf_numero");

                    b.ToTable("profissionais", "public");
                });

            modelBuilder.Entity("Imedto.Backend.Domain.Prontuarios.ModeloDeProntuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Descricao")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("descricao");

                    b.Property<bool>("EhPadraoSistema")
                        .HasColumnType("boolean")
                        .HasColumnName("eh_padrao_sistema");

                    b.Property<long?>("EstabelecimentoId")
                        .HasColumnType("bigint")
                        .HasColumnName("estabelecimento_id");

                    b.Property<string>("EstruturaJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("estrutura");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.HasIndex("EhPadraoSistema")
                        .HasDatabaseName("ix_modelo_prontuario_padrao_sistema");

                    b.HasIndex("EstabelecimentoId")
                        .HasDatabaseName("ix_modelo_prontuario_estabelecimento");

                    b.ToTable("modelo_de_prontuario", "public");
                });

            modelBuilder.Entity("Imedto.Backend.Domain.Prontuarios.Prontuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<long>("EstabelecimentoId")
                        .HasColumnType("bigint")
                        .HasColumnName("estabelecimento_id");

                    b.Property<long>("ModeloDeProntuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("modelo_de_prontuario_id");

                    b.Property<long>("PacienteId")
                        .HasColumnType("bigint")
                        .HasColumnName("paciente_id");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId", "EstabelecimentoId")
                        .IsUnique()
                        .HasDatabaseName("uq_prontuario_paciente_estabelecimento");

                    b.ToTable("prontuarios", "public");
                });

            modelBuilder.Entity("Imedto.Backend.Domain.Prontuarios.ProntuarioAcessoLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("EstabelecimentoId")
                        .HasColumnType("bigint")
                        .HasColumnName("estabelecimento_id");

                    b.Property<DateTime>("OcorridoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ocorrido_em");

                    b.Property<long>("ProntuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("prontuario_id");

                    b.Property<string>("TipoAcesso")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo_acesso");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_acesso_log_usuario");

                    b.HasIndex("ProntuarioId", "OcorridoEm")
                        .HasDatabaseName("ix_acesso_log_prontuario_data");

                    b.ToTable("prontuario_acesso_log", "public");
                });

            modelBuilder.Entity("Imedto.Backend.Domain.Prontuarios.ProntuarioAnexo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("ArquivadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("arquivado_em");

                    b.Property<Guid?>("ArquivadoPorUsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("arquivado_por_usuario_id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<Guid>("CriadoPorUsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("criado_por_usuario_id");

                    b.Property<long>("EstabelecimentoId")
                        .HasColumnType("bigint")
                        .HasColumnName("estabelecimento_id");

                    b.Property<long?>("EvolucaoId")
                        .HasColumnType("bigint")
                        .HasColumnName("evolucao_id");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("mime_type");

                    b.Property<string>("NomeOriginal")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("nome_original");

                    b.Property<long>("ProntuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("prontuario_id");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("storage_path");

                    b.Property<long>("TamanhoBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("tamanho_bytes");

                    b.HasKey("Id");

                    b.HasIndex("EvolucaoId")
                        .HasDatabaseName("ix_anexos_evolucao");

                    b.HasIndex("ProntuarioId", "ArquivadoEm")
                        .HasDatabaseName("ix_anexos_prontuario");

                    b.ToTable("prontuario_anexos", "public");
                });

            modelBuilder.Entity("Imedto.Backend.Domain.Prontuarios.ProntuarioEvolucao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("AutorUsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("autor_usuario_id");

                    b.Property<string>("ConteudoJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("conteudo");

                    b.Property<DateTime>("CriadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criada_em");

                    b.Property<long>("ModeloDeProntuarioIdOrigem")
                        .HasColumnType("bigint")
                        .HasColumnName("modelo_de_prontuario_id_origem");

                    b.Property<string>("ModeloSnapshotJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("modelo_snapshot");

                    b.Property<long>("ProntuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("prontuario_id");

                    b.HasKey("Id");

                    b.HasIndex("ProntuarioId", "CriadaEm")
                        .HasDatabaseName("ix_evolucoes_prontuario_data");

                    b.ToTable("prontuario_evolucoes", "public");
                });

            modelBuilder.Entity("Imedto.Backend.Domain.Prontuarios.ProntuarioVariavelPool", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<bool>("EhPadraoSistema")
                        .HasColumnType("boolean")
                        .HasColumnName("eh_padrao_sistema");

                    b.Property<long?>("EstabelecimentoId")
                        .HasColumnType("bigint")
                        .HasColumnName("estabelecimento_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.HasIndex("EhPadraoSistema", "Tipo")
                        .HasDatabaseName("ix_pool_padrao_tipo");

                    b.HasIndex("EstabelecimentoId", "Tipo")
                        .HasDatabaseName("ix_pool_estabelecimento_tipo");

                    b.ToTable("prontuario_variaveis_pool", "public");
                });

            modelBuilder.Entity("Imedto.Backend.Domain.Usuarios.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("Cpf")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("cpf");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("NomeCompleto")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome_completo");

                    b.Property<bool>("OnboardingCompleto")
                        .HasColumnType("boolean")
                        .HasColumnName("onboarding_completo");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefone");

                    b.Property<DateTime?>("UltimoAcessoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultimo_acesso_em");

                    b.HasKey("Id");

                    b.HasIndex("Cpf")
                        .IsUnique()
                        .HasDatabaseName("uq_usuarios_cpf")
                        .HasFilter("cpf IS NOT NULL");

                    b.HasIndex("Email")
                        .HasDatabaseName("ix_usuarios_email");

                    b.ToTable("usuarios", "public");
                });

            modelBuilder.Entity("Imedto.Backend.Domain.Vinculos.VinculoProfissionalEstabelecimento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("AceitoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("aceito_em");

                    b.Property<DateTime>("ConvidadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("convidado_em");

                    b.Property<Guid>("ConvidadoPorUsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("convidado_por_usuario_id");

                    b.Property<long>("EstabelecimentoId")
                        .HasColumnType("bigint")
                        .HasColumnName("estabelecimento_id");

                    b.Property<DateTime?>("InativadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("inativado_em");

                    b.Property<long>("ModeloPermissaoId")
                        .HasColumnType("bigint")
                        .HasColumnName("modelo_permissao_id");

                    b.Property<Guid>("ProfissionalUsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("profissional_usuario_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("EstabelecimentoId", "Status")
                        .HasDatabaseName("ix_vinculo_estabelecimento_status");

                    b.HasIndex("ProfissionalUsuarioId", "Status")
                        .HasDatabaseName("ix_vinculo_profissional_status");

                    b.ToTable("vinculo_profissional_estabelecimento", "public");
                });

            modelBuilder.Entity("Imedto.Backend.Domain.Agendamentos.Agendamento", b =>
                {
                    b.HasOne("Imedto.Backend.Domain.Estabelecimentos.Estabelecimento", null)
                        .WithMany()
                        .HasForeignKey("EstabelecimentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_agendamento_estabelecimento");

                    b.HasOne("Imedto.Backend.Domain.Pacientes.Paciente", null)
                        .WithMany()
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_agendamento_paciente");
                });

            modelBuilder.Entity("Imedto.Backend.Domain.Inventario.ItemInventario", b =>
                {
                    b.HasOne("Imedto.Backend.Domain.Estabelecimentos.Estabelecimento", null)
                        .WithMany()
                        .HasForeignKey("EstabelecimentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_inventario_estabelecimento");
                });

            modelBuilder.Entity("Imedto.Backend.Domain.Inventario.MovimentacaoEstoque", b =>
                {
                    b.HasOne("Imedto.Backend.Domain.Estabelecimentos.Estabelecimento", null)
                        .WithMany()
                        .HasForeignKey("EstabelecimentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_movimentacao_estabelecimento");

                    b.HasOne("Imedto.Backend.Domain.Inventario.ItemInventario", null)
                        .WithMany()
                        .HasForeignKey("ItemInventarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_movimentacao_item_inventario");
                });
#pragma warning restore 612, 618
        }
    }
}
