using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Imedto.Backend.Infrastructure.Database.Migrations
{
    /// <inheritdoc />
    public partial class CriarTabelaMigracaoJobEventos : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // ── 1. Tabela migracao_job_eventos ────────────────────────────────────
            // Trilha forward-only de transições de status de um MigracaoJob.
            // Sem PII — só metadados de transição (status_anterior, status_novo, usuario_id, criado_em).
            // Multi-tenant: estabelecimento_id herdado do job.
            // FK com CASCADE: ao excluir o job, os eventos são removidos junto.
            // (addendum 003 — briefing 2026-06-15_004)
            migrationBuilder.Sql(@"
CREATE TABLE IF NOT EXISTS public.migracao_job_eventos (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    migracao_job_id   BIGINT        NOT NULL,
    estabelecimento_id BIGINT       NOT NULL,
    status_anterior   TEXT          NULL,
    status_novo       TEXT          NOT NULL,
    usuario_id        UUID          NULL,
    criado_em         TIMESTAMPTZ   NOT NULL,
    CONSTRAINT fk_migracao_job_eventos_job
        FOREIGN KEY (migracao_job_id)
        REFERENCES public.migracao_jobs (id)
        ON DELETE CASCADE
);");

            // Índice da timeline cronológica por job.
            migrationBuilder.Sql(@"
CREATE INDEX IF NOT EXISTS ix_migracao_job_eventos_job_criado_em
    ON public.migracao_job_eventos (migracao_job_id, criado_em);");

            // ── 2. Índice em migracao_jobs para filtro de período + ordenação ─────
            // Query de listagem admin filtra criado_em (intervalo) e ordena DESC.
            // Colunas: (estabelecimento_id, criado_em DESC) — igualdade primeiro.
            // Não existe ainda: ix_migracao_jobs_estab_status tem (estabelecimento_id, status)
            // e ix_migracao_jobs_estab_onda_status tem (estabelecimento_id, onda, status).
            // Nenhum deles cobre criado_em.
            migrationBuilder.Sql(@"
CREATE INDEX IF NOT EXISTS ix_migracao_jobs_estab_criado_em
    ON public.migracao_jobs (estabelecimento_id, criado_em DESC);");

            // ── 3. Índice em migracao_registros (job_id, status) ─────────────────
            // ix_migracao_registros_job_status (migracao_job_id, status) JÁ EXISTE
            // desde a migration 20260615152934_CriarTabelasMigracao. Não recriar.
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                "DROP INDEX IF EXISTS public.ix_migracao_jobs_estab_criado_em;");

            migrationBuilder.Sql(
                "DROP INDEX IF EXISTS public.ix_migracao_job_eventos_job_criado_em;");

            migrationBuilder.Sql(
                "DROP TABLE IF EXISTS public.migracao_job_eventos;");
        }
    }
}
