using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Imedto.Backend.Infrastructure.Database.Migrations
{
    /// <inheritdoc />
    public partial class CriarCategoriaFinanceiraPadraoSistema : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Tabela global de categorias financeiras padrão da plataforma (briefing 2026-06-22_003 M1).
            // Sem estabelecimento_id — escopo plataforma. Acesso exclusivo pelo admin global.
            // Idempotente via CREATE TABLE IF NOT EXISTS (gotcha: QA aplica schema fora do EFMigrationsHistory).
            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS public.categorias_financeiras_padrao_sistema (
                    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    nome        character varying(80)           NOT NULL,
                    tipo        character varying(10)           NOT NULL,
                    ativo       boolean                         NOT NULL DEFAULT true,
                    criada_em   timestamp with time zone        NOT NULL,
                    atualizada_em timestamp with time zone      NULL
                );
                """);

            // Índice único (nome, tipo) — chave de negócio do catálogo global.
            migrationBuilder.Sql("""
                CREATE UNIQUE INDEX IF NOT EXISTS uq_categorias_financeiras_padrao_sistema_nome_tipo
                    ON public.categorias_financeiras_padrao_sistema (nome, tipo);
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                DROP TABLE IF EXISTS public.categorias_financeiras_padrao_sistema;
                """);
        }
    }
}
