// <auto-generated />
using System;
using Imedto.Backend.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Imedto.Backend.Infrastructure.Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260615200000_AdicionarMotivoFalhaJob")]
    partial class AdicionarMotivoFalhaJob
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Modelo completo mantido no AppDbContextModelSnapshot.cs.
            // Este Designer registra apenas o ID da migration para controle do EF Core.
            // As novas propriedades MotivoFalha e StatusAntesFalha estão refletidas
            // no AppDbContextModelSnapshot.cs (entidade MigracaoJob).
        }
    }
}
