using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Imedto.Backend.Infrastructure.Database.Migrations
{
    /// <summary>
    /// Cria a tabela modelos_descricao_cirurgica para o aggregate ModeloDescricaoCirurgica
    /// (bounded context Prontuários).
    ///
    /// Padrão live-link: registros com eh_padrao_sistema = true têm estabelecimento_id = NULL
    /// (visíveis a todos os tenants). Registros do tenant têm estabelecimento_id NOT NULL.
    ///
    /// Implementação via SQL raw idempotente (IF NOT EXISTS + DO-guards) para tolerar
    /// o caso em que o schema foi aplicado manualmente antes do registro em
    /// __ef_migrations_history (padrão pós-incidente 2026-06-12).
    /// </summary>
    public partial class CriarModeloDescricaoCirurgica : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // ── Tabela ────────────────────────────────────────────────────────────
            migrationBuilder.Sql(@"
CREATE TABLE IF NOT EXISTS public.modelos_descricao_cirurgica (
    id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estabelecimento_id bigint       NULL,
    titulo             varchar(200) NOT NULL,
    corpo              text         NOT NULL,
    ativo              boolean      NOT NULL DEFAULT true,
    eh_padrao_sistema  boolean      NOT NULL DEFAULT false,
    criado_em          timestamptz  NOT NULL,
    atualizado_em      timestamptz  NULL
);
");

            // ── FK para estabelecimentos (nullable — padrão-sistema tem NULL) ────
            migrationBuilder.Sql(@"
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_modelo_desc_cirurgica_estabelecimento'
          AND conrelid = 'public.modelos_descricao_cirurgica'::regclass
    ) THEN
        ALTER TABLE public.modelos_descricao_cirurgica
            ADD CONSTRAINT fk_modelo_desc_cirurgica_estabelecimento
            FOREIGN KEY (estabelecimento_id)
            REFERENCES public.estabelecimentos (id)
            ON DELETE RESTRICT;
    END IF;
END $$;
");

            // ── Índices ───────────────────────────────────────────────────────────
            migrationBuilder.Sql(@"
CREATE INDEX IF NOT EXISTS ix_modelo_desc_cirurgica_estabelecimento
    ON public.modelos_descricao_cirurgica (estabelecimento_id);
");

            migrationBuilder.Sql(@"
CREATE INDEX IF NOT EXISTS ix_modelo_desc_cirurgica_padrao
    ON public.modelos_descricao_cirurgica (eh_padrao_sistema);
");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "modelos_descricao_cirurgica",
                schema: "public");
        }
    }
}
