// <auto-generated />
using System;
using Imedto.Backend.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Imedto.Backend.Infrastructure.Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260615220000_CriarTabelaMigracaoJobEventos")]
    partial class CriarTabelaMigracaoJobEventos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Modelo completo mantido no AppDbContextModelSnapshot.cs.
            // Este Designer registra apenas o ID da migration para controle do EF Core.
            // A nova entidade MigracaoJobEvento e os novos índices estão refletidos
            // no AppDbContextModelSnapshot.cs.
        }
    }
}
