-- Cria a tabela public.estabelecimentos (tenant root).
-- EF migration: 20260418042103_CreateEstabelecimentos
-- Complementos: FK para public.usuarios (dono) + RLS enabled sem policies (defense-in-depth).

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260418042103_CreateEstabelecimentos') THEN
    CREATE TABLE public.estabelecimentos (
        id              bigint GENERATED BY DEFAULT AS IDENTITY,
        dono_usuario_id uuid NOT NULL,
        nome_fantasia   character varying(200) NOT NULL,
        razao_social    character varying(200),
        cnpj            character varying(14),
        telefone        character varying(20),
        endereco        character varying(500),
        status          character varying(20) NOT NULL,
        criado_em       timestamp with time zone NOT NULL,
        atualizado_em   timestamp with time zone,
        CONSTRAINT "PK_estabelecimentos" PRIMARY KEY (id)
    );

    CREATE INDEX ix_estabelecimentos_dono ON public.estabelecimentos (dono_usuario_id);
    CREATE UNIQUE INDEX uq_estabelecimentos_cnpj ON public.estabelecimentos (cnpj)
        WHERE cnpj IS NOT NULL;

    ALTER TABLE public.estabelecimentos
        ADD CONSTRAINT fk_estabelecimentos_dono
        FOREIGN KEY (dono_usuario_id) REFERENCES public.usuarios(id) ON DELETE RESTRICT;

    ALTER TABLE public.estabelecimentos ENABLE ROW LEVEL SECURITY;

    COMMENT ON TABLE public.estabelecimentos IS
        'Tenant root — dado de domínio só acessível via backend; RLS negativo em defense-in-depth.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260418042103_CreateEstabelecimentos') THEN
    INSERT INTO public.__ef_migrations_history ("MigrationId", "ProductVersion")
    VALUES ('20260418042103_CreateEstabelecimentos', '10.0.0');
    END IF;
END $EF$;
