-- Migration gerada a partir do EF Core (20260418035744_InitialCreate).
-- Autoria: dotnet ef migrations script --idempotent (dentro de transação do supabase CLI).

CREATE TABLE IF NOT EXISTS public.__ef_migrations_history (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___ef_migrations_history" PRIMARY KEY ("MigrationId")
);

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260418035744_InitialCreate') THEN
    CREATE TABLE public.produtos (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        nome character varying(200) NOT NULL,
        descricao character varying(2000),
        preco numeric(14,2) NOT NULL,
        status character varying(30) NOT NULL,
        criado_em timestamp with time zone NOT NULL,
        atualizado_em timestamp with time zone,
        CONSTRAINT "PK_produtos" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260418035744_InitialCreate') THEN
    INSERT INTO public.__ef_migrations_history ("MigrationId", "ProductVersion")
    VALUES ('20260418035744_InitialCreate', '10.0.0');
    END IF;
END $EF$;
