-- Tabelas de templates e pool de variáveis de prontuário.
-- Ambas suportam escopo duplo:
--   - padrão-sistema (estabelecimento_id IS NULL, eh_padrao_sistema = true) — gerenciado via admin
--   - do estabelecimento (estabelecimento_id NOT NULL, eh_padrao_sistema = false)
-- EF migration: 20260418155850_CreateModeloProntuarioEPool

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260418155850_CreateModeloProntuarioEPool') THEN

    CREATE TABLE public.modelo_de_prontuario (
        id                 bigint GENERATED BY DEFAULT AS IDENTITY,
        estabelecimento_id bigint,
        nome               character varying(200) NOT NULL,
        descricao          character varying(1000),
        estrutura          jsonb NOT NULL,
        eh_padrao_sistema  boolean NOT NULL,
        ativo              boolean NOT NULL,
        criado_em          timestamp with time zone NOT NULL,
        atualizado_em      timestamp with time zone,
        CONSTRAINT "PK_modelo_de_prontuario" PRIMARY KEY (id),
        CONSTRAINT ck_modelo_escopo
            CHECK ((eh_padrao_sistema = true  AND estabelecimento_id IS NULL)
                OR (eh_padrao_sistema = false AND estabelecimento_id IS NOT NULL))
    );
    CREATE INDEX ix_modelo_prontuario_estabelecimento
        ON public.modelo_de_prontuario (estabelecimento_id);
    CREATE INDEX ix_modelo_prontuario_padrao_sistema
        ON public.modelo_de_prontuario (eh_padrao_sistema);
    ALTER TABLE public.modelo_de_prontuario
        ADD CONSTRAINT fk_modelo_prontuario_estabelecimento
        FOREIGN KEY (estabelecimento_id)
        REFERENCES public.estabelecimentos(id) ON DELETE CASCADE;
    ALTER TABLE public.modelo_de_prontuario ENABLE ROW LEVEL SECURITY;

    CREATE TABLE public.prontuario_variaveis_pool (
        id                 bigint GENERATED BY DEFAULT AS IDENTITY,
        estabelecimento_id bigint,
        tipo               character varying(20) NOT NULL,
        nome               character varying(200) NOT NULL,
        ativo              boolean NOT NULL,
        eh_padrao_sistema  boolean NOT NULL,
        criado_em          timestamp with time zone NOT NULL,
        atualizado_em      timestamp with time zone,
        CONSTRAINT "PK_prontuario_variaveis_pool" PRIMARY KEY (id),
        CONSTRAINT ck_pool_escopo
            CHECK ((eh_padrao_sistema = true  AND estabelecimento_id IS NULL)
                OR (eh_padrao_sistema = false AND estabelecimento_id IS NOT NULL))
    );
    CREATE INDEX ix_pool_estabelecimento_tipo
        ON public.prontuario_variaveis_pool (estabelecimento_id, tipo);
    CREATE INDEX ix_pool_padrao_tipo
        ON public.prontuario_variaveis_pool (eh_padrao_sistema, tipo);
    ALTER TABLE public.prontuario_variaveis_pool
        ADD CONSTRAINT fk_pool_estabelecimento
        FOREIGN KEY (estabelecimento_id)
        REFERENCES public.estabelecimentos(id) ON DELETE CASCADE;
    ALTER TABLE public.prontuario_variaveis_pool ENABLE ROW LEVEL SECURITY;

    COMMENT ON TABLE public.modelo_de_prontuario IS
        'Templates de prontuário — padrão-sistema (admin) ou do estabelecimento.';
    COMMENT ON TABLE public.prontuario_variaveis_pool IS
        'Itens pré-cadastrados (alergias, medicamentos, doenças, cirurgias) — padrão-sistema ou do estabelecimento.';

    -- Seed inicial: 1 modelo padrão-sistema "Consulta clínica geral" com seções mínimas.
    -- Esse seed é substituído pela ferramenta admin quando ela for implementada.
    INSERT INTO public.modelo_de_prontuario
        (estabelecimento_id, nome, descricao, estrutura, eh_padrao_sistema, ativo, criado_em)
    VALUES (
        NULL,
        'Consulta clínica geral',
        'Template base padrão-sistema com seções mínimas para consulta clínica.',
        $json$[
            {"chave":"queixa_principal","titulo":"Queixa principal","tipo":"texto","ordem":1},
            {"chave":"anamnese","titulo":"Anamnese","tipo":"texto_longo","ordem":2},
            {"chave":"exame_fisico","titulo":"Exame físico","tipo":"texto_longo","ordem":3},
            {"chave":"hipotese_diagnostica","titulo":"Hipótese diagnóstica","tipo":"texto","ordem":4},
            {"chave":"conduta","titulo":"Conduta","tipo":"texto_longo","ordem":5},
            {"chave":"medicacoes","titulo":"Medicações prescritas","tipo":"texto_longo","ordem":6}
        ]$json$::jsonb,
        true,
        true,
        now()
    );

    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260418155850_CreateModeloProntuarioEPool') THEN
    INSERT INTO public.__ef_migrations_history ("MigrationId", "ProductVersion")
    VALUES ('20260418155850_CreateModeloProntuarioEPool', '10.0.0');
    END IF;
END $EF$;
