-- ============================================================
-- Fase 6.1.b — Catálogo de produtos para orçamento + vínculo cirurgia × produto.
--
-- Tabelas:
--   - orcamento_catalogo_produto         — catálogo de produtos (nome, valor de
--     referência, flag uso_unico). Independente do inventário/estoque.
--   - orcamento_catalogo_cirurgia_produto — link M:N entre catálogo de cirurgia
--     e catálogo de produto, com quantidade padrão + flag obrigatorio.
-- ============================================================

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260430170259_Fase6_1bProdutos') THEN
    CREATE TABLE public.orcamento_catalogo_produto (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        estabelecimento_id bigint NOT NULL,
        nome character varying(200) NOT NULL,
        descricao character varying(500),
        valor_referencia numeric(12,2),
        uso_unico boolean NOT NULL DEFAULT FALSE,
        ativo boolean NOT NULL DEFAULT TRUE,
        criada_em timestamp with time zone NOT NULL,
        atualizada_em timestamp with time zone,
        CONSTRAINT "PK_orcamento_catalogo_produto" PRIMARY KEY (id),
        CONSTRAINT fk_catalogo_produto_estabelecimento FOREIGN KEY (estabelecimento_id) REFERENCES public.estabelecimentos (id) ON DELETE CASCADE
    );

    CREATE TABLE public.orcamento_catalogo_cirurgia_produto (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        catalogo_cirurgia_id bigint NOT NULL,
        catalogo_produto_id bigint NOT NULL,
        quantidade_padrao numeric(10,3) NOT NULL,
        obrigatorio boolean NOT NULL DEFAULT FALSE,
        criada_em timestamp with time zone NOT NULL,
        CONSTRAINT "PK_orcamento_catalogo_cirurgia_produto" PRIMARY KEY (id),
        CONSTRAINT fk_cirurgia_produto_cirurgia FOREIGN KEY (catalogo_cirurgia_id) REFERENCES public.orcamento_catalogo_cirurgia (id) ON DELETE CASCADE,
        CONSTRAINT fk_cirurgia_produto_produto FOREIGN KEY (catalogo_produto_id) REFERENCES public.orcamento_catalogo_produto (id) ON DELETE CASCADE
    );

    CREATE INDEX ix_catalogo_produto_estab_ativo ON public.orcamento_catalogo_produto (estabelecimento_id, ativo);
    CREATE INDEX "IX_orcamento_catalogo_cirurgia_produto_catalogo_produto_id" ON public.orcamento_catalogo_cirurgia_produto (catalogo_produto_id);
    CREATE UNIQUE INDEX uq_catalogo_cirurgia_produto ON public.orcamento_catalogo_cirurgia_produto (catalogo_cirurgia_id, catalogo_produto_id);

    INSERT INTO public.__ef_migrations_history ("MigrationId", "ProductVersion")
    VALUES ('20260430170259_Fase6_1bProdutos', '10.0.0');
    END IF;
END $EF$;

-- RLS — defense-in-depth (LGPD).
DO $$
BEGIN
    -- Produto: tenant-scoped.
    EXECUTE 'ALTER TABLE public.orcamento_catalogo_produto ENABLE ROW LEVEL SECURITY';
    EXECUTE 'ALTER TABLE public.orcamento_catalogo_produto FORCE ROW LEVEL SECURITY';
    DROP POLICY IF EXISTS orcamento_catalogo_produto_select_tenant ON public.orcamento_catalogo_produto;
    EXECUTE $p$
        CREATE POLICY orcamento_catalogo_produto_select_tenant
            ON public.orcamento_catalogo_produto
            FOR SELECT
            TO authenticated
            USING (
                estabelecimento_id IN (
                    SELECT v.estabelecimento_id
                    FROM public.vinculo_profissional_estabelecimento v
                    WHERE v.profissional_usuario_id = auth.uid()
                      AND v.status = 'Ativo'
                )
                OR estabelecimento_id IN (
                    SELECT e.id
                    FROM public.estabelecimentos e
                    WHERE e.dono_usuario_id = auth.uid()
                )
            );
    $p$;

    -- Vínculo: cascata via parent (cirurgia).
    EXECUTE 'ALTER TABLE public.orcamento_catalogo_cirurgia_produto ENABLE ROW LEVEL SECURITY';
    EXECUTE 'ALTER TABLE public.orcamento_catalogo_cirurgia_produto FORCE ROW LEVEL SECURITY';
    DROP POLICY IF EXISTS orcamento_catalogo_cirurgia_produto_select_via_parent ON public.orcamento_catalogo_cirurgia_produto;
    EXECUTE $p$
        CREATE POLICY orcamento_catalogo_cirurgia_produto_select_via_parent
            ON public.orcamento_catalogo_cirurgia_produto
            FOR SELECT
            TO authenticated
            USING (
                catalogo_cirurgia_id IN (
                    SELECT id FROM public.orcamento_catalogo_cirurgia
                    WHERE estabelecimento_id IN (
                        SELECT v.estabelecimento_id
                        FROM public.vinculo_profissional_estabelecimento v
                        WHERE v.profissional_usuario_id = auth.uid()
                          AND v.status = 'Ativo'
                    )
                    OR estabelecimento_id IN (
                        SELECT e.id FROM public.estabelecimentos e
                        WHERE e.dono_usuario_id = auth.uid()
                    )
                )
            );
    $p$;
END $$;
