-- Cria tabelas tipo_sala_atendimento (catálogo system-wide) e sala_atendimento (repartições por estabelecimento).
-- EF migration: 20260425045955_CriarSalasAtendimento
-- Inclui seed dos tipos padrão (consultório, laboratório, etc.) e RLS habilitado.

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260425045955_CriarSalasAtendimento') THEN
    CREATE TABLE public.tipo_sala_atendimento (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        nome character varying(100) NOT NULL,
        descricao character varying(500),
        CONSTRAINT "PK_tipo_sala_atendimento" PRIMARY KEY (id)
    );

    COMMENT ON TABLE public.tipo_sala_atendimento IS
        'Catálogo system-wide de tipos de sala. Seed gerido pelo backend, somente leitura para o cliente.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260425045955_CriarSalasAtendimento') THEN
    CREATE TABLE public.sala_atendimento (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        estabelecimento_id bigint NOT NULL,
        unidade_id bigint NOT NULL,
        tipo_sala_id bigint,
        nome character varying(200) NOT NULL,
        descricao character varying(500),
        ativo boolean NOT NULL,
        criado_em timestamp with time zone NOT NULL,
        atualizado_em timestamp with time zone,
        CONSTRAINT "PK_sala_atendimento" PRIMARY KEY (id),
        CONSTRAINT fk_salas_estab FOREIGN KEY (estabelecimento_id) REFERENCES public.estabelecimentos (id) ON DELETE CASCADE,
        CONSTRAINT fk_salas_tipo FOREIGN KEY (tipo_sala_id) REFERENCES public.tipo_sala_atendimento (id) ON DELETE SET NULL,
        CONSTRAINT fk_salas_unidade FOREIGN KEY (unidade_id) REFERENCES public.unidades_estabelecimento (id) ON DELETE RESTRICT
    );

    ALTER TABLE public.sala_atendimento ENABLE ROW LEVEL SECURITY;
    ALTER TABLE public.tipo_sala_atendimento ENABLE ROW LEVEL SECURITY;

    COMMENT ON TABLE public.sala_atendimento IS
        'Repartições/salas por estabelecimento e unidade. RLS negativo — acesso só via backend.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260425045955_CriarSalasAtendimento') THEN
    CREATE INDEX "IX_sala_atendimento_tipo_sala_id" ON public.sala_atendimento (tipo_sala_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260425045955_CriarSalasAtendimento') THEN
    CREATE INDEX ix_salas_estab ON public.sala_atendimento (estabelecimento_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260425045955_CriarSalasAtendimento') THEN
    CREATE INDEX ix_salas_unidade ON public.sala_atendimento (unidade_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260425045955_CriarSalasAtendimento') THEN
    CREATE UNIQUE INDEX uq_tipo_sala_nome ON public.tipo_sala_atendimento (nome);
    END IF;
END $EF$;

-- Seed dos tipos padrão de sala (system-wide).
DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260425045955_CriarSalasAtendimento') THEN
    INSERT INTO public.tipo_sala_atendimento (nome, descricao) VALUES
        ('Consultório',     'Sala de atendimento clínico geral e consultas.'),
        ('Cirurgia',        'Sala preparada para procedimentos cirúrgicos.'),
        ('Procedimentos',   'Sala para pequenos procedimentos e curativos.'),
        ('Exames',          'Sala para realização de exames (imagem, laboratoriais).'),
        ('Triagem',         'Sala de triagem e avaliação inicial do paciente.'),
        ('Teleatendimento', 'Sala dedicada a atendimentos remotos / telemedicina.'),
        ('Recepção',        'Área de recepção e atendimento inicial de pacientes.'),
        ('Farmácia',        'Farmácia interna para dispensação de medicamentos.'),
        ('Laboratório',     'Laboratório para análises clínicas e exames.'),
        ('Radiologia',      'Sala de radiologia e exames de imagem.'),
        ('Ultrassonografia','Sala equipada para exames de ultrassom.'),
        ('Fisioterapia',    'Sala para atendimento fisioterápico e reabilitação.'),
        ('Psicologia',      'Sala para atendimento psicológico.'),
        ('Odontologia',     'Consultório odontológico.'),
        ('Enfermaria',      'Enfermaria para observação e internação.'),
        ('Sala de Espera',  'Área de espera para pacientes e acompanhantes.'),
        ('Almoxarifado',    'Área de armazenamento de materiais e insumos.'),
        ('Administração',   'Sala administrativa e gestão.'),
        ('Esterilização',   'Sala de esterilização de materiais e instrumentos.')
    ON CONFLICT (nome) DO NOTHING;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260425045955_CriarSalasAtendimento') THEN
    INSERT INTO public.__ef_migrations_history ("MigrationId", "ProductVersion")
    VALUES ('20260425045955_CriarSalasAtendimento', '10.0.0');
    END IF;
END $EF$;
