
DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260418233525_CriarOrcamentos') THEN
    CREATE TABLE public.orcamentos (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        estabelecimento_id bigint NOT NULL,
        paciente_id bigint NOT NULL,
        numero character varying(20) NOT NULL,
        status character varying(20) NOT NULL,
        validade date NOT NULL,
        observacoes character varying(1000),
        criado_por_usuario_id uuid NOT NULL,
        criado_em timestamp with time zone NOT NULL,
        atualizado_em timestamp with time zone,
        CONSTRAINT "PK_orcamentos" PRIMARY KEY (id),
        CONSTRAINT fk_orcamento_estabelecimento FOREIGN KEY (estabelecimento_id) REFERENCES public.estabelecimentos (id) ON DELETE RESTRICT,
        CONSTRAINT fk_orcamento_paciente FOREIGN KEY (paciente_id) REFERENCES public.pacientes (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260418233525_CriarOrcamentos') THEN
    CREATE TABLE public.itens_orcamento (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        orcamento_id bigint NOT NULL,
        descricao character varying(200) NOT NULL,
        quantidade numeric(10,3) NOT NULL,
        valor_unitario numeric(12,2) NOT NULL,
        desconto_percent numeric(5,2) NOT NULL,
        subtotal numeric(12,2) NOT NULL,
        CONSTRAINT "PK_itens_orcamento" PRIMARY KEY (id),
        CONSTRAINT fk_item_orcamento_orcamento FOREIGN KEY (orcamento_id) REFERENCES public.orcamentos (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260418233525_CriarOrcamentos') THEN
    CREATE INDEX ix_item_orcamento_orcamento ON public.itens_orcamento (orcamento_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260418233525_CriarOrcamentos') THEN
    CREATE INDEX ix_orcamento_estab_paciente ON public.orcamentos (estabelecimento_id, paciente_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260418233525_CriarOrcamentos') THEN
    CREATE INDEX ix_orcamento_estab_status ON public.orcamentos (estabelecimento_id, status);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260418233525_CriarOrcamentos') THEN
    CREATE INDEX "IX_orcamentos_paciente_id" ON public.orcamentos (paciente_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260418233525_CriarOrcamentos') THEN
    INSERT INTO public.__ef_migrations_history ("MigrationId", "ProductVersion")
    VALUES ('20260418233525_CriarOrcamentos', '10.0.0');
    END IF;
END $EF$;

