-- Fase 2 — Waves 2, 3 e 4: schema novo (scheduler, notificacoes, automation,
-- IA settings/audit-link, planos/assinaturas) + ALTER em ai_rate_limits.
--
-- Esta migration combina:
-- 1) SQL idempotente gerado pelo EF Core (CREATE TABLE/INDEX para tabelas novas
--    e ADD COLUMN em ai_audit_logs) — registra a migration no historico do EF.
-- 2) ADIÇÕES MANUAIS pós-EF:
--    a) FKs com ON DELETE SET NULL nas novas colunas de ai_audit_logs
--       (paciente_id -> pacientes, prontuario_id -> prontuarios,
--        evolucao_id -> prontuario_evolucoes). Nao foram declaradas como
--       navegacao no aggregate (item 2.13), entao precisam ser criadas aqui.
--    b) ALTER em ai_rate_limits (item 2.14): adiciona estabelecimento_id NOT NULL
--       DEFAULT 0, troca a UNIQUE de (usuario_id, periodo_inicio) para
--       (usuario_id, estabelecimento_id, periodo_inicio). A tabela foi criada
--       via SQL puro em 20260429023830 — nao tem aggregate EF, entao o EF nao
--       gera ALTER aqui.
--
-- Observacao: BEGIN/COMMIT removidos — supabase CLI gerencia transacao.

-- =====================================================================
-- BLOCO 1 — SQL idempotente gerado pelo EF (Fase2Wave234Schema)
-- =====================================================================

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260429101733_Fase2Wave234Schema') THEN
    ALTER TABLE public.ai_audit_logs ADD evolucao_id bigint;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260429101733_Fase2Wave234Schema') THEN
    ALTER TABLE public.ai_audit_logs ADD paciente_id bigint;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260429101733_Fase2Wave234Schema') THEN
    ALTER TABLE public.ai_audit_logs ADD prontuario_id bigint;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260429101733_Fase2Wave234Schema') THEN
    CREATE TABLE public.automation_rules (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        estabelecimento_id bigint NOT NULL,
        nome character varying(120) NOT NULL,
        evento_gatilho character varying(60) NOT NULL,
        condicoes_json jsonb NOT NULL,
        acoes_json jsonb NOT NULL,
        ativa boolean NOT NULL,
        criado_em timestamp with time zone NOT NULL,
        atualizado_em timestamp with time zone,
        CONSTRAINT "PK_automation_rules" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260429101733_Fase2Wave234Schema') THEN
    CREATE TABLE public.establishment_ai_settings (
        estabelecimento_id bigint NOT NULL,
        ai_enabled boolean NOT NULL DEFAULT TRUE,
        ai_provider character varying(40) NOT NULL DEFAULT 'anthropic',
        ai_model character varying(80) NOT NULL DEFAULT 'claude-sonnet-4-6',
        rate_limit_per_minute integer NOT NULL DEFAULT 10,
        rate_limit_per_day integer NOT NULL DEFAULT 200,
        data_minimization_level character varying(20) NOT NULL DEFAULT 'standard',
        atualizada_em timestamp with time zone,
        CONSTRAINT "PK_establishment_ai_settings" PRIMARY KEY (estabelecimento_id),
        CONSTRAINT "FK_establishment_ai_settings_estabelecimentos_estabelecimento_~" FOREIGN KEY (estabelecimento_id) REFERENCES public.estabelecimentos (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260429101733_Fase2Wave234Schema') THEN
    CREATE TABLE public.jobs_agendados (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        nome character varying(120) NOT NULL,
        proximo_run_em timestamp with time zone NOT NULL,
        ultimo_run_em timestamp with time zone,
        intervalo_seg integer NOT NULL,
        status character varying(20) NOT NULL,
        ultima_falha character varying(500),
        tentativas integer NOT NULL,
        criado_em timestamp with time zone NOT NULL,
        atualizado_em timestamp with time zone,
        CONSTRAINT "PK_jobs_agendados" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260429101733_Fase2Wave234Schema') THEN
    CREATE TABLE public.notificacoes (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        usuario_id uuid NOT NULL,
        estabelecimento_id bigint,
        titulo character varying(200) NOT NULL,
        mensagem character varying(1000) NOT NULL,
        categoria character varying(40) NOT NULL,
        link_acao character varying(500),
        lida boolean NOT NULL,
        criada_em timestamp with time zone NOT NULL,
        lida_em timestamp with time zone,
        CONSTRAINT "PK_notificacoes" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260429101733_Fase2Wave234Schema') THEN
    CREATE TABLE public.planos (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        nome character varying(80) NOT NULL,
        preco_mensal numeric(12,2) NOT NULL DEFAULT 0.0,
        limite_profissionais integer,
        limite_pacientes integer,
        features_json jsonb NOT NULL DEFAULT ('[]'::jsonb),
        ativo boolean NOT NULL DEFAULT TRUE,
        ordem integer NOT NULL DEFAULT 0,
        CONSTRAINT "PK_planos" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260429101733_Fase2Wave234Schema') THEN
    CREATE TABLE public.automation_events (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        regra_id bigint NOT NULL,
        payload_json jsonb NOT NULL,
        status character varying(20) NOT NULL,
        tentativa_n integer NOT NULL,
        executar_em timestamp with time zone NOT NULL,
        executado_em timestamp with time zone,
        ultima_falha character varying(500),
        criado_em timestamp with time zone NOT NULL,
        CONSTRAINT "PK_automation_events" PRIMARY KEY (id),
        CONSTRAINT fk_automation_events_regra FOREIGN KEY (regra_id) REFERENCES public.automation_rules (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260429101733_Fase2Wave234Schema') THEN
    CREATE TABLE public.assinaturas (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        estabelecimento_id bigint NOT NULL,
        plano_id bigint NOT NULL,
        status character varying(20) NOT NULL,
        iniciada_em timestamp with time zone NOT NULL,
        expira_em timestamp with time zone,
        cancelada_em timestamp with time zone,
        renovada_em timestamp with time zone,
        criada_em timestamp with time zone NOT NULL,
        atualizada_em timestamp with time zone,
        CONSTRAINT "PK_assinaturas" PRIMARY KEY (id),
        CONSTRAINT "FK_assinaturas_estabelecimentos_estabelecimento_id" FOREIGN KEY (estabelecimento_id) REFERENCES public.estabelecimentos (id) ON DELETE CASCADE,
        CONSTRAINT "FK_assinaturas_planos_plano_id" FOREIGN KEY (plano_id) REFERENCES public.planos (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260429101733_Fase2Wave234Schema') THEN
    CREATE INDEX "IX_assinaturas_plano_id" ON public.assinaturas (plano_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260429101733_Fase2Wave234Schema') THEN
    CREATE INDEX ix_assinaturas_status_expira ON public.assinaturas (status, expira_em);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260429101733_Fase2Wave234Schema') THEN
    CREATE UNIQUE INDEX uq_assinaturas_estabelecimento ON public.assinaturas (estabelecimento_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260429101733_Fase2Wave234Schema') THEN
    CREATE INDEX "IX_automation_events_regra_id" ON public.automation_events (regra_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260429101733_Fase2Wave234Schema') THEN
    CREATE INDEX ix_automation_events_status_executar_em ON public.automation_events (status, executar_em);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260429101733_Fase2Wave234Schema') THEN
    CREATE INDEX ix_automation_rules_estab_evento_ativa ON public.automation_rules (estabelecimento_id, evento_gatilho, ativa);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260429101733_Fase2Wave234Schema') THEN
    CREATE INDEX ix_jobs_agendados_status_proximo_run ON public.jobs_agendados (status, proximo_run_em);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260429101733_Fase2Wave234Schema') THEN
    CREATE UNIQUE INDEX uq_jobs_agendados_nome ON public.jobs_agendados (nome);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260429101733_Fase2Wave234Schema') THEN
    CREATE INDEX ix_notificacoes_estabelecimento_criada ON public.notificacoes (estabelecimento_id, criada_em);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260429101733_Fase2Wave234Schema') THEN
    CREATE INDEX ix_notificacoes_usuario_lida_criada ON public.notificacoes (usuario_id, lida, criada_em);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260429101733_Fase2Wave234Schema') THEN
    CREATE UNIQUE INDEX uq_planos_nome ON public.planos (nome);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260429101733_Fase2Wave234Schema') THEN
    INSERT INTO public.__ef_migrations_history ("MigrationId", "ProductVersion")
    VALUES ('20260429101733_Fase2Wave234Schema', '10.0.0');
    END IF;
END $EF$;

-- =====================================================================
-- BLOCO 2 — Adições manuais pós-EF
-- =====================================================================

-- Item 2.13: FKs nullable em ai_audit_logs com ON DELETE SET NULL.
-- Justificativa: agregado AiAuditLog NAO declara navegacao para Paciente/
-- Prontuario/Evolucao (apenas as colunas escalares), portanto o EF nao gera
-- a constraint. SET NULL preserva o registro de auditoria mesmo apos um
-- delete (ou anonimizacao LGPD) do alvo — auditoria nao pode sumir.

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_ai_audit_paciente') THEN
        ALTER TABLE public.ai_audit_logs
            ADD CONSTRAINT fk_ai_audit_paciente FOREIGN KEY (paciente_id)
            REFERENCES public.pacientes(id) ON DELETE SET NULL;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_ai_audit_prontuario') THEN
        ALTER TABLE public.ai_audit_logs
            ADD CONSTRAINT fk_ai_audit_prontuario FOREIGN KEY (prontuario_id)
            REFERENCES public.prontuarios(id) ON DELETE SET NULL;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_ai_audit_evolucao') THEN
        ALTER TABLE public.ai_audit_logs
            ADD CONSTRAINT fk_ai_audit_evolucao FOREIGN KEY (evolucao_id)
            REFERENCES public.prontuario_evolucoes(id) ON DELETE SET NULL;
    END IF;
END $$;

-- Item 2.14: ai_rate_limits passa a ser por (usuario, estabelecimento, periodo).
-- A tabela foi criada por 20260429023830_criar_ai_cache_e_rate_limit.sql sem
-- estabelecimento_id; precisamos:
--   1. ADD COLUMN estabelecimento_id NOT NULL DEFAULT 0 (linhas existentes ficam
--      com 0 — sentinela administrativa, sera coletada pelo job de purge).
--   2. DROP UNIQUE antiga (usuario_id, periodo_inicio).
--   3. ADD UNIQUE nova (usuario_id, estabelecimento_id, periodo_inicio).

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'ai_rate_limits'
          AND column_name = 'estabelecimento_id'
    ) THEN
        ALTER TABLE public.ai_rate_limits
            ADD COLUMN estabelecimento_id bigint NOT NULL DEFAULT 0;
    END IF;
END $$;

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'uq_ai_rate_limits_usuario_periodo') THEN
        ALTER TABLE public.ai_rate_limits
            DROP CONSTRAINT uq_ai_rate_limits_usuario_periodo;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'uq_ai_rate_limits_user_estab_periodo') THEN
        ALTER TABLE public.ai_rate_limits
            ADD CONSTRAINT uq_ai_rate_limits_user_estab_periodo
            UNIQUE (usuario_id, estabelecimento_id, periodo_inicio);
    END IF;
END $$;
