DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260429031451_Fase2Wave1Schema') THEN
    ALTER TABLE public.profissionais ADD deletado_em timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260429031451_Fase2Wave1Schema') THEN
    ALTER TABLE public.profissionais ADD deletado_por_usuario_id uuid;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260429031451_Fase2Wave1Schema') THEN
    CREATE TABLE public.categorias_financeiras (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        estabelecimento_id bigint NOT NULL,
        nome character varying(80) NOT NULL,
        tipo character varying(10) NOT NULL,
        padrao boolean NOT NULL,
        ativo boolean NOT NULL,
        criada_em timestamp with time zone NOT NULL,
        atualizada_em timestamp with time zone,
        CONSTRAINT "PK_categorias_financeiras" PRIMARY KEY (id),
        CONSTRAINT fk_categoria_financeira_estabelecimento FOREIGN KEY (estabelecimento_id) REFERENCES public.estabelecimentos (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260429031451_Fase2Wave1Schema') THEN
    CREATE TABLE public.formas_pagamento (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        estabelecimento_id bigint NOT NULL,
        nome character varying(80) NOT NULL,
        padrao boolean NOT NULL,
        ativo boolean NOT NULL,
        criada_em timestamp with time zone NOT NULL,
        atualizada_em timestamp with time zone,
        CONSTRAINT "PK_formas_pagamento" PRIMARY KEY (id),
        CONSTRAINT fk_forma_pagamento_estabelecimento FOREIGN KEY (estabelecimento_id) REFERENCES public.estabelecimentos (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260429031451_Fase2Wave1Schema') THEN
    CREATE TABLE public.idempotency_keys (
        key character varying(80) NOT NULL,
        hash_payload character varying(64) NOT NULL,
        status_code integer NOT NULL,
        response_json text NOT NULL,
        criado_em timestamp with time zone NOT NULL,
        expira_em timestamp with time zone NOT NULL,
        CONSTRAINT "PK_idempotency_keys" PRIMARY KEY (key)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260429031451_Fase2Wave1Schema') THEN
    CREATE TABLE public.profissoes (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        nome character varying(80) NOT NULL,
        conselho_sigla character varying(10),
        ativo boolean NOT NULL DEFAULT TRUE,
        CONSTRAINT "PK_profissoes" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260429031451_Fase2Wave1Schema') THEN
    CREATE TABLE public.especialidades (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        profissao_id bigint NOT NULL,
        nome character varying(120) NOT NULL,
        ativo boolean NOT NULL DEFAULT TRUE,
        CONSTRAINT "PK_especialidades" PRIMARY KEY (id),
        CONSTRAINT fk_especialidades_profissao FOREIGN KEY (profissao_id) REFERENCES public.profissoes (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260429031451_Fase2Wave1Schema') THEN
    CREATE INDEX ix_categoria_financeira_estab_tipo_ativo ON public.categorias_financeiras (estabelecimento_id, tipo, ativo);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260429031451_Fase2Wave1Schema') THEN
    CREATE UNIQUE INDEX uq_categoria_financeira_estab_nome ON public.categorias_financeiras (estabelecimento_id, nome);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260429031451_Fase2Wave1Schema') THEN
    CREATE INDEX ix_especialidades_profissao_ativo ON public.especialidades (profissao_id, ativo);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260429031451_Fase2Wave1Schema') THEN
    CREATE UNIQUE INDEX uq_especialidades_profissao_nome ON public.especialidades (profissao_id, nome);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260429031451_Fase2Wave1Schema') THEN
    CREATE INDEX ix_forma_pagamento_estab_ativo ON public.formas_pagamento (estabelecimento_id, ativo);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260429031451_Fase2Wave1Schema') THEN
    CREATE UNIQUE INDEX uq_forma_pagamento_estab_nome ON public.formas_pagamento (estabelecimento_id, nome);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260429031451_Fase2Wave1Schema') THEN
    CREATE INDEX ix_profissoes_ativo ON public.profissoes (ativo);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260429031451_Fase2Wave1Schema') THEN
    CREATE UNIQUE INDEX uq_profissoes_nome ON public.profissoes (nome);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260429031451_Fase2Wave1Schema') THEN
    INSERT INTO public.__ef_migrations_history ("MigrationId", "ProductVersion")
    VALUES ('20260429031451_Fase2Wave1Schema', '10.0.0');
    END IF;
END $EF$;
