-- Cria public.modelo_permissao_estabelecimento + public.vinculo_profissional_estabelecimento.
-- EF migration: 20260418043823_CreateModelosPermissaoEVinculos
-- Complementos: FKs + unique parcial para eh_padrao + unique parcial para vínculo não-inativo + RLS.

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260418043823_CreateModelosPermissaoEVinculos') THEN

    -- modelo_permissao_estabelecimento -----------------------------------------------------
    CREATE TABLE public.modelo_permissao_estabelecimento (
        id                 bigint GENERATED BY DEFAULT AS IDENTITY,
        estabelecimento_id bigint NOT NULL,
        nome               character varying(100) NOT NULL,
        permissoes         jsonb NOT NULL,
        eh_padrao          boolean NOT NULL,
        criado_em          timestamp with time zone NOT NULL,
        atualizado_em      timestamp with time zone,
        CONSTRAINT "PK_modelo_permissao_estabelecimento" PRIMARY KEY (id)
    );
    CREATE INDEX ix_modelo_permissao_estabelecimento
        ON public.modelo_permissao_estabelecimento (estabelecimento_id);
    CREATE UNIQUE INDEX uq_modelo_permissao_nome_por_estabelecimento
        ON public.modelo_permissao_estabelecimento (estabelecimento_id, nome);
    -- Só 1 modelo "padrão" por estabelecimento.
    CREATE UNIQUE INDEX uq_modelo_permissao_padrao
        ON public.modelo_permissao_estabelecimento (estabelecimento_id)
        WHERE eh_padrao = true;
    ALTER TABLE public.modelo_permissao_estabelecimento
        ADD CONSTRAINT fk_modelo_permissao_estabelecimento
        FOREIGN KEY (estabelecimento_id)
        REFERENCES public.estabelecimentos(id) ON DELETE CASCADE;
    ALTER TABLE public.modelo_permissao_estabelecimento ENABLE ROW LEVEL SECURITY;
    COMMENT ON TABLE public.modelo_permissao_estabelecimento IS
        'Templates de permissões atribuídos a profissionais vinculados a um estabelecimento.';

    -- vinculo_profissional_estabelecimento -------------------------------------------------
    CREATE TABLE public.vinculo_profissional_estabelecimento (
        id                       bigint GENERATED BY DEFAULT AS IDENTITY,
        profissional_usuario_id  uuid NOT NULL,
        estabelecimento_id       bigint NOT NULL,
        modelo_permissao_id      bigint NOT NULL,
        convidado_por_usuario_id uuid NOT NULL,
        status                   character varying(20) NOT NULL,
        convidado_em             timestamp with time zone NOT NULL,
        aceito_em                timestamp with time zone,
        inativado_em             timestamp with time zone,
        CONSTRAINT "PK_vinculo_profissional_estabelecimento" PRIMARY KEY (id)
    );
    CREATE INDEX ix_vinculo_estabelecimento_status
        ON public.vinculo_profissional_estabelecimento (estabelecimento_id, status);
    CREATE INDEX ix_vinculo_profissional_status
        ON public.vinculo_profissional_estabelecimento (profissional_usuario_id, status);

    -- Um usuário só pode ter 1 vínculo ativo/pendente com o mesmo estabelecimento.
    -- Permite múltiplos vínculos inativos (histórico).
    CREATE UNIQUE INDEX uq_vinculo_profissional_estabelecimento_ativo
        ON public.vinculo_profissional_estabelecimento (profissional_usuario_id, estabelecimento_id)
        WHERE status != 'Inativo';

    ALTER TABLE public.vinculo_profissional_estabelecimento
        ADD CONSTRAINT fk_vinculo_usuario
        FOREIGN KEY (profissional_usuario_id)
        REFERENCES public.usuarios(id) ON DELETE CASCADE;
    ALTER TABLE public.vinculo_profissional_estabelecimento
        ADD CONSTRAINT fk_vinculo_estabelecimento
        FOREIGN KEY (estabelecimento_id)
        REFERENCES public.estabelecimentos(id) ON DELETE CASCADE;
    ALTER TABLE public.vinculo_profissional_estabelecimento
        ADD CONSTRAINT fk_vinculo_modelo_permissao
        FOREIGN KEY (modelo_permissao_id)
        REFERENCES public.modelo_permissao_estabelecimento(id) ON DELETE RESTRICT;
    ALTER TABLE public.vinculo_profissional_estabelecimento
        ADD CONSTRAINT fk_vinculo_convidado_por
        FOREIGN KEY (convidado_por_usuario_id)
        REFERENCES public.usuarios(id) ON DELETE RESTRICT;
    ALTER TABLE public.vinculo_profissional_estabelecimento ENABLE ROW LEVEL SECURITY;
    COMMENT ON TABLE public.vinculo_profissional_estabelecimento IS
        'Vínculo profissional×estabelecimento com fluxo Convidado → Ativo → Inativo.';

    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260418043823_CreateModelosPermissaoEVinculos') THEN
    INSERT INTO public.__ef_migrations_history ("MigrationId", "ProductVersion")
    VALUES ('20260418043823_CreateModelosPermissaoEVinculos', '10.0.0');
    END IF;
END $EF$;
