-- ----------------------------------------------------------------------------
-- paciente_acesso_log: audit trail LGPD para acesso a dados de paciente.
--
-- Append-only. Cada GET/PUT/DELETE/EXPORT/ANONIMIZACAO de paciente gera
-- uma linha. NAO eh log de mutacoes (nao reconstroi estado anterior),
-- eh log de quem viu/tocou.
--
-- Indices: paciente+data (consultar historico por paciente),
-- usuario (auditar comportamento por usuario), estab+data (analise temporal).
-- ----------------------------------------------------------------------------

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260503005017_PacienteAcessoLog') THEN
    CREATE TABLE public.paciente_acesso_log (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        paciente_id bigint NOT NULL,
        usuario_id uuid NOT NULL,
        estabelecimento_id bigint NOT NULL,
        tipo_acesso character varying(20) NOT NULL,
        ocorrido_em timestamp with time zone NOT NULL,
        ip_origem character varying(45),
        CONSTRAINT "PK_paciente_acesso_log" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260503005017_PacienteAcessoLog') THEN
    CREATE INDEX ix_paciente_acesso_log_estab_data ON public.paciente_acesso_log (estabelecimento_id, ocorrido_em);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260503005017_PacienteAcessoLog') THEN
    CREATE INDEX ix_paciente_acesso_log_paciente_data ON public.paciente_acesso_log (paciente_id, ocorrido_em);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260503005017_PacienteAcessoLog') THEN
    CREATE INDEX ix_paciente_acesso_log_usuario ON public.paciente_acesso_log (usuario_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260503005017_PacienteAcessoLog') THEN
    INSERT INTO public.__ef_migrations_history ("MigrationId", "ProductVersion")
    VALUES ('20260503005017_PacienteAcessoLog', '10.0.0');
    END IF;
END $EF$;
