
DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260418232458_CriarInventario') THEN
    CREATE TABLE public.itens_inventario (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        estabelecimento_id bigint NOT NULL,
        codigo character varying(50) NOT NULL,
        nome character varying(200) NOT NULL,
        categoria character varying(100) NOT NULL,
        unidade_medida character varying(30) NOT NULL,
        quantidade_atual numeric(12,3) NOT NULL,
        quantidade_minima numeric(12,3) NOT NULL,
        ativo boolean NOT NULL,
        criado_em timestamp with time zone NOT NULL,
        atualizado_em timestamp with time zone,
        CONSTRAINT "PK_itens_inventario" PRIMARY KEY (id),
        CONSTRAINT fk_inventario_estabelecimento FOREIGN KEY (estabelecimento_id) REFERENCES public.estabelecimentos (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260418232458_CriarInventario') THEN
    CREATE TABLE public.movimentacoes_estoque (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        item_inventario_id bigint NOT NULL,
        estabelecimento_id bigint NOT NULL,
        tipo character varying(20) NOT NULL,
        quantidade numeric(12,3) NOT NULL,
        quantidade_anterior numeric(12,3) NOT NULL,
        quantidade_apos numeric(12,3) NOT NULL,
        observacao character varying(500),
        criado_por_usuario_id uuid NOT NULL,
        criado_em timestamp with time zone NOT NULL,
        CONSTRAINT "PK_movimentacoes_estoque" PRIMARY KEY (id),
        CONSTRAINT fk_movimentacao_estabelecimento FOREIGN KEY (estabelecimento_id) REFERENCES public.estabelecimentos (id) ON DELETE RESTRICT,
        CONSTRAINT fk_movimentacao_item_inventario FOREIGN KEY (item_inventario_id) REFERENCES public.itens_inventario (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260418232458_CriarInventario') THEN
    CREATE INDEX ix_inventario_estab_ativo ON public.itens_inventario (estabelecimento_id, ativo);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260418232458_CriarInventario') THEN
    CREATE UNIQUE INDEX uq_inventario_codigo_por_estab ON public.itens_inventario (estabelecimento_id, codigo);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260418232458_CriarInventario') THEN
    CREATE INDEX ix_movimentacao_estab_data ON public.movimentacoes_estoque (estabelecimento_id, criado_em);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260418232458_CriarInventario') THEN
    CREATE INDEX ix_movimentacao_item_data ON public.movimentacoes_estoque (item_inventario_id, criado_em);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260418232458_CriarInventario') THEN
    INSERT INTO public.__ef_migrations_history ("MigrationId", "ProductVersion")
    VALUES ('20260418232458_CriarInventario', '10.0.0');
    END IF;
END $EF$;

