-- Hardening Fase 1 — schema (itens 1.1, 1.4 e 1.7 de Docs/01_FASE_1_HARDENING.md)
--
-- Consolida em uma única migration EF as três alterações de schema:
--   1.1 Custo médio ponderado (itens_inventario.custo_medio,
--       movimentacoes_estoque.custo_unitario / custo_total).
--   1.4 Auditoria + soft delete (audit_delete_attempts +
--       deletado_em / deletado_por_usuario_id em prontuarios,
--       prontuario_evolucoes, prontuario_anexos, movimentacoes_estoque;
--       pacientes já tinha desde a migration original).
--   1.7 Auditoria de IA (ai_audit_logs).
--
-- Decisão: EF detecta todas as alterações de configuration ao mesmo tempo
-- e gera uma única migration consolidada. Tentar dividir artificialmente
-- exigiria editar o snapshot manualmente entre migrations — fragil e
-- fora do fluxo idiomático do EF Core. Mantemos o agrupamento por fase.
--
-- As tabelas ai_outputs_cache e ai_rate_limits NÃO têm aggregate EF
-- (são acessadas via Dapper); são criadas em arquivo separado:
--   20260429023830_criar_ai_cache_e_rate_limit.sql
--
-- Pendente: RLS policies para ai_audit_logs, audit_delete_attempts,
-- ai_outputs_cache, ai_rate_limits. Será endereçado em sprint dedicada
-- de RLS na Fase 2.

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260429023829_HardeningFase1Schema') THEN
    ALTER TABLE public.prontuarios ADD deletado_em timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260429023829_HardeningFase1Schema') THEN
    ALTER TABLE public.prontuarios ADD deletado_por_usuario_id uuid;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260429023829_HardeningFase1Schema') THEN
    ALTER TABLE public.prontuario_evolucoes ADD deletado_em timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260429023829_HardeningFase1Schema') THEN
    ALTER TABLE public.prontuario_evolucoes ADD deletado_por_usuario_id uuid;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260429023829_HardeningFase1Schema') THEN
    ALTER TABLE public.prontuario_anexos ADD deletado_em timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260429023829_HardeningFase1Schema') THEN
    ALTER TABLE public.prontuario_anexos ADD deletado_por_usuario_id uuid;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260429023829_HardeningFase1Schema') THEN
    ALTER TABLE public.movimentacoes_estoque ADD custo_total numeric(18,4) NOT NULL DEFAULT 0.0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260429023829_HardeningFase1Schema') THEN
    ALTER TABLE public.movimentacoes_estoque ADD custo_unitario numeric(18,4) NOT NULL DEFAULT 0.0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260429023829_HardeningFase1Schema') THEN
    ALTER TABLE public.movimentacoes_estoque ADD deletado_em timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260429023829_HardeningFase1Schema') THEN
    ALTER TABLE public.movimentacoes_estoque ADD deletado_por_usuario_id uuid;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260429023829_HardeningFase1Schema') THEN
    ALTER TABLE public.itens_inventario ADD custo_medio numeric(18,4) NOT NULL DEFAULT 0.0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260429023829_HardeningFase1Schema') THEN
    CREATE TABLE public.ai_audit_logs (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        usuario_id uuid NOT NULL,
        estabelecimento_id bigint NOT NULL,
        prompt_hash character varying(64) NOT NULL,
        response_hash character varying(64),
        tokens_in integer,
        tokens_out integer,
        modelo character varying(80) NOT NULL,
        endpoint character varying(80) NOT NULL,
        duracao_ms integer,
        sucesso boolean NOT NULL,
        erro_mensagem character varying(500),
        criado_em timestamp with time zone NOT NULL,
        CONSTRAINT "PK_ai_audit_logs" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260429023829_HardeningFase1Schema') THEN
    CREATE TABLE public.audit_delete_attempts (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        tabela character varying(80) NOT NULL,
        registro_id character varying(80) NOT NULL,
        estabelecimento_id bigint,
        usuario_id uuid,
        motivo character varying(500),
        tentado_em timestamp with time zone NOT NULL,
        CONSTRAINT "PK_audit_delete_attempts" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260429023829_HardeningFase1Schema') THEN
    CREATE INDEX ix_ai_audit_estab_data ON public.ai_audit_logs (estabelecimento_id, criado_em DESC);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260429023829_HardeningFase1Schema') THEN
    CREATE INDEX ix_ai_audit_usuario_data ON public.ai_audit_logs (usuario_id, criado_em DESC);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260429023829_HardeningFase1Schema') THEN
    CREATE INDEX ix_audit_delete_estab_data ON public.audit_delete_attempts (estabelecimento_id, tentado_em DESC);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260429023829_HardeningFase1Schema') THEN
    CREATE INDEX ix_audit_delete_tabela_data ON public.audit_delete_attempts (tabela, tentado_em DESC);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260429023829_HardeningFase1Schema') THEN
    INSERT INTO public.__ef_migrations_history ("MigrationId", "ProductVersion")
    VALUES ('20260429023829_HardeningFase1Schema', '10.0.0');
    END IF;
END $EF$;
