-- Tabela de pacientes — escopada por estabelecimento (multi-tenant).
-- EF migration: 20260418153650_CreatePacientes
-- Complementos: FK para estabelecimentos, RLS habilitado.

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260418153650_CreatePacientes') THEN

    CREATE TABLE public.pacientes (
        id                      bigint GENERATED BY DEFAULT AS IDENTITY,
        estabelecimento_id      bigint NOT NULL,
        nome_completo           character varying(200) NOT NULL,
        cpf                     character varying(11),
        data_nascimento         date,
        genero                  character varying(20) NOT NULL,
        telefone                character varying(20),
        email                   character varying(320),
        endereco                character varying(500),
        observacoes             character varying(2000),
        criado_em               timestamp with time zone NOT NULL,
        atualizado_em           timestamp with time zone,
        deletado_em             timestamp with time zone,
        deletado_por_usuario_id uuid,
        CONSTRAINT "PK_pacientes" PRIMARY KEY (id)
    );

    CREATE INDEX ix_pacientes_estabelecimento
        ON public.pacientes (estabelecimento_id, deletado_em);

    -- CPF único apenas dentro do mesmo estabelecimento ativo (o mesmo CPF pode existir em outros tenants).
    CREATE UNIQUE INDEX uq_pacientes_estabelecimento_cpf
        ON public.pacientes (estabelecimento_id, cpf)
        WHERE cpf IS NOT NULL AND deletado_em IS NULL;

    ALTER TABLE public.pacientes
        ADD CONSTRAINT fk_pacientes_estabelecimento
        FOREIGN KEY (estabelecimento_id)
        REFERENCES public.estabelecimentos(id) ON DELETE RESTRICT;

    ALTER TABLE public.pacientes ENABLE ROW LEVEL SECURITY;

    COMMENT ON TABLE public.pacientes IS
        'Pacientes multi-tenant (escopados por estabelecimento). Dados sensíveis de saúde (LGPD Art. 5º II).';

    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260418153650_CreatePacientes') THEN
    INSERT INTO public.__ef_migrations_history ("MigrationId", "ProductVersion")
    VALUES ('20260418153650_CreatePacientes', '10.0.0');
    END IF;
END $EF$;
