-- Agendamentos de pacientes por estabelecimento.
-- EF migration: 20260418230100_CreateAgendamentos

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260418230100_CreateAgendamentos') THEN
    CREATE TABLE public.agendamentos (
        id                      bigint GENERATED BY DEFAULT AS IDENTITY,
        estabelecimento_id      bigint NOT NULL,
        paciente_id             bigint NOT NULL,
        profissional_usuario_id uuid NOT NULL,
        criado_por_usuario_id   uuid NOT NULL,
        inicio_previsto         timestamp with time zone NOT NULL,
        fim_previsto            timestamp with time zone NOT NULL,
        tipo_servico            character varying(100) NOT NULL,
        observacoes             character varying(1000),
        status                  character varying(20) NOT NULL,
        motivo_cancelamento     character varying(500),
        criado_em               timestamp with time zone NOT NULL,
        atualizado_em           timestamp with time zone,
        CONSTRAINT "PK_agendamentos" PRIMARY KEY (id),
        CONSTRAINT fk_agendamento_estabelecimento
            FOREIGN KEY (estabelecimento_id) REFERENCES public.estabelecimentos (id) ON DELETE RESTRICT,
        CONSTRAINT fk_agendamento_paciente
            FOREIGN KEY (paciente_id) REFERENCES public.pacientes (id) ON DELETE RESTRICT
    );
    CREATE INDEX ix_agendamentos_estab_inicio
        ON public.agendamentos (estabelecimento_id, inicio_previsto);
    CREATE INDEX ix_agendamentos_paciente_inicio
        ON public.agendamentos (paciente_id, inicio_previsto);
    CREATE INDEX ix_agendamentos_prof_inicio
        ON public.agendamentos (profissional_usuario_id, inicio_previsto);

    ALTER TABLE public.agendamentos ENABLE ROW LEVEL SECURITY;

    COMMENT ON TABLE public.agendamentos IS
        'Agendamentos de consultas/procedimentos; multi-tenant por estabelecimento_id.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260418230100_CreateAgendamentos') THEN
    INSERT INTO public.__ef_migrations_history ("MigrationId", "ProductVersion")
    VALUES ('20260418230100_CreateAgendamentos', '10.0.0');
    END IF;
END $EF$;
