-- ============================================================
-- Lista de espera de agendamento.
--
-- Tabela `lista_espera_agendamento` — pacientes com interesse em ser atendidos
-- mas sem horário fixo agendado. Podem ser "encaixados" depois quando surgir
-- uma vaga (cancelamento ou slot livre).
-- ============================================================

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260501024052_AddListaEsperaAgendamento') THEN
    CREATE TABLE public.lista_espera_agendamento (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        estabelecimento_id bigint NOT NULL,
        paciente_id bigint NOT NULL,
        motivo character varying(200) NOT NULL,
        profissional_preferido_id uuid,
        criado_por_usuario_id uuid NOT NULL,
        criado_em timestamp with time zone NOT NULL,
        atendido_em timestamp with time zone,
        atendido_por_agendamento_id bigint,
        CONSTRAINT "PK_lista_espera_agendamento" PRIMARY KEY (id),
        CONSTRAINT fk_lista_espera_estabelecimento FOREIGN KEY (estabelecimento_id) REFERENCES public.estabelecimentos (id) ON DELETE CASCADE,
        CONSTRAINT fk_lista_espera_paciente FOREIGN KEY (paciente_id) REFERENCES public.pacientes (id) ON DELETE RESTRICT,
        CONSTRAINT fk_lista_espera_agendamento FOREIGN KEY (atendido_por_agendamento_id) REFERENCES public.agendamentos (id) ON DELETE SET NULL
    );

    CREATE INDEX ix_lista_espera_estab_atendido ON public.lista_espera_agendamento (estabelecimento_id, atendido_em);

    INSERT INTO public.__ef_migrations_history ("MigrationId", "ProductVersion")
    VALUES ('20260501024052_AddListaEsperaAgendamento', '10.0.0');
    END IF;
END $EF$;

-- RLS
DO $$
BEGIN
    EXECUTE 'ALTER TABLE public.lista_espera_agendamento ENABLE ROW LEVEL SECURITY';
    EXECUTE 'ALTER TABLE public.lista_espera_agendamento FORCE ROW LEVEL SECURITY';
    DROP POLICY IF EXISTS lista_espera_select_tenant ON public.lista_espera_agendamento;
    EXECUTE $p$
        CREATE POLICY lista_espera_select_tenant
            ON public.lista_espera_agendamento
            FOR SELECT
            TO authenticated
            USING (
                estabelecimento_id IN (
                    SELECT v.estabelecimento_id
                    FROM public.vinculo_profissional_estabelecimento v
                    WHERE v.profissional_usuario_id = auth.uid()
                      AND v.status = 'Ativo'
                )
                OR estabelecimento_id IN (
                    SELECT e.id
                    FROM public.estabelecimentos e
                    WHERE e.dono_usuario_id = auth.uid()
                )
            );
    $p$;
END $$;
