-- Fase 3 — Dominio Clinico (consolidado).
--
-- Itens cobertos:
--   3.1 Receitas (receitas, receita_itens, receitas_configuracao_estabelecimento, medicamentos_favoritos)
--   3.2 Exame fisico (exame_fisico, exame_fisico_regioes)
--   3.3.A Procedimento cirurgico (procedimentos_cirurgicos, equipe_cirurgica)
--   3.3.B Orcamento completo (ALTER orcamentos + orcamento_equipe / _implantes / _formas_pagamento)
--   3.4 Permissao fina (ALTER modelo_permissao_estabelecimento.permissoes_extras + backfill Admin/Medico)
--
-- Script gerado a partir da migration EF 20260429171108_Fase3Schema (--idempotent).
-- BEGIN/COMMIT removidos: o supabase CLI gerencia a transacao.
--
-- O bloco final faz BACKFILL dos modelos padrao Admin / Medico com a permissao
-- 'ia_assistente_clinico' — sem isso, modelos pre-existentes ficariam sem acesso
-- ao IA Assistente Clinico (bloqueador funcional).

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260429171108_Fase3Schema') THEN
    ALTER TABLE public.orcamentos ADD config_pagamento_json jsonb;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260429171108_Fase3Schema') THEN
    ALTER TABLE public.orcamentos ADD custo_implantes_total numeric(12,2) NOT NULL DEFAULT 0.0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260429171108_Fase3Schema') THEN
    ALTER TABLE public.orcamentos ADD procedimento_cirurgico_id bigint;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260429171108_Fase3Schema') THEN
    ALTER TABLE public.orcamentos ADD tipo character varying(20) NOT NULL DEFAULT 'Simples';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260429171108_Fase3Schema') THEN
    ALTER TABLE public.modelo_permissao_estabelecimento ADD permissoes_extras jsonb NOT NULL DEFAULT ('[]'::jsonb);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260429171108_Fase3Schema') THEN
    CREATE TABLE public.exame_fisico (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        evolucao_id bigint NOT NULL,
        prontuario_id bigint NOT NULL,
        paciente_id bigint NOT NULL,
        estabelecimento_id bigint NOT NULL,
        realizado_em timestamp with time zone NOT NULL,
        realizado_por_usuario_id uuid NOT NULL,
        dados_gerais_json jsonb,
        observacoes_gerais character varying(2000),
        criado_em timestamp with time zone NOT NULL,
        atualizado_em timestamp with time zone,
        deletado_em timestamp with time zone,
        deletado_por_usuario_id uuid,
        CONSTRAINT "PK_exame_fisico" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260429171108_Fase3Schema') THEN
    CREATE TABLE public.medicamentos_favoritos (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        profissional_usuario_id uuid NOT NULL,
        estabelecimento_id bigint NOT NULL,
        medicamento character varying(200) NOT NULL,
        posologia character varying(500),
        via_administracao character varying(40),
        uso_count integer NOT NULL DEFAULT 0,
        ultimo_uso timestamp with time zone,
        criado_em timestamp with time zone NOT NULL,
        CONSTRAINT "PK_medicamentos_favoritos" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260429171108_Fase3Schema') THEN
    CREATE TABLE public.orcamento_equipe (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        orcamento_id bigint NOT NULL,
        profissional_usuario_id uuid NOT NULL,
        papel character varying(40) NOT NULL,
        valor numeric(12,2) NOT NULL,
        ordem integer NOT NULL,
        CONSTRAINT "PK_orcamento_equipe" PRIMARY KEY (id),
        CONSTRAINT fk_orcamento_equipe_orcamento FOREIGN KEY (orcamento_id) REFERENCES public.orcamentos (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260429171108_Fase3Schema') THEN
    CREATE TABLE public.orcamento_formas_pagamento (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        orcamento_id bigint NOT NULL,
        forma_pagamento_id bigint NOT NULL,
        valor numeric(12,2) NOT NULL,
        parcelas integer NOT NULL,
        observacao character varying(200),
        ordem integer NOT NULL,
        CONSTRAINT "PK_orcamento_formas_pagamento" PRIMARY KEY (id),
        CONSTRAINT fk_orcamento_forma_pagamento_forma FOREIGN KEY (forma_pagamento_id) REFERENCES public.formas_pagamento (id) ON DELETE RESTRICT,
        CONSTRAINT fk_orcamento_forma_pagamento_orcamento FOREIGN KEY (orcamento_id) REFERENCES public.orcamentos (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260429171108_Fase3Schema') THEN
    CREATE TABLE public.orcamento_implantes (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        orcamento_id bigint NOT NULL,
        item_inventario_id bigint,
        descricao character varying(200) NOT NULL,
        quantidade numeric(12,3) NOT NULL,
        custo_unitario numeric(18,4) NOT NULL,
        custo_total numeric(18,4) NOT NULL,
        CONSTRAINT "PK_orcamento_implantes" PRIMARY KEY (id),
        CONSTRAINT fk_orcamento_implante_item_inventario FOREIGN KEY (item_inventario_id) REFERENCES public.itens_inventario (id) ON DELETE SET NULL,
        CONSTRAINT fk_orcamento_implante_orcamento FOREIGN KEY (orcamento_id) REFERENCES public.orcamentos (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260429171108_Fase3Schema') THEN
    CREATE TABLE public.procedimentos_cirurgicos (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        paciente_id bigint NOT NULL,
        prontuario_id bigint NOT NULL,
        estabelecimento_id bigint NOT NULL,
        agendamento_id bigint,
        data_agendada timestamp with time zone,
        data_realizada timestamp with time zone,
        status character varying(20) NOT NULL,
        cirurgia_principal character varying(200) NOT NULL,
        cirurgia_codigo character varying(40),
        descricao_cirurgica text,
        ficha_anestesica jsonb,
        evolucao_pos_op text,
        observacoes character varying(2000),
        cancelado_em timestamp with time zone,
        motivo_cancelamento character varying(500),
        deletado_em timestamp with time zone,
        deletado_por_usuario_id uuid,
        criado_em timestamp with time zone NOT NULL,
        atualizado_em timestamp with time zone,
        CONSTRAINT "PK_procedimentos_cirurgicos" PRIMARY KEY (id),
        CONSTRAINT fk_procedimento_agendamento FOREIGN KEY (agendamento_id) REFERENCES public.agendamentos (id) ON DELETE SET NULL,
        CONSTRAINT fk_procedimento_estabelecimento FOREIGN KEY (estabelecimento_id) REFERENCES public.estabelecimentos (id) ON DELETE RESTRICT,
        CONSTRAINT fk_procedimento_paciente FOREIGN KEY (paciente_id) REFERENCES public.pacientes (id) ON DELETE RESTRICT,
        CONSTRAINT fk_procedimento_prontuario FOREIGN KEY (prontuario_id) REFERENCES public.prontuarios (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260429171108_Fase3Schema') THEN
    CREATE TABLE public.receitas (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        prontuario_id bigint NOT NULL,
        paciente_id bigint NOT NULL,
        profissional_usuario_id uuid NOT NULL,
        estabelecimento_id bigint NOT NULL,
        tipo character varying(30) NOT NULL,
        emitida_em timestamp with time zone NOT NULL,
        validade_ate timestamp with time zone,
        observacoes character varying(2000),
        status character varying(20) NOT NULL,
        cancelada_em timestamp with time zone,
        motivo_cancelamento character varying(500),
        criada_em timestamp with time zone NOT NULL,
        atualizada_em timestamp with time zone,
        deletado_em timestamp with time zone,
        deletado_por_usuario_id uuid,
        CONSTRAINT "PK_receitas" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260429171108_Fase3Schema') THEN
    CREATE TABLE public.receitas_configuracao_estabelecimento (
        estabelecimento_id bigint NOT NULL,
        cabecalho_html text,
        rodape_html text,
        modelo_padrao_id bigint,
        emissor_padrao character varying(80),
        atualizada_em timestamp with time zone,
        CONSTRAINT "PK_receitas_configuracao_estabelecimento" PRIMARY KEY (estabelecimento_id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260429171108_Fase3Schema') THEN
    CREATE TABLE public.exame_fisico_regioes (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        exame_fisico_id bigint NOT NULL,
        regiao_codigo character varying(60) NOT NULL,
        regiao_pai_codigo character varying(60),
        lateralidade character varying(20) NOT NULL,
        achados character varying(2000),
        severidade character varying(20),
        ordem integer NOT NULL DEFAULT 0,
        CONSTRAINT "PK_exame_fisico_regioes" PRIMARY KEY (id),
        CONSTRAINT "FK_exame_fisico_regioes_exame_fisico_exame_fisico_id" FOREIGN KEY (exame_fisico_id) REFERENCES public.exame_fisico (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260429171108_Fase3Schema') THEN
    CREATE TABLE public.equipe_cirurgica (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        procedimento_id bigint NOT NULL,
        profissional_usuario_id uuid NOT NULL,
        papel character varying(40) NOT NULL,
        ordem integer NOT NULL,
        CONSTRAINT "PK_equipe_cirurgica" PRIMARY KEY (id),
        CONSTRAINT fk_membro_equipe_cirurgica_procedimento FOREIGN KEY (procedimento_id) REFERENCES public.procedimentos_cirurgicos (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260429171108_Fase3Schema') THEN
    CREATE TABLE public.receita_itens (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        receita_id bigint NOT NULL,
        ordem integer NOT NULL,
        medicamento character varying(200) NOT NULL,
        posologia character varying(500) NOT NULL,
        quantidade character varying(80),
        via_administracao character varying(40),
        observacao character varying(500),
        CONSTRAINT "PK_receita_itens" PRIMARY KEY (id),
        CONSTRAINT "FK_receita_itens_receitas_receita_id" FOREIGN KEY (receita_id) REFERENCES public.receitas (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260429171108_Fase3Schema') THEN
    CREATE INDEX ix_orcamento_procedimento_cirurgico ON public.orcamentos (procedimento_cirurgico_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260429171108_Fase3Schema') THEN
    CREATE INDEX ix_equipe_cirurgica_procedimento_papel ON public.equipe_cirurgica (procedimento_id, papel);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260429171108_Fase3Schema') THEN
    CREATE UNIQUE INDEX uq_equipe_cirurgica_procedimento_profissional_papel ON public.equipe_cirurgica (procedimento_id, profissional_usuario_id, papel);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260429171108_Fase3Schema') THEN
    CREATE INDEX ix_exame_fisico_estabelecimento ON public.exame_fisico (estabelecimento_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260429171108_Fase3Schema') THEN
    CREATE INDEX ix_exame_fisico_evolucao ON public.exame_fisico (evolucao_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260429171108_Fase3Schema') THEN
    CREATE INDEX ix_exame_fisico_paciente_realizado ON public.exame_fisico (paciente_id, realizado_em DESC);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260429171108_Fase3Schema') THEN
    CREATE INDEX ix_exame_fisico_prontuario_realizado ON public.exame_fisico (prontuario_id, realizado_em DESC);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260429171108_Fase3Schema') THEN
    CREATE UNIQUE INDEX ux_exame_fisico_regiao_codigo ON public.exame_fisico_regioes (exame_fisico_id, regiao_codigo);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260429171108_Fase3Schema') THEN
    CREATE INDEX ix_medicamentos_favoritos_ranking ON public.medicamentos_favoritos (profissional_usuario_id, estabelecimento_id, uso_count DESC);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260429171108_Fase3Schema') THEN
    CREATE UNIQUE INDEX uq_medicamentos_favoritos_chave ON public.medicamentos_favoritos (profissional_usuario_id, estabelecimento_id, medicamento, posologia);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260429171108_Fase3Schema') THEN
    CREATE UNIQUE INDEX uq_orcamento_equipe_orcamento_profissional_papel ON public.orcamento_equipe (orcamento_id, profissional_usuario_id, papel);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260429171108_Fase3Schema') THEN
    CREATE INDEX ix_orcamento_forma_pagamento_orcamento ON public.orcamento_formas_pagamento (orcamento_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260429171108_Fase3Schema') THEN
    CREATE INDEX "IX_orcamento_formas_pagamento_forma_pagamento_id" ON public.orcamento_formas_pagamento (forma_pagamento_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260429171108_Fase3Schema') THEN
    CREATE INDEX ix_orcamento_implante_orcamento ON public.orcamento_implantes (orcamento_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260429171108_Fase3Schema') THEN
    CREATE INDEX "IX_orcamento_implantes_item_inventario_id" ON public.orcamento_implantes (item_inventario_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260429171108_Fase3Schema') THEN
    CREATE INDEX ix_procedimento_estab_data_agendada ON public.procedimentos_cirurgicos (estabelecimento_id, data_agendada);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260429171108_Fase3Schema') THEN
    CREATE INDEX ix_procedimento_paciente_data_realizada ON public.procedimentos_cirurgicos (paciente_id, data_realizada DESC);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260429171108_Fase3Schema') THEN
    CREATE INDEX "IX_procedimentos_cirurgicos_agendamento_id" ON public.procedimentos_cirurgicos (agendamento_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260429171108_Fase3Schema') THEN
    CREATE INDEX "IX_procedimentos_cirurgicos_prontuario_id" ON public.procedimentos_cirurgicos (prontuario_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260429171108_Fase3Schema') THEN
    CREATE INDEX ix_receita_itens_receita_ordem ON public.receita_itens (receita_id, ordem);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260429171108_Fase3Schema') THEN
    CREATE INDEX ix_receitas_estab_prof_emitida ON public.receitas (estabelecimento_id, profissional_usuario_id, emitida_em DESC);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260429171108_Fase3Schema') THEN
    CREATE INDEX ix_receitas_paciente_emitida ON public.receitas (paciente_id, emitida_em DESC);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260429171108_Fase3Schema') THEN
    ALTER TABLE public.orcamentos ADD CONSTRAINT fk_orcamento_procedimento_cirurgico FOREIGN KEY (procedimento_cirurgico_id) REFERENCES public.procedimentos_cirurgicos (id) ON DELETE SET NULL;
    END IF;
END $EF$;

-- ---------------------------------------------------------------------
-- Backfill — Item 3.4: ativa 'ia_assistente_clinico' nos modelos padrao
-- 'Admin' e 'Medico' que ja existiam antes desta migration. Idempotente:
-- so atualiza linhas com permissoes_extras vazia.
-- ---------------------------------------------------------------------
DO $$
BEGIN
    UPDATE public.modelo_permissao_estabelecimento
    SET permissoes_extras = '["ia_assistente_clinico"]'::jsonb
    WHERE eh_padrao = true
      AND nome IN ('Admin', 'Médico')
      AND (permissoes_extras IS NULL OR permissoes_extras = '[]'::jsonb);
END $$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260429171108_Fase3Schema') THEN
    INSERT INTO public.__ef_migrations_history ("MigrationId", "ProductVersion")
    VALUES ('20260429171108_Fase3Schema', '10.0.0');
    END IF;
END $EF$;
