-- Cria a tabela public.unidades_estabelecimento (matriz/filial).
-- EF migration: 20260425044739_CriarUnidadesEstabelecimento
-- Complementos: RLS enabled sem policies (defense-in-depth — backend controla via aggregate).

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260425044739_CriarUnidadesEstabelecimento') THEN
    CREATE TABLE public.unidades_estabelecimento (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        estabelecimento_id bigint NOT NULL,
        nome character varying(200) NOT NULL,
        is_principal boolean NOT NULL,
        cep character varying(8),
        logradouro character varying(200),
        numero character varying(20),
        complemento character varying(100),
        bairro character varying(100),
        cidade character varying(100),
        estado character varying(2),
        telefone character varying(20),
        ativo boolean NOT NULL,
        criado_em timestamp with time zone NOT NULL,
        atualizado_em timestamp with time zone,
        CONSTRAINT "PK_unidades_estabelecimento" PRIMARY KEY (id),
        CONSTRAINT fk_unidades_estabelecimento FOREIGN KEY (estabelecimento_id) REFERENCES public.estabelecimentos (id) ON DELETE CASCADE
    );

    ALTER TABLE public.unidades_estabelecimento ENABLE ROW LEVEL SECURITY;

    COMMENT ON TABLE public.unidades_estabelecimento IS
        'Unidades físicas (matriz/filial) do estabelecimento. RLS negativo — acesso só via backend.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260425044739_CriarUnidadesEstabelecimento') THEN
    CREATE INDEX ix_unidades_estab ON public.unidades_estabelecimento (estabelecimento_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260425044739_CriarUnidadesEstabelecimento') THEN
    CREATE UNIQUE INDEX uq_unidades_principal_por_estab ON public.unidades_estabelecimento (estabelecimento_id) WHERE is_principal = true;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260425044739_CriarUnidadesEstabelecimento') THEN
    INSERT INTO public.__ef_migrations_history ("MigrationId", "ProductVersion")
    VALUES ('20260425044739_CriarUnidadesEstabelecimento', '10.0.0');
    END IF;
END $EF$;
