-- ============================================================
-- Fase 6.1 — Catálogos de orçamento (settings).
--
-- 6 novas tabelas (todas tenant-scoped por estabelecimento_id):
--   - orcamento_catalogo_cirurgia        (cirurgias com valor base + duração padrão)
--   - orcamento_valor_profissional       (tabela de honorários por tempo)
--   - orcamento_configuracao_local_cirurgia (1 linha por tipo de internação)
--   - orcamento_catalogo_equipe          (equipes especializadas)
--   - orcamento_catalogo_implante        (catálogo de implantes — FK opcional p/ inventário)
--   - orcamento_configuracao_pagamento   (acréscimo % + entrada padrão por forma)
--
-- Idempotente: usa DO $EF$ blocks gerados pelo `dotnet ef migrations script --idempotent`.
-- ============================================================

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260430123214_Fase6_1OrcamentoCatalogos') THEN
    CREATE TABLE public.orcamento_catalogo_cirurgia (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        estabelecimento_id bigint NOT NULL,
        descricao character varying(200) NOT NULL,
        valor_base numeric(12,2) NOT NULL,
        duracao_padrao_minutos integer,
        ativo boolean NOT NULL DEFAULT TRUE,
        criada_em timestamp with time zone NOT NULL,
        atualizada_em timestamp with time zone,
        CONSTRAINT "PK_orcamento_catalogo_cirurgia" PRIMARY KEY (id),
        CONSTRAINT fk_catalogo_cirurgia_estabelecimento FOREIGN KEY (estabelecimento_id) REFERENCES public.estabelecimentos (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260430123214_Fase6_1OrcamentoCatalogos') THEN
    CREATE TABLE public.orcamento_catalogo_equipe (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        estabelecimento_id bigint NOT NULL,
        descricao character varying(200) NOT NULL,
        valor_padrao numeric(12,2) NOT NULL,
        ativo boolean NOT NULL DEFAULT TRUE,
        criada_em timestamp with time zone NOT NULL,
        atualizada_em timestamp with time zone,
        CONSTRAINT "PK_orcamento_catalogo_equipe" PRIMARY KEY (id),
        CONSTRAINT fk_catalogo_equipe_estabelecimento FOREIGN KEY (estabelecimento_id) REFERENCES public.estabelecimentos (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260430123214_Fase6_1OrcamentoCatalogos') THEN
    CREATE TABLE public.orcamento_catalogo_implante (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        estabelecimento_id bigint NOT NULL,
        item_inventario_id bigint,
        descricao character varying(200) NOT NULL,
        custo_unitario numeric(12,2) NOT NULL,
        ativo boolean NOT NULL DEFAULT TRUE,
        criada_em timestamp with time zone NOT NULL,
        atualizada_em timestamp with time zone,
        CONSTRAINT "PK_orcamento_catalogo_implante" PRIMARY KEY (id),
        CONSTRAINT fk_catalogo_implante_estabelecimento FOREIGN KEY (estabelecimento_id) REFERENCES public.estabelecimentos (id) ON DELETE CASCADE,
        CONSTRAINT fk_catalogo_implante_item_inventario FOREIGN KEY (item_inventario_id) REFERENCES public.itens_inventario (id) ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260430123214_Fase6_1OrcamentoCatalogos') THEN
    CREATE TABLE public.orcamento_configuracao_local_cirurgia (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        estabelecimento_id bigint NOT NULL,
        tipo_internacao character varying(20) NOT NULL,
        tempo_base_minutos integer NOT NULL,
        valor_base numeric(12,2) NOT NULL,
        tempo_adicional_minutos integer NOT NULL,
        valor_adicional numeric(12,2) NOT NULL,
        criada_em timestamp with time zone NOT NULL,
        atualizada_em timestamp with time zone,
        CONSTRAINT "PK_orcamento_configuracao_local_cirurgia" PRIMARY KEY (id),
        CONSTRAINT fk_config_local_cirurgia_estabelecimento FOREIGN KEY (estabelecimento_id) REFERENCES public.estabelecimentos (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260430123214_Fase6_1OrcamentoCatalogos') THEN
    CREATE TABLE public.orcamento_configuracao_pagamento (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        estabelecimento_id bigint NOT NULL,
        forma_pagamento_id bigint NOT NULL,
        acrescimo_percentual numeric(5,2) NOT NULL,
        entrada_percentual_padrao numeric(5,2) NOT NULL,
        taxa_parcela numeric(7,4) NOT NULL,
        parcelas_maximas integer NOT NULL,
        ativo boolean NOT NULL DEFAULT TRUE,
        criada_em timestamp with time zone NOT NULL,
        atualizada_em timestamp with time zone,
        CONSTRAINT "PK_orcamento_configuracao_pagamento" PRIMARY KEY (id),
        CONSTRAINT fk_config_pgto_estabelecimento FOREIGN KEY (estabelecimento_id) REFERENCES public.estabelecimentos (id) ON DELETE CASCADE,
        CONSTRAINT fk_config_pgto_forma_pagamento FOREIGN KEY (forma_pagamento_id) REFERENCES public.formas_pagamento (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260430123214_Fase6_1OrcamentoCatalogos') THEN
    CREATE TABLE public.orcamento_valor_profissional (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        estabelecimento_id bigint NOT NULL,
        profissional_usuario_id uuid,
        funcao character varying(60) NOT NULL,
        tempo_base_minutos integer NOT NULL,
        valor_tempo_base numeric(12,2) NOT NULL,
        tempo_adicional_minutos integer NOT NULL,
        valor_adicional numeric(12,2) NOT NULL,
        valor_plus numeric(12,2) NOT NULL,
        ativo boolean NOT NULL DEFAULT TRUE,
        criada_em timestamp with time zone NOT NULL,
        atualizada_em timestamp with time zone,
        CONSTRAINT "PK_orcamento_valor_profissional" PRIMARY KEY (id),
        CONSTRAINT fk_valor_prof_orc_estabelecimento FOREIGN KEY (estabelecimento_id) REFERENCES public.estabelecimentos (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260430123214_Fase6_1OrcamentoCatalogos') THEN
    CREATE INDEX ix_catalogo_cirurgia_estab_ativo ON public.orcamento_catalogo_cirurgia (estabelecimento_id, ativo);
    CREATE INDEX ix_catalogo_equipe_estab_ativo ON public.orcamento_catalogo_equipe (estabelecimento_id, ativo);
    CREATE INDEX ix_catalogo_implante_estab_ativo ON public.orcamento_catalogo_implante (estabelecimento_id, ativo);
    CREATE INDEX "IX_orcamento_catalogo_implante_item_inventario_id" ON public.orcamento_catalogo_implante (item_inventario_id);
    CREATE UNIQUE INDEX uq_config_local_estab_tipo ON public.orcamento_configuracao_local_cirurgia (estabelecimento_id, tipo_internacao);
    CREATE INDEX "IX_orcamento_configuracao_pagamento_forma_pagamento_id" ON public.orcamento_configuracao_pagamento (forma_pagamento_id);
    CREATE UNIQUE INDEX uq_config_pgto_estab_forma ON public.orcamento_configuracao_pagamento (estabelecimento_id, forma_pagamento_id);
    CREATE INDEX ix_valor_prof_orc_estab_prof_funcao ON public.orcamento_valor_profissional (estabelecimento_id, profissional_usuario_id, funcao);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260430123214_Fase6_1OrcamentoCatalogos') THEN
    INSERT INTO public.__ef_migrations_history ("MigrationId", "ProductVersion")
    VALUES ('20260430123214_Fase6_1OrcamentoCatalogos', '10.0.0');
    END IF;
END $EF$;

-- ============================================================
-- RLS — defense-in-depth (LGPD). Padrão tenant-scoped: leitura para
-- vinculados ativos OU dono; INSERT/UPDATE/DELETE só service_role.
-- service_role bypassa RLS automaticamente.
-- ============================================================

DO $$
DECLARE
    t text;
    tabelas text[] := ARRAY[
        'orcamento_catalogo_cirurgia',
        'orcamento_valor_profissional',
        'orcamento_configuracao_local_cirurgia',
        'orcamento_catalogo_equipe',
        'orcamento_catalogo_implante',
        'orcamento_configuracao_pagamento'
    ];
BEGIN
    FOREACH t IN ARRAY tabelas LOOP
        EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY;', t);
        EXECUTE format('ALTER TABLE public.%I FORCE ROW LEVEL SECURITY;', t);
        EXECUTE format('DROP POLICY IF EXISTS %I_select_tenant ON public.%I;', t, t);
        EXECUTE format($p$
            CREATE POLICY %I_select_tenant
                ON public.%I
                FOR SELECT
                TO authenticated
                USING (
                    estabelecimento_id IN (
                        SELECT v.estabelecimento_id
                        FROM public.vinculo_profissional_estabelecimento v
                        WHERE v.profissional_usuario_id = auth.uid()
                          AND v.status = 'Ativo'
                    )
                    OR estabelecimento_id IN (
                        SELECT e.id
                        FROM public.estabelecimentos e
                        WHERE e.dono_usuario_id = auth.uid()
                    )
                );
        $p$, t, t);
    END LOOP;
END $$;
