-- Anexos de prontuário. Blobs ficam no Supabase Storage (bucket 'prontuario-anexos');
-- esta tabela guarda apenas metadata + storage_path.
-- EF migration: 20260418222504_CreateProntuarioAnexos

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260418222504_CreateProntuarioAnexos') THEN

    CREATE TABLE public.prontuario_anexos (
        id                        bigint GENERATED BY DEFAULT AS IDENTITY,
        prontuario_id             bigint NOT NULL,
        evolucao_id               bigint,
        estabelecimento_id        bigint NOT NULL,
        storage_path              character varying(500) NOT NULL,
        nome_original             character varying(300) NOT NULL,
        mime_type                 character varying(100) NOT NULL,
        tamanho_bytes             bigint NOT NULL,
        criado_por_usuario_id     uuid NOT NULL,
        criado_em                 timestamp with time zone NOT NULL,
        arquivado_em              timestamp with time zone,
        arquivado_por_usuario_id  uuid,
        CONSTRAINT "PK_prontuario_anexos" PRIMARY KEY (id)
    );
    CREATE INDEX ix_anexos_prontuario
        ON public.prontuario_anexos (prontuario_id, arquivado_em);
    CREATE INDEX ix_anexos_evolucao
        ON public.prontuario_anexos (evolucao_id);

    ALTER TABLE public.prontuario_anexos
        ADD CONSTRAINT fk_anexo_prontuario
        FOREIGN KEY (prontuario_id) REFERENCES public.prontuarios(id) ON DELETE CASCADE;
    ALTER TABLE public.prontuario_anexos
        ADD CONSTRAINT fk_anexo_evolucao
        FOREIGN KEY (evolucao_id) REFERENCES public.prontuario_evolucoes(id) ON DELETE SET NULL;
    ALTER TABLE public.prontuario_anexos
        ADD CONSTRAINT fk_anexo_estabelecimento
        FOREIGN KEY (estabelecimento_id) REFERENCES public.estabelecimentos(id) ON DELETE RESTRICT;
    ALTER TABLE public.prontuario_anexos
        ADD CONSTRAINT fk_anexo_autor
        FOREIGN KEY (criado_por_usuario_id) REFERENCES public.usuarios(id) ON DELETE RESTRICT;

    ALTER TABLE public.prontuario_anexos ENABLE ROW LEVEL SECURITY;

    COMMENT ON TABLE public.prontuario_anexos IS
        'Metadata de anexos do prontuário (blob fica em Storage). Append-only; remoção lógica via arquivado_em.';

    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260418222504_CreateProntuarioAnexos') THEN
    INSERT INTO public.__ef_migrations_history ("MigrationId", "ProductVersion")
    VALUES ('20260418222504_CreateProntuarioAnexos', '10.0.0');
    END IF;
END $EF$;
