-- Prontuários + evoluções append-only.
-- EF migration: 20260418160628_CreateProntuarios

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260418160628_CreateProntuarios') THEN

    CREATE TABLE public.prontuarios (
        id                       bigint GENERATED BY DEFAULT AS IDENTITY,
        paciente_id              bigint NOT NULL,
        estabelecimento_id       bigint NOT NULL,
        modelo_de_prontuario_id  bigint NOT NULL,
        criado_em                timestamp with time zone NOT NULL,
        atualizado_em            timestamp with time zone,
        CONSTRAINT "PK_prontuarios" PRIMARY KEY (id)
    );
    CREATE UNIQUE INDEX uq_prontuario_paciente_estabelecimento
        ON public.prontuarios (paciente_id, estabelecimento_id);
    ALTER TABLE public.prontuarios
        ADD CONSTRAINT fk_prontuario_paciente
        FOREIGN KEY (paciente_id) REFERENCES public.pacientes(id) ON DELETE CASCADE;
    ALTER TABLE public.prontuarios
        ADD CONSTRAINT fk_prontuario_estabelecimento
        FOREIGN KEY (estabelecimento_id) REFERENCES public.estabelecimentos(id) ON DELETE RESTRICT;
    ALTER TABLE public.prontuarios
        ADD CONSTRAINT fk_prontuario_modelo
        FOREIGN KEY (modelo_de_prontuario_id) REFERENCES public.modelo_de_prontuario(id) ON DELETE RESTRICT;
    ALTER TABLE public.prontuarios ENABLE ROW LEVEL SECURITY;

    CREATE TABLE public.prontuario_evolucoes (
        id                              bigint GENERATED BY DEFAULT AS IDENTITY,
        prontuario_id                   bigint NOT NULL,
        autor_usuario_id                uuid NOT NULL,
        conteudo                        jsonb NOT NULL,
        modelo_snapshot                 jsonb NOT NULL,
        modelo_de_prontuario_id_origem  bigint NOT NULL,
        criada_em                       timestamp with time zone NOT NULL,
        CONSTRAINT "PK_prontuario_evolucoes" PRIMARY KEY (id)
    );
    CREATE INDEX ix_evolucoes_prontuario_data
        ON public.prontuario_evolucoes (prontuario_id, criada_em);
    ALTER TABLE public.prontuario_evolucoes
        ADD CONSTRAINT fk_evolucao_prontuario
        FOREIGN KEY (prontuario_id) REFERENCES public.prontuarios(id) ON DELETE CASCADE;
    ALTER TABLE public.prontuario_evolucoes
        ADD CONSTRAINT fk_evolucao_autor
        FOREIGN KEY (autor_usuario_id) REFERENCES public.usuarios(id) ON DELETE RESTRICT;
    ALTER TABLE public.prontuario_evolucoes ENABLE ROW LEVEL SECURITY;

    -- Imutabilidade: bloqueia UPDATE e DELETE em evoluções em nível de banco.
    -- Defense-in-depth — a camada de aplicação nem expõe métodos, mas garantimos aqui também.
    CREATE OR REPLACE FUNCTION public.prontuario_evolucao_imutavel()
    RETURNS trigger LANGUAGE plpgsql AS $fn$
    BEGIN
        RAISE EXCEPTION 'Evoluções de prontuário são imutáveis. Crie uma nova evolução para corrigir.';
    END;
    $fn$;

    CREATE TRIGGER tg_evolucao_no_update
        BEFORE UPDATE ON public.prontuario_evolucoes
        FOR EACH ROW EXECUTE FUNCTION public.prontuario_evolucao_imutavel();

    CREATE TRIGGER tg_evolucao_no_delete
        BEFORE DELETE ON public.prontuario_evolucoes
        FOR EACH ROW EXECUTE FUNCTION public.prontuario_evolucao_imutavel();

    COMMENT ON TABLE public.prontuarios IS
        'Prontuário único por paciente × estabelecimento (container). Evoluções vão em prontuario_evolucoes.';
    COMMENT ON TABLE public.prontuario_evolucoes IS
        'Evoluções APPEND-ONLY (triggers bloqueiam UPDATE/DELETE). Cada entrada guarda snapshot do template.';

    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260418160628_CreateProntuarios') THEN
    INSERT INTO public.__ef_migrations_history ("MigrationId", "ProductVersion")
    VALUES ('20260418160628_CreateProntuarios', '10.0.0');
    END IF;
END $EF$;
