-- Item 1.7 (Docs/01_FASE_1_HARDENING.md) — tabelas auxiliares de IA sem aggregate EF.
--
-- Estas tabelas são acessadas via Dapper (raw SQL) por AiCacheRepository
-- e AiRateLimitRepository. NÃO há entidade EF correspondente, portanto
-- nunca aparecem em uma migration EF — vivem como SQL puro em
-- supabase/migrations/.
--
-- Idempotência: usamos CREATE TABLE IF NOT EXISTS / CREATE INDEX IF NOT
-- EXISTS para casar com a estratégia idempotente do supabase CLI
-- (mesmo padrão do EF, sem precisar do registro em __ef_migrations_history).
--
-- Pendente: RLS policies. Como ai_outputs_cache e ai_rate_limits são
-- tabelas internas usadas só pelo backend (service_role), o caminho
-- esperado é "REVOKE ALL FROM authenticated/anon" — fica para a sprint
-- de RLS na Fase 2 junto com ai_audit_logs e audit_delete_attempts.

-- ---------------------------------------------------------------------
-- ai_outputs_cache
-- ---------------------------------------------------------------------
-- Cache de respostas da IA chaveado por hash sha256 do prompt.
-- prompt_hash é PK porque o mesmo prompt produz a mesma resposta
-- determinística (dentro da janela de TTL).
CREATE TABLE IF NOT EXISTS public.ai_outputs_cache (
    prompt_hash         character varying(64) NOT NULL,
    estabelecimento_id  bigint                NOT NULL,
    endpoint            character varying(80) NOT NULL,
    output              text                  NOT NULL,
    tokens_in           integer,
    tokens_out          integer,
    expira_em           timestamp with time zone NOT NULL,
    criado_em           timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT pk_ai_outputs_cache PRIMARY KEY (prompt_hash)
);

-- Índice para o job de limpeza (DELETE WHERE expira_em < now()).
CREATE INDEX IF NOT EXISTS ix_ai_outputs_cache_expira
    ON public.ai_outputs_cache (expira_em);

-- Índice multi-tenant (consultas filtradas por estabelecimento + endpoint
-- caso virem necessárias para auditoria/relatório).
CREATE INDEX IF NOT EXISTS ix_ai_outputs_cache_estab_endpoint
    ON public.ai_outputs_cache (estabelecimento_id, endpoint);

-- ---------------------------------------------------------------------
-- ai_rate_limits
-- ---------------------------------------------------------------------
-- Janela deslizante de 1 minuto por usuário.
-- (usuario_id, periodo_inicio) é único — uma linha por usuário por
-- janela. O backend faz UPSERT incrementando "contagem" e atualizando
-- "ultimo_acesso".
CREATE TABLE IF NOT EXISTS public.ai_rate_limits (
    id              bigint GENERATED BY DEFAULT AS IDENTITY,
    usuario_id      uuid                     NOT NULL,
    periodo_inicio  timestamp with time zone NOT NULL,
    contagem        integer                  NOT NULL DEFAULT 1,
    ultimo_acesso   timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT pk_ai_rate_limits PRIMARY KEY (id),
    CONSTRAINT uq_ai_rate_limits_usuario_periodo UNIQUE (usuario_id, periodo_inicio)
);

-- Índice para varredura de limpeza de janelas antigas
-- (DELETE WHERE periodo_inicio < now() - interval '1 hour').
CREATE INDEX IF NOT EXISTS ix_ai_rate_limits_periodo
    ON public.ai_rate_limits (periodo_inicio);
