-- Audit log LGPD — todo acesso (leitura/escrita) a dados de prontuário é registrado.
-- Append-only: triggers bloqueiam UPDATE e DELETE em nível de banco.
-- EF migration: 20260418221604_CreateProntuarioAcessoLog

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260418221604_CreateProntuarioAcessoLog') THEN

    CREATE TABLE public.prontuario_acesso_log (
        id                  bigint GENERATED BY DEFAULT AS IDENTITY,
        prontuario_id       bigint NOT NULL,
        usuario_id          uuid NOT NULL,
        estabelecimento_id  bigint NOT NULL,
        tipo_acesso         character varying(20) NOT NULL,
        ocorrido_em         timestamp with time zone NOT NULL,
        CONSTRAINT "PK_prontuario_acesso_log" PRIMARY KEY (id)
    );
    CREATE INDEX ix_acesso_log_prontuario_data
        ON public.prontuario_acesso_log (prontuario_id, ocorrido_em);
    CREATE INDEX ix_acesso_log_usuario
        ON public.prontuario_acesso_log (usuario_id);

    ALTER TABLE public.prontuario_acesso_log
        ADD CONSTRAINT fk_acesso_log_prontuario
        FOREIGN KEY (prontuario_id) REFERENCES public.prontuarios(id) ON DELETE CASCADE;
    ALTER TABLE public.prontuario_acesso_log
        ADD CONSTRAINT fk_acesso_log_usuario
        FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id) ON DELETE RESTRICT;
    ALTER TABLE public.prontuario_acesso_log
        ADD CONSTRAINT fk_acesso_log_estabelecimento
        FOREIGN KEY (estabelecimento_id) REFERENCES public.estabelecimentos(id) ON DELETE RESTRICT;
    ALTER TABLE public.prontuario_acesso_log ENABLE ROW LEVEL SECURITY;

    CREATE OR REPLACE FUNCTION public.prontuario_acesso_log_imutavel()
    RETURNS trigger LANGUAGE plpgsql AS $fn$
    BEGIN
        RAISE EXCEPTION 'Logs de acesso ao prontuário são imutáveis por exigência de auditoria (LGPD).';
    END;
    $fn$;

    CREATE TRIGGER tg_acesso_log_no_update
        BEFORE UPDATE ON public.prontuario_acesso_log
        FOR EACH ROW EXECUTE FUNCTION public.prontuario_acesso_log_imutavel();

    CREATE TRIGGER tg_acesso_log_no_delete
        BEFORE DELETE ON public.prontuario_acesso_log
        FOR EACH ROW EXECUTE FUNCTION public.prontuario_acesso_log_imutavel();

    COMMENT ON TABLE public.prontuario_acesso_log IS
        'Log imutável de acessos a prontuários (LGPD Art. 37 — rastreabilidade). Escrito pelo backend a cada leitura ou escrita.';

    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260418221604_CreateProntuarioAcessoLog') THEN
    INSERT INTO public.__ef_migrations_history ("MigrationId", "ProductVersion")
    VALUES ('20260418221604_CreateProntuarioAcessoLog', '10.0.0');
    END IF;
END $EF$;
