
DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260419000948_CriarAutomacoes') THEN
    ALTER TABLE public.agendamentos ADD lembrete_por_email_enviado boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260419000948_CriarAutomacoes') THEN
    CREATE TABLE public.configuracoes_automacao (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        estabelecimento_id bigint NOT NULL,
        lembretes_habilitados boolean NOT NULL,
        horas_antecedencia_lembrete integer NOT NULL,
        expiracao_orcamentos_habilitada boolean NOT NULL,
        email_remetente character varying(320),
        atualizado_em timestamp with time zone NOT NULL,
        CONSTRAINT "PK_configuracoes_automacao" PRIMARY KEY (id),
        CONSTRAINT fk_configuracao_automacao_estabelecimento FOREIGN KEY (estabelecimento_id) REFERENCES public.estabelecimentos (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260419000948_CriarAutomacoes') THEN
    CREATE UNIQUE INDEX uq_configuracoes_automacao_estabelecimento ON public.configuracoes_automacao (estabelecimento_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260419000948_CriarAutomacoes') THEN
    INSERT INTO public.__ef_migrations_history ("MigrationId", "ProductVersion")
    VALUES ('20260419000948_CriarAutomacoes', '10.0.0');
    END IF;
END $EF$;
