-- Fase 4 — Schema consolidado (Waves 2 e 3).
--
-- Itens cobertos:
--   4.2  solicitacoes_vinculo (vínculo inverso: profissional -> estabelecimento).
--   4.3  LGPD: pacientes.anonimizado_em/_por_usuario_id, lgpd_anonimizacoes,
--        lgpd_consentimentos.
--   4.12 ANVISA: receitas.requer_retencao + backfill.
--   4.13 TUSS/CBHPM: catalogo_procedimentos + seed de 83 procedimentos.
--
-- Origem do DDL: dotnet ef migrations script --idempotent
-- (20260429200248_Fase3ParidadeSchema -> 20260430010241_Fase4Schema).
-- BEGIN/COMMIT removidos: supabase CLI gerencia transação por arquivo.
--
-- RLS para estas tabelas vai no arquivo separado 20260430010242_rls_fase4_tabelas.sql.

-- =====================================================================
-- 1) DDL gerado pelo EF Core (idempotente)
-- =====================================================================

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260430010241_Fase4Schema') THEN
    ALTER TABLE public.receitas ADD requer_retencao boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260430010241_Fase4Schema') THEN
    ALTER TABLE public.pacientes ADD anonimizado_em timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260430010241_Fase4Schema') THEN
    ALTER TABLE public.pacientes ADD anonimizado_por_usuario_id uuid;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260430010241_Fase4Schema') THEN
    CREATE TABLE public.catalogo_procedimentos (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        codigo character varying(20) NOT NULL,
        nome character varying(300) NOT NULL,
        origem character varying(20) NOT NULL,
        capitulo character varying(80),
        ativo boolean NOT NULL DEFAULT TRUE,
        CONSTRAINT "PK_catalogo_procedimentos" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260430010241_Fase4Schema') THEN
    CREATE TABLE public.lgpd_anonimizacoes (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        tabela character varying(80) NOT NULL,
        registro_id bigint NOT NULL,
        motivo character varying(40) NOT NULL,
        anonimizado_em timestamp with time zone NOT NULL,
        executado_por_usuario_id uuid,
        CONSTRAINT "PK_lgpd_anonimizacoes" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260430010241_Fase4Schema') THEN
    CREATE TABLE public.lgpd_consentimentos (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        usuario_id uuid NOT NULL,
        tipo character varying(40) NOT NULL,
        versao character varying(20) NOT NULL,
        aceito_em timestamp with time zone NOT NULL,
        ip_origem character varying(45),
        user_agent character varying(500),
        CONSTRAINT "PK_lgpd_consentimentos" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260430010241_Fase4Schema') THEN
    CREATE TABLE public.solicitacoes_vinculo (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        profissional_usuario_id uuid NOT NULL,
        estabelecimento_id bigint NOT NULL,
        status character varying(20) NOT NULL,
        mensagem character varying(1000),
        criada_em timestamp with time zone NOT NULL,
        respondida_em timestamp with time zone,
        respondida_por_usuario_id uuid,
        motivo_recusa character varying(500),
        CONSTRAINT "PK_solicitacoes_vinculo" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260430010241_Fase4Schema') THEN
    CREATE INDEX ix_catalogo_procedimentos_ativo_origem ON public.catalogo_procedimentos (ativo, origem);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260430010241_Fase4Schema') THEN
    CREATE UNIQUE INDEX uq_catalogo_procedimentos_codigo ON public.catalogo_procedimentos (codigo);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260430010241_Fase4Schema') THEN
    CREATE INDEX ix_lgpd_anonimizacoes_motivo_data ON public.lgpd_anonimizacoes (motivo, anonimizado_em);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260430010241_Fase4Schema') THEN
    CREATE INDEX ix_lgpd_anonimizacoes_tabela_registro ON public.lgpd_anonimizacoes (tabela, registro_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260430010241_Fase4Schema') THEN
    CREATE INDEX ix_lgpd_consentimentos_usuario_tipo_data ON public.lgpd_consentimentos (usuario_id, tipo, aceito_em);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260430010241_Fase4Schema') THEN
    CREATE INDEX ix_solicitacoes_vinculo_estab_status_data ON public.solicitacoes_vinculo (estabelecimento_id, status, criada_em);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260430010241_Fase4Schema') THEN
    CREATE INDEX ix_solicitacoes_vinculo_profissional_status ON public.solicitacoes_vinculo (profissional_usuario_id, status);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260430010241_Fase4Schema') THEN
    CREATE UNIQUE INDEX uq_solicitacoes_vinculo_pendente ON public.solicitacoes_vinculo (profissional_usuario_id, estabelecimento_id) WHERE status = 'Pendente';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260430010241_Fase4Schema') THEN
    INSERT INTO public.__ef_migrations_history ("MigrationId", "ProductVersion")
    VALUES ('20260430010241_Fase4Schema', '10.0.0');
    END IF;
END $EF$;

-- =====================================================================
-- 2) Salvaguarda — UNIQUE PARCIAL em solicitacoes_vinculo
-- =====================================================================
-- O EF já emite o filtro WHERE status='Pendente', mas mantemos esta verificação
-- para garantir o índice em ambientes onde o DDL gerado evolua.
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_indexes
        WHERE schemaname = 'public' AND indexname = 'uq_solicitacoes_vinculo_pendente'
    ) THEN
        CREATE UNIQUE INDEX uq_solicitacoes_vinculo_pendente
            ON public.solicitacoes_vinculo (profissional_usuario_id, estabelecimento_id)
            WHERE status = 'Pendente';
    END IF;
END $$;

-- =====================================================================
-- 3) Backfill — receitas.requer_retencao
-- =====================================================================
-- Receitas Controladas (Portaria 344/98) e Antibióticos (RDC 471/2021) exigem
-- retenção pela farmácia. Backfill idempotente: filtro garante que rodar duas
-- vezes não causa efeito (linhas já com TRUE são ignoradas pelo WHERE).
UPDATE public.receitas
SET requer_retencao = true
WHERE tipo IN ('Controlada', 'Antibiotico')
  AND requer_retencao = false;

-- =====================================================================
-- 4) Seed TUSS/CBHPM — catalogo_procedimentos (83 entradas)
-- =====================================================================
-- Fonte: backend/src/Services/Imedto.Backend.Application/Catalogo/SeedsProcedimentosCatalogo.cs
-- Idempotente via ON CONFLICT (codigo) DO NOTHING — evita duplicar em re-runs.
INSERT INTO public.catalogo_procedimentos (codigo, nome, origem, capitulo, ativo) VALUES
    -- Consultas
    ('10101012', 'Consulta médica em atenção primária', 'TUSS', 'Consultas', true),
    ('10101039', 'Consulta médica em consultório (horário normal)', 'TUSS', 'Consultas', true),
    ('10101047', 'Consulta médica em pronto atendimento/urgência', 'TUSS', 'Consultas', true),
    ('10102016', 'Consulta odontológica', 'TUSS', 'Consultas', true),
    ('10103011', 'Consulta de enfermagem', 'TUSS', 'Consultas', true),
    ('10105014', 'Consulta nutricional', 'TUSS', 'Consultas', true),
    ('10104010', 'Consulta em psicologia', 'TUSS', 'Consultas', true),
    -- Cirurgias plásticas
    ('30724019', 'Rinoplastia', 'TUSS', 'Cirurgia / Sistema tegumentar', true),
    ('30724027', 'Mentoplastia', 'TUSS', 'Cirurgia / Sistema tegumentar', true),
    ('30724035', 'Otoplastia', 'TUSS', 'Cirurgia / Sistema tegumentar', true),
    ('30724043', 'Blefaroplastia superior', 'TUSS', 'Cirurgia / Sistema tegumentar', true),
    ('30724051', 'Blefaroplastia inferior', 'TUSS', 'Cirurgia / Sistema tegumentar', true),
    ('30724078', 'Ritidoplastia (face lift)', 'TUSS', 'Cirurgia / Sistema tegumentar', true),
    ('30724094', 'Mamoplastia redutora', 'TUSS', 'Cirurgia / Sistema tegumentar', true),
    ('30724105', 'Lipoaspiração', 'TUSS', 'Cirurgia / Sistema tegumentar', true),
    ('30724113', 'Abdominoplastia', 'TUSS', 'Cirurgia / Sistema tegumentar', true),
    ('30724121', 'Lipoenxertia (lipofilling)', 'TUSS', 'Cirurgia / Sistema tegumentar', true),
    ('30724148', 'Mamoplastia de aumento (implante mamário)', 'TUSS', 'Cirurgia / Sistema tegumentar', true),
    ('30724156', 'Mastopexia', 'TUSS', 'Cirurgia / Sistema tegumentar', true),
    ('30724164', 'Braquioplastia', 'TUSS', 'Cirurgia / Sistema tegumentar', true),
    ('30724172', 'Gluteoplastia', 'TUSS', 'Cirurgia / Sistema tegumentar', true),
    -- Cirurgias digestivas
    ('30602025', 'Apendicectomia', 'TUSS', 'Cirurgia / Sistema digestivo', true),
    ('30602033', 'Colecistectomia laparoscópica', 'TUSS', 'Cirurgia / Sistema digestivo', true),
    ('30602041', 'Herniorrafia inguinal (unilateral)', 'TUSS', 'Cirurgia / Sistema digestivo', true),
    ('30602050', 'Herniorrafia umbilical', 'TUSS', 'Cirurgia / Sistema digestivo', true),
    ('30602068', 'Gastrectomia parcial', 'TUSS', 'Cirurgia / Sistema digestivo', true),
    ('30602076', 'Colectomia (ressecção do cólon)', 'TUSS', 'Cirurgia / Sistema digestivo', true),
    -- Cirurgias ortopédicas
    ('30901014', 'Artroscopia de joelho diagnóstica', 'TUSS', 'Cirurgia / Sistema musculoesquelético', true),
    ('30901022', 'Artroscopia de joelho com meniscectomia', 'TUSS', 'Cirurgia / Sistema musculoesquelético', true),
    ('30901030', 'Reconstrução do ligamento cruzado anterior', 'TUSS', 'Cirurgia / Sistema musculoesquelético', true),
    ('30901049', 'Artroscopia de ombro', 'TUSS', 'Cirurgia / Sistema musculoesquelético', true),
    ('30910014', 'Osteossíntese de fratura de fêmur', 'TUSS', 'Cirurgia / Sistema musculoesquelético', true),
    ('30910022', 'Artroplastia total de quadril', 'TUSS', 'Cirurgia / Sistema musculoesquelético', true),
    ('30910030', 'Artroplastia total de joelho', 'TUSS', 'Cirurgia / Sistema musculoesquelético', true),
    -- Endoscopias
    ('40307054', 'Endoscopia digestiva alta', 'TUSS', 'Endoscopia', true),
    ('40307062', 'Colonoscopia', 'TUSS', 'Endoscopia', true),
    ('40307070', 'Colonoscopia com polipectomia', 'TUSS', 'Endoscopia', true),
    ('40307089', 'Videolaparoscopia diagnóstica', 'TUSS', 'Endoscopia', true),
    ('40308040', 'Broncoscopia diagnóstica', 'TUSS', 'Endoscopia', true),
    -- Cardiologia / diagnóstico e radiologia
    ('40312027', 'Eletrocardiograma (ECG)', 'TUSS', 'Cardiologia / Diagnóstico', true),
    ('40312035', 'Ecocardiograma transtorácico', 'TUSS', 'Cardiologia / Diagnóstico', true),
    ('40312043', 'Holter 24h', 'TUSS', 'Cardiologia / Diagnóstico', true),
    ('40312051', 'Teste ergométrico (ergometria)', 'TUSS', 'Cardiologia / Diagnóstico', true),
    ('40801026', 'Tomografia computadorizada de crânio', 'TUSS', 'Radiologia', true),
    ('40801034', 'Tomografia computadorizada de tórax', 'TUSS', 'Radiologia', true),
    ('40801042', 'Ressonância magnética de coluna lombar', 'TUSS', 'Radiologia', true),
    ('40801050', 'Ressonância magnética de joelho', 'TUSS', 'Radiologia', true),
    ('40901017', 'Ultrassonografia de abdome total', 'TUSS', 'Radiologia', true),
    ('40901025', 'Ultrassonografia pélvica transvaginal', 'TUSS', 'Radiologia', true),
    ('40901033', 'Ultrassonografia de mama bilateral', 'TUSS', 'Radiologia', true),
    ('40901041', 'Mamografia bilateral', 'TUSS', 'Radiologia', true),
    ('40901050', 'Densitometria óssea', 'TUSS', 'Radiologia', true),
    -- Dermatologia
    ('30701014', 'Exérese de lesão de pele (até 1 cm)', 'TUSS', 'Dermatologia', true),
    ('30701022', 'Exérese de lesão de pele (1 a 3 cm)', 'TUSS', 'Dermatologia', true),
    ('30701030', 'Biópsia de pele', 'TUSS', 'Dermatologia', true),
    ('30701049', 'Crioterapia (lesão única)', 'TUSS', 'Dermatologia', true),
    ('30701057', 'Peeling químico superficial', 'TUSS', 'Dermatologia', true),
    -- Ginecologia / obstetrícia
    ('31309016', 'Parto vaginal (normal)', 'TUSS', 'Obstetrícia', true),
    ('31309024', 'Cesariana', 'TUSS', 'Obstetrícia', true),
    ('31309032', 'Curetagem uterina', 'TUSS', 'Ginecologia', true),
    ('31309040', 'Histerectomia total abdominal', 'TUSS', 'Ginecologia', true),
    ('31309059', 'Laparoscopia ginecológica diagnóstica', 'TUSS', 'Ginecologia', true),
    ('31309067', 'Colposcopia', 'TUSS', 'Ginecologia', true),
    -- Odontologia
    ('81000010', 'Exame clínico odontológico', 'TUSS', 'Odontologia', true),
    ('81000029', 'Radiografia periapical (unitária)', 'TUSS', 'Odontologia', true),
    ('81000061', 'Restauração de resina composta — face única', 'TUSS', 'Odontologia', true),
    ('81000088', 'Extração de dente permanente', 'TUSS', 'Odontologia', true),
    ('81000096', 'Raspagem e alisamento radicular (por sextante)', 'TUSS', 'Odontologia', true),
    ('81000100', 'Tratamento de canal — dente unirradicular', 'TUSS', 'Odontologia', true),
    ('81000118', 'Tratamento de canal — dente multirradicular', 'TUSS', 'Odontologia', true),
    ('81000126', 'Instalação de implante osseointegrado', 'TUSS', 'Odontologia', true),
    ('81000134', 'Coroa metálica fundida', 'TUSS', 'Odontologia', true),
    ('81000142', 'Coroa cerâmica sobre implante', 'TUSS', 'Odontologia', true),
    ('81000150', 'Aparelho ortodôntico fixo (instalação)', 'TUSS', 'Odontologia', true),
    -- Anestesiologia
    ('20101015', 'Anestesia geral (por tempo cirúrgico)', 'TUSS', 'Anestesiologia', true),
    ('20101023', 'Anestesia regional (peridural/raqui)', 'TUSS', 'Anestesiologia', true),
    ('20101031', 'Sedação consciente', 'TUSS', 'Anestesiologia', true),
    -- Neurologia / neurocirurgia
    ('30809016', 'Eletroencefalograma (EEG)', 'TUSS', 'Neurologia / Diagnóstico', true),
    ('30809024', 'Potencial evocado auditivo', 'TUSS', 'Neurologia / Diagnóstico', true),
    ('31001016', 'Descompressão de nervo periférico (nervo único)', 'TUSS', 'Neurocirurgia', true),
    -- Cardiologia / intervenção
    ('30201013', 'Cateterismo cardíaco diagnóstico', 'TUSS', 'Cardiologia / Intervenção', true),
    ('30201021', 'Angioplastia coronariana transluminal percutânea', 'TUSS', 'Cardiologia / Intervenção', true),
    ('30201030', 'Implante de marcapasso definitivo (câmara dupla)', 'TUSS', 'Cardiologia / Intervenção', true)
ON CONFLICT (codigo) DO NOTHING;
