
DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260418234227_CriarFinanceiro') THEN
    CREATE TABLE public.lancamentos (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        estabelecimento_id bigint NOT NULL,
        tipo character varying(20) NOT NULL,
        descricao character varying(300) NOT NULL,
        valor numeric(12,2) NOT NULL,
        data_vencimento date NOT NULL,
        data_pagamento date,
        status character varying(20) NOT NULL,
        categoria character varying(100) NOT NULL,
        orcamento_id bigint,
        criado_por_usuario_id uuid NOT NULL,
        criado_em timestamp with time zone NOT NULL,
        atualizado_em timestamp with time zone,
        CONSTRAINT "PK_lancamentos" PRIMARY KEY (id),
        CONSTRAINT fk_lancamento_estabelecimento FOREIGN KEY (estabelecimento_id) REFERENCES public.estabelecimentos (id) ON DELETE RESTRICT,
        CONSTRAINT fk_lancamento_orcamento FOREIGN KEY (orcamento_id) REFERENCES public.orcamentos (id) ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260418234227_CriarFinanceiro') THEN
    CREATE INDEX ix_lancamento_estab_status_venc ON public.lancamentos (estabelecimento_id, status, data_vencimento);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260418234227_CriarFinanceiro') THEN
    CREATE INDEX ix_lancamento_estab_tipo ON public.lancamentos (estabelecimento_id, tipo);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260418234227_CriarFinanceiro') THEN
    CREATE INDEX "IX_lancamentos_orcamento_id" ON public.lancamentos (orcamento_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.__ef_migrations_history WHERE "MigrationId" = '20260418234227_CriarFinanceiro') THEN
    INSERT INTO public.__ef_migrations_history ("MigrationId", "ProductVersion")
    VALUES ('20260418234227_CriarFinanceiro', '10.0.0');
    END IF;
END $EF$;

